.gitignore, C/c4Base.cc, C/c4Database.cc, C/c4Document1.cc, LiteCore/RevTrees/RawRevTree.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/ForestDataFile.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Support/Error.cc, LiteCore/Support/FilePath.cc, LiteCore/VersionVectors/VersionVector.cc, MSVC/ForestDB/ForestDB.vcxproj, MSVC/ForestDB/ForestDB.vcxproj.filters, MSVC/LiteCore.sln, MSVC/LiteCore.vcxproj, MSVC/LiteCore.vcxproj.filters, MSVC/asprintf.c, MSVC/asprintf.h, MSVC/dirent.h, MSVC/memmem.cc, MSVC/memmem.h, MSVC/vasprintf-msvc.c
Please review for any changes that don't seem appropriate
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/couchbase/couchbase-lite-core/1)
=> Changes needed for MSVC compilation

LiteCore/Indexes/MapReduceIndex.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteFleeceEach.cc, LiteCore/Storage/SQLiteIterator.cc, LiteCore/Storage/SQLiteKeyStore.cc
int64_t is long int on most 64-bit Linux systems, not long long
=> Explicit casts between long long and int64_t

LiteCore/Storage/QueryParser.hh, LiteCore/tests/QueryParserTest.cc
Works around limitation in GCC 4.x STL
Fixes #31
=> Made QueryParser class not copy/move/assign-able

Java/jni/native_glue.cc, Java/jni/native_glue.hh
- Fixed assertHeapBlock() for Android  (in fleece)
- Updated JNI for recent slice accessor changes
=> Fixed #72 - compilation failure and test failures with Android

CMakeLists.txt, CSharp/src/LiteCore.Shared/Constants.cs, CSharp/src/LiteCore.Shared/Interop/C4Base.cs, CSharp/src/LiteCore.Shared/Interop/C4Replicator_native.cs, CSharp/src/LiteCore.Shared/Interop/C4Socket_native.cs, CSharp/src/LiteCore.Shared/LiteCore.Shared.projitems, Replicator/CMakeLists.txt, Replicator/Replicator.def, Replicator/c4Replicator.cc
Dependent on https://github.com/couchbaselabs/BLIP-Cpp/pull/1 and https://github.com/couchbaselabs/fleece/pull/16
Most of the commit here is C# stuff, but there are a few things in C++ (notably, Windows complains about the ambiguity between fleece::slice and litecore::blip::slice despite them being the same thing)
=> Fixes for Windows (and possibly other non-Apple)

Java/CMakeLists.txt, Java/androidTest/java/com/couchbase/litecore/BaseTest.java, Java/androidTest/java/com/couchbase/litecore/C4QueryBaseTest.java, Java/androidTest/java/com/couchbase/litecore/C4QueryTest.java, Java/jni/native_c4query.cc, Java/src/com/couchbase/litecore/C4QueryEnumerator.java, Java/src/com/couchbase/litecore/Constants.java, Java/src/com/couchbase/litecore/fleece/FLArray.java, Java/src/com/couchbase/litecore/fleece/FLArrayIterator.java
https://github.com/couchbase/couchbase-lite-android/issues/1176
- Update C4QueryEnumerator
- Fixed unit tests
=> Fixed - 2.0: Catchup recent litecore changes

Java/CMakeLists.txt, Java/androidTest/java/com/couchbase/litecore/C4QueryBaseTest.java, Java/jni/native_c4replicator.cc, Java/jni/native_c4socket.cc, Java/src/com/couchbase/litecore/fleece/FLArrayIterator.java
- Fixed Android issue 1185 - 2.0: Unit Test failure on Jenkins [Ticket](https://github.com/couchbase/couchbase-lite-android/issues/1185)
- Java aggressively releases FLArrayIterator instance that is managed by LiteCore. It caused the crash.
- Catchup latest lite core changes
=> Bug fixes for Java (DB008)

CMakeLists.txt
Also correct trailing whitespace errors.
=> Search for libc++ headers from cbdeps.

Java/jni/native_document.cc, Java/src/com/couchbase/litecore/Document.java
- c4doc_resolveConflict
- c4doc_selectCommonAncestorRevision
=> Implemented JNI bindings for following methods:

CMakeLists.txt, build_cmake/scripts/test_unix.sh
Change-Id: I888a277eec9067603a44be165ac53de55d0a13b1
=> Enable RPATH for Linux libs; abort build on test failures

LiteCore/Query/QueryParser.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/tests/QueryTest.cc
=> Implement functionality for SELECT *

C/c4.def, C/c4.exp, C/c4Database.cc, C/include/c4Database.h, C/tests/c4DatabaseTest.cc, LiteCore/Database/Database.cc, LiteCore/Database/Database.hh, LiteCore/Database/PrebuiltCopier.cc, LiteCore/Database/PrebuiltCopier.hh, LiteCore/Support/FilePath.cc, Xcode/LiteCore.xcodeproj/project.pbxproj
I'm on the fence about the last refactor to put stuff into a C++ file (similar to Upgrader.cc) because there is nothing actually C++-ish about it, but I did anyway to be consistent and to allow a signature that uses `FilePath`.
=> Introduce a way to copy prebuilt DBs in from an application

C/c4Query.cc, C/include/c4Query.h, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Storage/KeyStore.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/QueryTest.cc
=> Refactor index creation and deletion to use named aliases

Java/src/com/couchbase/litecore/fleece/FLDict.java
https://github.com/couchbase/couchbase-lite-android/issues/1371
=> Fixed Android issue 1371 - NPE in `FLDict.asDict()`

tools/litecp/DBEndpoint.cc
If no ID property is specified, then it will mistakenly use _id for import.  Also a transaction needs to be started before Fleece encoding.
=> Fix for misbehaving cblite cp when source is JSON

Java/jni/native_c4socket.cc, Java/src/com/couchbase/litecore/C4Socket.java
This change is for https://github.com/couchbase/couchbase-lite-android/issues/1522.
=> Add message parameter to JNI C4Socket’s closed() method

Java/jni/native_c4query.cc
https://github.com/couchbase/couchbase-lite-android/issues/1614
=> Java: Fixed  Stemming is not working for FTS.

Java/src/com/couchbase/litecore/C4Document.java, Java/src/com/couchbase/litecore/fleece/Encoder.java, Java/src/com/couchbase/litecore/fleece/FLDict.java, Java/src/com/couchbase/litecore/fleece/FLEncoder.java, Java/src/com/couchbase/litecore/fleece/FLSharedKeys.java
https://github.com/couchbase/couchbase-lite-android/issues/1627
=> Fixed - 2.0: Remove unnecessary lock for FLSharedKeys

Java/src/com/couchbase/litecore/C4Document.java
- Added equals(Object) and hashCode() to C4Document class.
=> Fixed Android 1632

LiteCore/Support/FilePath.cc, LiteCore/tests/DataFileTest.cc, MSVC/SQLiteTempDirectory.cc
While at it, fixed a problem that it uncovered.  Verified these assertions on Windows, Linux, and Mac.
=> Add test for canonical paths

modules/docs/pages/replication-protocol.adoc
See https://github.com/couchbase/sync_gateway/issues/3372#issuecomment-374784714
=> Update replication spec w/ regards to proposeChanges and normal mode

C/c4Private.h, LiteCore/Database/Database.cc, LiteCore/Database/PrebuiltCopier.cc, Replicator/DBWorker.cc, Replicator/DBWorker.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
(Support importing replicator last sequence when copy the database)
=> import replicator last seq when copying database

Java/jni/native_fleece.cc, Java/jni/native_glue.cc, Java/jni/native_glue.hh
See https://github.com/couchbase/couchbase-lite-android/issues/1742 (Couchbase mobile 2.0.2 Emoji Support).  This is a bug in the Android NDK that we have to work around...
=> Fixes Android emoji issue

modules/docs/pages/replication-protocol.adoc
Related to https://github.com/couchbase/sync_gateway/issues/3738
=> Document norev message

modules/docs/pages/replication-protocol.adoc
Related to https://github.com/couchbase/sync_gateway/issues/3738
=> Update description of error field, add "reason" field.

LiteCore/Database/PrebuiltCopier.cc, LiteCore/Support/FilePath.cc
Made alternate of the tempDirectory based on moving (or renaming) target instead of source.
=> Make alternate tempDirectory based on move target

Replicator/c4Socket+Internal.hh, Replicator/c4Socket.cc
* Added try/catch to c4socket_received and c4socket_gotHTTPResponse and close socket when catching an exception.
* Exposed factory object on C4SocketImpl.
#562
=> Fixed #562: Add try/catch to c4socket_received and c4socket_gotHTTPResponse

Java/jni/native_c4replicator.cc, Java/src/com/couchbase/litecore/C4Constants.java, Java/src/com/couchbase/litecore/C4Replicator.java, Java/src/com/couchbase/litecore/C4ReplicatorListener.java
- update document ended JNI binding, c4 replicator and replicator listener.
=> Document Replication eventing

Java/jni/native_c4replicator.cc, Java/src/com/couchbase/litecore/C4Document.java, Java/src/com/couchbase/litecore/C4DocumentEnded.java, Java/src/com/couchbase/litecore/C4Replicator.java, Java/src/com/couchbase/litecore/C4ReplicatorListener.java
Add accessRemoved method, support documents ended callback in batch, add C4DocumentEnded class.
=> Replication eventing API updates in LiteCore Android/JNI

Java/jni/native_c4.cc
=> docs: update the signature of the writeToBinaryFile method

C/tests/c4QueryTest.cc, LiteCore/Query/SQLiteKeyStore+FTSIndexes.cc
Need a ruling on whether or not to put this into Iridium (still time left?)
=> Fixes #723 and adds a test for it

C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc
=> Account for datasource aliases in column names

LiteCore/Database/TreeDocument.cc
not sure, whether this is the best way to fix this issue. 
Ref: #788
=> fix: conflict error not returning

C/include/c4Document+Fleece.h
* NONNULL not allowing to build in XCode. When changed to C4NONULL, it worked.
=> fix: build error

LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryTest.cc
Fixes #761 by remembering aliases and keeping track of things that use them
=>  Account for result aliases when creating SQL

LiteCore/Query/SQLiteFleeceEach.cc
SQLiteFleeceEach was failing to parse Fleece data at an odd address.
This was already worked around in the fix for #589 but that only
covered regular queries, not the special ‘virtual table’ used by ANY
and EVERY queries. This time I made sure that there are no more places
where this bug could lurk.
Fixes #787
Copied from: https://github.com/couchbase/couchbase-lite-core/commit/e0a0c246d26453599b236f10ef269273b5bee708
=> Fixed “datatype mismatch” error in ANY/EVERY query

Replicator/Replicator.cc
* check for existing conflicts only in pull mode.
=> CBL-94: fix: only resolve in pull mode

Replicator/Replicator+Checkpoints.cc
The introduction of _db->use made it so that any error response was incorrectly followed by another response for the same request.
=> [CBL-108] Fix a regression regarding handleSetCheckpoint

Xcode/xcconfigs/Project.xcconfig
* update litecore verion updated
=> fix: version bump

C/c4.exp
Added symbols used by JNI to c4.exp
=> Add symbols used by JNI to c4.exp

Replicator/Replicator.cc
Need to come up with a testing method, but this will stop the replicator when a BLIP message containing 503 is received.  CBL should pick this up and react to it by retrying later.
=> CBL-126 Add 503 to the list of errors to stop replication

C/tests/c4Test.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/LiteCoreTest.hh, LiteCore/tests/LogEncoderTest.cc, LiteCore/tests/UpgraderTest.cc, Replicator/tests/ReplicatorLoopbackTest.cc
Otherwise if PR validation is running on multiple PRs at once the validation jobs will step on each other
=> CBL-343 Make the LiteCore/C4Tests databases (reasonably) unique

Xcode/xcconfigs/Project.xcconfig
=> bump version 

LiteCore/Storage/UnicodeCollator.cc, jenkins/jenkins_unix.sh
And Add it PR validation (using this PR to check)
=> Fix issues with Xcode build

C/c4.def, C/c4.exp, C/include/c4Replicator.h, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
c4repl_isDocumentPending and c4repl_pendingDocIDs
=> CBL-455 [API] Pending document ID APIs

C/c4.def, C/c4.exp, C/c4.gnu, C/scripts/c4.txt, C/scripts/c4_exp.txt, C/scripts/generate_export_list.py, C/tests/cmake/platform_linux.cmake, cmake/platform_apple.cmake, cmake/platform_linux.cmake, cmake/platform_linux_desktop.cmake, cmake/platform_unix.cmake
Via gnu linker file, and add a script to generate the list of symbols to export for each platform
=> CBL-430 Hide non-exported symbols on Linux

C/include/c4Replicator.h, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
Based on testing with iOS platform
=> Pending Document ID API fixes

LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/tests/DataFileTest.cc
=> CBL-550: Only change to user_version 301

Replicator/c4Replicator.cc
Create a stub function returning an error, in a CE build.
In the future we should have separate export lists for CE and EE.
=> Fixed CE link error on c4repl_newLocal

Replicator/c4RemoteReplicator.hh, Replicator/c4Replicator.hh
Fixed some bugs I found while running the Obj-C unit tests.
=> Two C4Replicator bug fixes

Jenkinsfile, jenkins/jenkins_unix.sh
It needs to be usable for generating test TLS certificates
=> Unlock keychain for macOS validation

.travis.yml, Jenkinsfile, LiteCore/Storage/SQLiteChooser.c, Replicator/Replicator.cc, cmake/platform_unix.cmake, jenkins/jenkins_android.sh, jenkins/jenkins_ios.sh, jenkins/jenkins_uwp.ps1
macOS CE, iOS, Android, and UWP
=> Expand PR validation

Replicator/CookieStore.cc, Xcode/xcconfigs/Project.xcconfig
* fix implicit conversion error with floating point to int
* bump version to 2.7.1
=> fix: XCode 11.4 compatible

Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/tests/ReplicatorLoopbackTest.cc
Master port of https://github.com/couchbase/couchbase-lite-core/pull/927
=> CBL-726: Re-push a failed rev if its remote-ancestor changed

LiteCore/Query/QueryParser.cc, LiteCore/tests/QueryParserTest.cc
Allow query expressions like `_id LIKE 'food:%'` to be optimized with an index search, by having the QueryParser generate a LIKE expression instead of a call to our `fl_like` function when feasible.
Fixes CBL-890
=> Enable SQLite LIKE optimization

Crypto/PublicKey+Apple.mm
* SecKeyCopyPublicKey from the private key doesn’t work when the public key is not stored in the KeyChain. Instead getting the public key from the certificate via trust.
* Updated remove key to also remove public key (if available).
* In findInKeychain(), ignore some internal C++ exception thrown inside the security framework which doesn’t seem to harm anything.
* In findInKeychain(), do not Assert the result so that it can be used to check if thing exists in the key chain or not.
=> Fix how to get public key from private key and update remove key logic

Crypto/PublicKey+Apple.mm
The public key may not be in the KeyChain as a separate entity, for example, when using SecPKCS12Import to import the identity from P12 created from openSSL tool on macOS, the public key entity will not be presented in the KeyChain. When that happens, create the SecKeyRef of the public key from the public key data instead.
CBL-947
=> Fix withPublicKey() when the public key is not in the KeyChain

C/include/c4Socket.h
providesWebSockets was removed long time ago, but still mentioned in comments.
=> fix misleading comments in c4Socket.h

Replicator/RevFinder.cc
=> fix memory leak in RevFinder::_findOrRequestRevs

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/SQLitePredictionFunction.cc, LiteCore/tests/CMakeLists.txt, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/cmake/platform_base.cmake
=> Bump Fleece and add test for lack of precision in some math results

Crypto/PublicKey+Apple.mm
I couldn’t figure out the real reason why sometimes but not everytimes, -34018 (errSecMissingEntitlement) error returns when removing the SecKeyRef directly from the KeyChain. After changing to delete with public key hash query, I haven’t seen the issue ever since.
CBL-1024
=> Fix random failure with -34018 error when removing keys

C/tests/CMakeLists.txt, CMakeLists.txt, cmake/platform_base.cmake, cmake/platform_win_store.cmake
Build sqlite3 as a separate module for the possibility of replacement.
close #990
=> build sqlite3 as separate library

C/tests/c4QueryTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, LiteCore/Database/Database.cc, Networking/WebSockets/BuiltInWebSocket.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.hh
* Fleece's SharedKeys
* C4Replicator class
* BuiltinWebSocket, but only in debug builds
* ReplicatorAPITest, C4QueryTest
=> Fixed data races detected by Thread Sanitizer

Networking/WebSockets/WebSocketImpl.cc, Replicator/tests/ReplicatorAPITest.cc
And the C4Socket does not use framing.  Fixes #1009
=> Fix regression when stopped called during connecting phase

Crypto/CertificateTest.cc, Crypto/PublicKey+Windows.cc, LiteCore/tests/CMakeLists.txt, cmake/platform_apple.cmake, cmake/platform_win.cmake
Using mostly the NCrypt API.  Compiles in both desktop and UWP.
=> Windows implementation of persistent private keys

LiteCore/Query/QueryParser.cc, LiteCore/tests/QueryTest.cc
If a property started with a dollar sign it was confusing the path parser, because an opening $ character means "start a new path" and is required to be followed by either a period or bracket.
=> CBL-1107: Fix bad interpretation of '$' properties

C/c4Certificate.cc
delegate a request for raw data to the DER method.
=> Fix External Key Pair callback

C/c4QueryObserver.hh, LiteCore/Database/TreeDocument.cc, LiteCore/Query/SQLiteQuery.cc, Networking/NetworkInterfaces.cc, Networking/TLSContext.hh, Networking/WebSockets/BuiltInWebSocket.hh, REST/Server.hh, REST/tests/RESTListenerTest.cc, Replicator/Checkpointer.cc, Replicator/Checkpointer.hh, Replicator/IncomingRev.hh, Replicator/Puller.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh, Replicator/ReplicatorTuning.hh, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
These are minor changes I made during the big replicator refactoring. I've cherry-picked them into a separate PR, (a) so that they'll be more likely to get in soon, and (b) to check if they were causing the test failures I'm seeing in the big PR … apparently they weren't.
=> Minor fixes culled from pusher-refactor branch

Networking/BLIP/BLIPConnection.cc
Delegate them to the actor's mailbox
=> CBL-1084: Don't allow direct calls to BLIPIO::start

C/c4.def, C/c4.exp, C/c4.gnu, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/scripts/c4.txt
Add c4db_getCookies and c4db_setCookie to the exported symbol list.
=> Add c4db_getCookies and c4db_setCookie symbol

Replicator/RevFinder.cc
Sometimes a 0 would be inserted into the reply to a change message without a comma and result in invalid JSON
=> CBL-1208: Fix an rare improper changes response

Replicator/IncomingRev.cc
The pending rev message count needs to be handled in the case of attachments, which follows a different path than non-attachments
=> CBL-1291: Expanded failed delta recovery handling

C/tests/c4PerfTest.cc
This will allow data export to JSON that can be integrated into the showfast graphical dashboard to detect performance regressions
=> Integrate showfast export into c4PerfTest

Networking/TCPSocket.cc
Related to https://github.com/couchbase/couchbase-lite-core/issues/944
=> Windows sometimes uses EWOULDBLOCK instead of WSAEWOULDBLOCK

Jenkinsfile
This will free up more time on the mac machine it used to run on.
=> CBL-1494: Switch Android PR validation to Linux

C/include/c4Certificate.h
`@param cert  The certificate to store, or NULL to delete any saved cert with that name.`
=> make cert param as nullable

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/N1QLParserTest.cc
Allow second JOIN to consume white spaces. Added test cases that would fail without this fix.
=> Fix query grammar for multi-joins. CBL-1560

C/c4Certificate.cc, C/c4DocEnumerator.cc, C/c4Document.cc, C/c4Query.cc, LiteCore/Query/SQLiteQuery.cc, REST/c4Listener.cc
* Updated Fleece: Some micro-optimizations for moving a Retained, and turning a Retained in a a bare pointer with a reference.
* Tweaked some LiteCore code to eliminate a retain+release where the Retained-to-pointer optimization can be applied.
=> Ref-counting optimizations

LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc
Ensure they take multiple arguments (> 2) and always yield result according to N1QL doc.
=> ifmissing, ifmissingornull, ifnull. #CBL-1556

Networking/WebSockets/BuiltInWebSocket.cc
A zero return value for read or write from a socket can sometimes indicate that the socket has reached EOF, and in that case the polling should not continue.
=> CBL-1663: Fix infinite loop on socket POLLHUP

LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/tests/QueryTest.cc
We already have the function in SqLite. I wired it up with N1QL and added a test case.
=> Complete query function, ARRAY_AGG, #CBL-1622

LiteCore/Support/c4ExceptionUtils.hh
Added include <atomic> for std::atomic_int as required by windows build.
=> Add include <atomic> for std::atomic_int

LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Support/MultiLogDecoder.hh, Replicator/c4Replicator.cc
Make sure that there are no includes to private headers from public ones
=> Clean fleece headers

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/N1QLParserTest.cc
Also fixed a bug in fleece, setInt.
=> N1QL should take interger of 64-bits. #CBL-1657

C/include/c4ReplicatorTypes.h, Replicator/IncomingRev.cc, Replicator/Puller.cc, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc
* Updated the replicator protocol to CBMobile_3.
* Added enable auto-purge configuration.
* Fixed issues found while testing the implementation
=> Update access revocation implementation and fix issues

C/include/c4ReplicatorTypes.h, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.cc, Replicator/Puller.hh, Replicator/ReplicatedRev.hh, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh, Replicator/ReplicatorTypes.cc, Replicator/ReplicatorTypes.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorSGTest.cc, Replicator/tests/data/client_ssl_config.json, Replicator/tests/data/config.json
The code in the feature/revocation branch has been review. I'm creating this PR for merging the code into the dev branch.
=> Merge Revocation Branch into Dev Branch

LiteCore/Query/QueryParser.cc
* escaped the dbname with quoted string
* more info https://issues.couchbase.com/browse/CBL-2036
=> CBL-2036: Fix the dbName with hyphen issue

Replicator/ReplicatorOptions.hh
Fixed a mistake that use kC4ReplicatorOptionDisableDeltas instead of kC4ReplicatorOptionAutoPurge.
=> CBL-2079 : Fix wrong key used in enableAutoPurge()

C/tests/c4DocumentTest.cc
by c4doc_update in certain situations
(Jim's original test, which I forgot to include in my fix PR)
=> Add a test to show how external FLValue get invalidated

Replicator/ChangesFeed.cc, Replicator/tests/ReplicatorLoopbackTest.cc
…problem has already been avoided. I added a comment in the source and a unit test to verify it. #CBL-462
=> Avoid to replicate-push purged document

Xcode/xcconfigs/Project.xcconfig
For the 2.8.5 MP, version bump
=> version bump 2.8.5

REST/RESTListener+Replicate.cc, REST/tests/RESTListenerTest.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh
1) Added capability of Basic auth support.
2) Added 4 test cases, {continuous, one-shot} x {auth, no-auth}.
However, One-shot is not working yet. They will be handled by separate bugs.
=> REST _replicate, CBL-2208

Replicator/RevFinder.cc, Replicator/tests/ReplicatorSGTest.cc
Fix unexpected purging after push/pull tomestones, CBL-2345
As a deleted doc is pushed up, we lose the channel info because the deleted docs have empty bodies. This causes SGW to think all channels are removed from this doc and hence send down the Removal flag when pulled. This commit disregards the Removal flag if it is accompanied by the Deleted flag.
=> Fix unexpected purging after push/pull tomestones, CBL-2345 (#1245)

CMakeLists.txt, Xcode/build_mbedtls.sh
With Couchbase changes based on top of it.
=> CBL-2536: Update mbedTLS to v2.27.0

Xcode/build_mbedtls.sh
* No overriding the MacOSX minim version to 10.15
=> CBL-2574: No overriding allowed

LiteCore/Database/DatabaseImpl.cc
Fix the bug and also prevent possible omission of endTransaction due to stack unwinding.
=> CBL-2446 fix unpaired beginTransaction/endTransaction.

LiteCore/Database/BackgroundDB.cc
As it stands, the call to dataFile()->openAnother will register the datafile as a candidate to receive notifications of transactions committed by other handles but at the point that it does this the object is not fully constructed.  If a notification came in before the construction is finished this causes undefined behavior like hangs and crashing.
=> CBL-2543: Don't open DataFile in BackgroundDB too early

LiteCore/Database/LiveQuerier.cc
Instead, change it back to false if it starts again.  There is no valid scenario for the live query to do anything until that point anyway.  Also tighten up the check of it so that it is entirely based on the value read inside a lock.
=> CBL-2508: Don't change LiveQuery _stopping so early

C/Cpp_include/c4Database.hh, C/c4.def, C/c4.exp, C/c4.gnu, C/c4CAPI.cc, C/c4Database.cc, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Database.h, C/scripts/c4.txt, C/tests/c4DatabaseEncryptionTest.cc, Crypto/SecureSymmetricCrypto.cc, Crypto/SecureSymmetricCrypto.hh
This function will be phased out after the entire gamut of CBL uses SHA256 based PBKDF.
=> CBL-2541 add a new PBKDF based on SHA1.

Crypto/PublicKey+Apple.mm
* replaced iOS 14/macOS 11 deprecated API - SecTrustCopyPublicKey
* corrected the availability check for catalyst
=> [lithium] [helium] Updated  iOS 14 deprecated API

LiteCore/Database/BackgroundDB.cc
* As it stands, the call to dataFile()->openAnother will register the datafile as a candidate to receive notifications of transactions committed by other handles but at the point that it does this the object is not fully constructed.  If a notification came in before the construction is finished this causes undefined behavior like hangs and crashing.
* CBL-2689 is a clone of CBL-2543 to port the fix from Lithium to Master branch. This PR is basically a cherry-pick the fix for CBL-2543.
=> CBL-2689: Don't open DataFile in BackgroundDB too early (#1304)

C/Cpp_include/c4Query.hh, C/c4Query.cc, LiteCore/Database/LiveQuerier.cc, LiteCore/Database/LiveQuerier.hh
CBL-2692 is cloned from Lithium's CBL-2673.
CBL-2693 is cloned from Lithium's CBL-2678.
=> LiveQuery fix for CBL-2692 and CBL-2693

REST/tests/SyncListenerTest.cc
Add logs to learn more about where the test hung.
=> CBL-2696 : Add logs to P2P Server Addresses Test

Replicator/Replicator.cc
Fixing Repicator::isDocumentPending and Replicator::pendingDocumentIDs.
=> CBL-2575: catch db exception properly in Replicator.cc

Replicator/Replicator.cc
Fixing Repicator::isDocumentPending and Replicator::pendingDocumentIDs.
Note: cherry-picked from release/lithium#6265d618c78f3f739ea9801de024bfc8c8216f81
=> CBL-2721: catch db exception properly in Replicator.cc (#1346)

.github/workflows/check_deps.yml, build_cmake/scripts/check_deps.py
* include `-path` arg, so we can reuse it for other projects.
* changes reflected on workflow xml file.
* CBL-2504
=> Update check_deps.py script 

C/tests/c4DatabaseTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/BothKeyStore.cc, LiteCore/Storage/BothKeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryParserTest.hh, LiteCore/tests/QueryTest.cc
Incoporated those test cases into the Core.
=> CBL-2750 : fixing bugs that failed tests in CBLs, cf ticket cbl 2734

jenkins/build_server_android.sh, jenkins/build_server_unix.sh
CBD-4587, create lite-core artifacts to publish to latestbuild.
migrated unix & windows build scripts over from build repo.
-Ming Ho
=> CBD-4587, create lite-core artifacts to publish to latestbuild.

jenkins/build_server_unix.sh
CBD-4587, fixed SYMBOLS_DEBUG_PKG_NAME and SYMBOLS_REL_PKG_NAME.
-Ming Ho
=> CBD-4587, fixed SYMBOLS_DEBUG_PKG_NAME and SYMBOLS_REL_PKG_NAME.

Replicator/Puller.cc
Portions of commit 32c958de got lost in a merge I did right afterward
into the feature/pusher-refactor branch. The original commit was on
master, I merged it into the branch, and then later the branch got
merged back into master. This happened in July 2020.
Most of that commit was fixes to code that I'd reimplemented
on the branch, but there were some useful logging bits that I seem to
have missed and didn't propagate.
This commit restores those logs, except for one bit: Puller can't
log `_waitingChangesMessages.size` because it no longer exists; that
object is now in RevFinder and Puller can't access it.
=> Restored some Puller logs that got lost in a merge

jenkins/build_server_win.ps1
"STORE_$arch" was mis-used.  Should be "$arch" instead.
-Ming Ho
=> CBD-4587, fixed property variable name.

Networking/BLIP/BLIPConnection.cc, Networking/BLIP/Message.cc, Networking/HTTP/CookieStore.cc, Networking/WebSockets/WebSocketImpl.cc
This project will be split into various commits that begin with [LOGGING] in order to keep things small.  This PR starts with the Networking folder and logging more situations regarding BLIP, Cookies, and network.
=> [LOGGING] Enhance logging in the Networking folder

REST/c4Listener.cc
str << NULL << str instead of converting the NULL to a "NULL"
=> fix: crash with appending NULL to the string.

C/c4Document.cc, C/include/c4Compat.h, C/tests/c4Test.hh, LiteCore/Database/DatabaseImpl+Upgrade.cc, LiteCore/RevTrees/VectorRecord.cc, LiteCore/Support/DeDuplicateEncoder.hh, LiteCore/Support/TestsCommon.cc, Networking/BLIP/BLIPConnection.hh, Networking/BLIP/Message.cc, Networking/BLIP/MessageBuilder.cc, Networking/HTTP/CookieStore.cc, Networking/HTTP/Headers.cc, Networking/WebSockets/WebSocketImpl.hh, REST/CertRequest.hh, REST/RESTListener+Handlers.cc, REST/RESTListener+Replicate.cc, Replicator/Checkpoint.cc, Replicator/DBAccess.hh, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/c4ReplicatorImpl.hh, Replicator/tests/ReplicatorAPITest.hh
See https://github.com/couchbaselabs/fleece/pull/146
=> Updated to refactored Fleece headers

C/tests/CMakeLists.txt, C/tests/c4PerfTest.cc, C/tests/cmake/platform_linux.cmake
And make sure that per-platform metrics are output
=> Fix Linux build of perf test with prebuilt LiteCore

C/Cpp_include/c4.hh, C/Cpp_include/c4ConnectedClient.hh, C/c4.def, C/c4.exp, C/c4.gnu, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4.h, C/include/c4Base.h, C/include/c4ConnectedClient.h, C/scripts/c4.txt, C/scripts/c4_ee.txt, CMakeLists.txt, Replicator/ConnectedClient/ConnectedClient.cc, Replicator/ConnectedClient/ConnectedClient.hh, Replicator/c4ConnectedClient.cc, Replicator/c4ConnectedClientImpl.cc, Replicator/c4ConnectedClientImpl.hh, Replicator/c4ConnectedClient_CAPI.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, cmake/platform_base.cmake
* Connected client APIs for create a new connected client and get document
=> Connected client LiteCore APIs

C/c4Query.cc
* When enableObserver() is called twice to disable, there is a race b/w resetting _bgQuery in C4Query::liveQuerierStopped() called by an actor thread and calling _bgQuerier.stop() in C4Query::enableObserver(). As a result, _bgQuerier.stop() would could cause a crash as _bgQuerier could be null.
* Added a mutex lock in liveQuerierStopped() to prevent the race.
=> CBL-2942 : Fix crash when disable query observer twice

jenkins/build_server_unix.sh
CBD-4715, add header files to mac package.
-Ming.
=> CBD-4715, add header files to mac package.

LiteCore/Query/QueryParser.cc, LiteCore/Query/SQLiteKeyStore+PredictiveIndexes.cc, LiteCore/tests/N1QLParserTest.cc
- Add some n1ql tests for scopes and collections.
=> - Fixed 2 bugs to pass unit tests.

Replicator/Replicator.cc
Another place where NotOpen exception must be caught.
=> CBL-3072 : isDocumentPending crashes

Networking/BLIP/LoopbackProvider.hh
LoopbackWebSocket implements messsaging within the same application by threaded queues. For Mac, in particular, we use GCD's dispatch_after in order to simulate network latency. Since dispatch_after takes absolute time in the future, as opposed to a delta delay, the order may be displaced if two future times are numerically equal. To guarantee the ordering, we take advantage of the ordering guarantee of dispatch_async with the serial queue: we queue the messages with dispatch_async, and actually send the message with dispatch_after. We do two dispatches only if the latency is greater than 0.
cherry-picked from 1ca7012a81d6799ac7501b3b0486f26f92da538e
=> CBL-3090 : ensure message order for LoopbackWebSocket.

C/Cpp_include/c4Collection.hh, C/c4.exp, C/c4CAPI.cc, C/c4Collection.cc, C/c4_ee.exp, C/include/c4Base.h, C/include/c4Collection.h, C/scripts/c4.txt, C/tests/c4CollectionTest.cc, LiteCore/Database/CollectionImpl.hh, LiteCore/Database/DatabaseImpl.cc, LiteCore/Database/DatabaseImpl.hh, Xcode/LiteCore.xcodeproj/project.pbxproj
See docs at top of C4Collection.h.
=> Make C4Collection ref-counted [API]

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/tests/QueryTest.cc
=> Proper fleece encoding for uint64 query result

C/include/c4Collection.h, C/tests/c4CollectionTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/CMakeLists.txt, LiteCore/tests/QueryTest.cc
:heavy_exclamation_mark: For JSON syntax, this requires escaping dots for aliases
=> CBL-3048: Allow dots in alias names

LiteCore/Database/DatabaseImpl.cc
If you call db->deleteCollection(coll->spec()), the memory of the
CollectionSpec passed in belongs to the collection being deleted.
Unfortunately the method accesses it after deleting the collection.
Fixed by only accessing it before deletion.
=> Fixed a crash in C4Database::deleteCollection

LiteCore/Storage/SQLiteDataFile.cc
Note to function with EE, the EE commit must be at least 44e79198
=> CBL-3218: Enable F_BARRIERFSYNC on macOS / iOS

C/include/c4DatabaseTypes.h, Replicator/ReplicatorOptions.hh
Convert C4ReplicatorParameters to repl::Options.
=> CBL-3220 : ReplicatorOptions to include collection

C/Cpp_include/c4Replicator.hh, C/include/c4Replicator.h, Replicator/c4Replicator.cc, Replicator/c4ReplicatorImpl.hh, Replicator/c4Replicator_CAPI.cc, Replicator/tests/ReplicatorAPITest.cc
=> CBL-3349 : getPendingDocIDs and isDocumentPending to have collection

C/tests/c4Test.cc, C/tests/c4Test.hh, Replicator/tests/ReplicatorCollectionTest.cc
* Added reset checkpoint test and attachment test.
* Updated Sync with Default Collection Test and with Single Collection Test to cover multiple passive collections.
* More tests to come.
=> Add reset checkpoint and attachment tests

Replicator/tests/ReplicatorCollectionTest.cc
* Added a resolve conflict test in ReplicatorCollectionTest.
* Added setConflictResolver() to allow to set a conflict resolver function which is similar to ConflictResolver function in CBL.
=> Add a resolve conflict test in ReplicatorCollectionTest

Networking/BLIP/LoopbackProvider.hh, Replicator/IncomingRev+Blobs.cc, Replicator/IncomingRev.cc, Replicator/Puller.cc, Replicator/Pusher+Attachments.cc, Replicator/Pusher+Revs.cc, Replicator/Replicator.cc, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
CBL-3484 : Do not check collection property in the reply messages.
=> CBL-3467 : Replicator handles errors related to collections.

Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
* Moved UnbreakableEncryption() to the header file.
* Added property encryption test with collections to ReplicatorCollectionTest.
* Related PR in EE : https://github.com/couchbase/couchbase-lite-core-EE/pull/26
=> CBL-3486 : Add property encryption test with collections

C/tests/c4QueryTest.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/tests/DataFileTest.cc
Queries didn't mangle the collection name which led to upper case giving a collection not found error
=> CBL-3514: Fix bug in collection case sensitivity

README.md
Remove outdated references and text, and add modern techniques
=> CBL-3556: Update the README

LiteCore/RevTrees/RevTree.cc
Try to fix the loss of the prune after copy of treedocument explained in this issue https://github.com/couchbase/couchbase-lite-C/issues/339
=> Fixing the loss of the prune

Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
Added tests for push filters, pull filters, docIDs, docIDs with filters.
=> CBL-3503 : Add tests for using filters with multi collection

LiteCore/RevTrees/RevTree.cc
Port the fix from the master branch.
=> CBL-3671 : Fixing the loss of the prune (#1552)

build_cmake/scripts/check_bd_versions.py, cmake/platform_linux_desktop.cmake, jenkins/CBDeps.cmake, jenkins/CMakeLists.txt, jenkins/ParseArguments.cmake, jenkins/couchbase-lite-core-black-duck-manifest.yaml, jenkins/manifest.cmake
Switch away from depending on tlm for cbdeps management; use latest version of 'cbdep' tool to install required package(s).
=> CBD-5140: Update to ICU 71.1

C/tests/c4BlobStoreTest.cc
Fleece also needed sprintf changing to snprintf, forgot to bump it to that commit in the last PR for this issue. Thanks @borrrden for help with that.
=> CBL-3699: Update fleece to include snprintf changes

C/tests/c4AllDocsPerformanceTest.cc, C/tests/c4BlobStoreTest.cc, C/tests/c4CollectionTest.cc, C/tests/c4DatabaseTest.cc, C/tests/c4PerfTest.cc, C/tests/c4Test.cc, C/tests/c4ThreadingTest.cc, LiteCore/Database/DatabaseImpl.cc, LiteCore/Support/FilePath.cc, LiteCore/Support/LogDecoder.cc, LiteCore/Support/TestsCommon.cc, LiteCore/Support/ThreadedMailbox.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/LogEncoderTest.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/UpgraderTest.cc, LiteCore/tests/c4BaseTest.cc, Networking/BLIP/MessageBuilder.cc, REST/Request.cc, Replicator/Checkpointer.cc, Replicator/RemoteSequence.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh, Replicator/tests/ReplicatorSGTest.cc
Cherry-picked snprintf changes from CBL-3669 onto lithium branch. 
Also did the same for fleece, and updated fleece commit in this branch.
=> CBL-3712: Backport snprintf changes to Lithium.

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/N1QLParserTest.cc
Add array literal to the definition of the in expression in `n1ql.leg`
Regenerate `n1ql.cc` from updated `n1ql.leg`
Add test for array literal with IN expression
=> CBL-2876: Add array literal support for IN expressions

Replicator/ReplicatorOptions.hh
- Moved all mutables under `Mutables` struct
- Updated use/calls to reflect the struct change
=> CBL-3448: Manage mutable members of repl::Options

Replicator/tests/ReplicatorCollectionSGTest.cc, Replicator/tests/data/sg_setup.sh
Create shell script for easy SG setup.
=> CBL-3806: Easier setup of CollectionSGTest

Replicator/tests/ReplicatorCollectionSGTest.cc
- Test ported from ReplicatorSGTest to ReplicatorCollectionSGTest
- Validation added in order to check the 5000 revs - used .hasPrefix()
- File lint
=> CBL-3784: Collection SG test, "API Push 5000 Changes"

Replicator/tests/ReplicatorCollectionSGTest.cc
Ported test, passing consistently.
=> CBL-3786: Collection SG test, "Update Once-Conflicted Doc"

Replicator/tests/ReplicatorCollectionSGTest.cc
- Test ported from ReplicatorSGTest to ReplicatorCollectionSGTest
=> CBL-3790: Collection SG test, "Push & Pull Deletion"

LiteCore/Database/TreeDocument.cc, LiteCore/tests/c4DocumentTest_Internal.cc
PORT revID security vulnerability and random revID test
=> CBL-2937: Field Level Encryption and RevID Security Vulnerability (Port)

Replicator/tests/ReplicatorCollectionSGTest.cc
Test is passing with new timeout parameter in SG functions. Have given it a generous timeout as there are ~16k docs.
Have given it a separate tag from the rest of CollectionSG Tests because it takes ~3 mins to run the test.
=> CBL-3789: Collection SG test, "Pull iTunes deltas from SG"

C/c4.exp, C/c4CAPI.cc, C/c4_ee.exp, C/include/c4Collection.h, C/scripts/c4.txt, C/tests/c4CollectionTest.cc, C/tests/c4DatabaseTest.cc, C/tests/c4ObserverTest.cc, LiteCore/Database/DatabaseImpl.cc, LiteCore/Support/Error.cc
Also fixed annoying printout that tests generate as successful result.
=> CBL-3979: Not allow to delete default collection

Replicator/tests/ReplicatorCollectionSGTest.cc, Replicator/tests/ReplicatorSGTest.cc, Replicator/tests/SG.cc, Replicator/tests/SG.hh, Replicator/tests/SGTestUser.cc, Replicator/tests/SGTestUser.hh, Replicator/tests/data/sg_setup.sh
Tested with SGW 3.1.0-438, all tests are passing.
=> CBL-4023: Make SyncServerCollection tests compatible with SGW 3.1.0

C/tests/c4QueryTest.cc, C/tests/c4QueryTest.hh, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryParserTest.cc
* Extended SQL++ to be able specify the collection when referring to the FTS index in MATCH() function.
* Extended QueryParser to handle multiple collections.
* Fixed prediction with non-default collections.
=> CBL-3994: Query with FTS with multiple collections.

Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorCollectionSGTest.cc
* The test is failing owing to CBG-2487
=> CBL-3776: Collection SG test, "Auto Purge Disabled - Revoke Access"

Replicator/tests/ReplicatorCollectionSGTest.cc
Looks like I've accidentally included a commit from my branch for CBL-4070, as I was running all of the tests when investigating this bug and needed that one to pass.
=> CBL-4071: "Push & Pull Deletion SG" Add channel filter

Replicator/tests/ReplicatorCollectionSGTest.cc
I also had to change numDocs to 799 because it was failing on 800 for me (due to the CBG issue in the comment above that line).
=> CBL-4081: "Pull deltas from Collection SG" re-disable deltas

Networking/WebSockets/WebSocketImpl.cc, REST/tests/SyncListenerTest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorCollectionSGTest.cc
This problem is revealed by a DebugAssert.
=> CBL-4051: Fix a deadlock in ReplicatorAPITest

Replicator/tests/ReplicatorCollectionSGTest.cc, Replicator/tests/ReplicatorCollectionSGTest.hh, Replicator/tests/data/config-no-tls.json, Replicator/tests/data/sg_setup.sh
Modify `sg_setup.sh` to allow disabling TLS.
Add environment variable "NOTLS" to disable TLS in CollectionSGTest.
=> CBL-4093: CollectionSGTest option to disable TLS

Xcode/xcconfigs/LiteCore-framework.xcconfig, jenkins/build_server_ios.sh
This will affect .NET (need to change the name of the file to use) but has already been communicated.
=> Migrate to xcframework from framework for LiteCore iOS / Mac Catalyst

cmake/platform_linux_desktop.cmake, jenkins/CBDeps.cmake, jenkins/CMakeLists.txt, jenkins/ParseArguments.cmake
⚠️ libicu inside of the Linux packages have changed versions.  Scripts that are looking for `libicu*.so.54.1` will need to change to look for `libicu*.so.71.1`
=> CBD-5140 CBL-3643: Update to ICU 71.1

jenkins/CMakeLists.txt
Maybe someday in the future we can upgrade the Android build system to be inline with master, but for now this needs to work ASAP.
=> Go ultra hack mode and leave a comment about desktop Linux

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryParserTest.cc
The JSON format already has LOCALE property. This PR extends the SQL++ grammar to include it.
=> CBL-4131: SQL++ to allow UNICODE with LOCALE parameter.

Crypto/PublicKey+Apple.mm
* Ported the fix from release/3.1 branch (91f5b72a4cde239b3f759b39748f355b62b7278b), which is the fix for CBL-4237.
* Instead of creating the SecTrust with just a leaf cert, create it with the cert chain received from the server.
* Updated `sockpp` submodule to get the fix that passes the cert chains instead of just the leaf cert.
=> CBL-4238 : Create SecTrust with certificate chain

C/Cpp_include/c4Database.hh, C/c4.exp, C/c4Database.cc, C/c4_ee.exp, C/scripts/c4.txt, C/tests/c4DatabaseTest.cc
A compilant database name can be described by regex, "^[A-z0-9][-A-z0-9_]*".
=> CBL-4280: Warn on attempt to create a database with non-compilant name.

Replicator/Worker.cc, Replicator/Worker.hh, Replicator/tests/ReplicatorLoopbackTest.hh
Helium port of CBL-4368.
Make formatWithCollection thread-safe.
Change _formatCache to unordered_set.
Add timeout to ReplicatorLoopbackTest.
=> CBL-4376: (Helium port) formatWithCollection thread safety

.github/workflows/clang-format-check.yml, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, LiteCore/tests/main.cpp, MSVC/SQLiteTempDirectory.cc, MSVC/asprintf.c, MSVC/asprintf.h, MSVC/dirent.h, MSVC/mkdtemp.cc, MSVC/mkdtemp.h, MSVC/mkstemp.cc, MSVC/mkstemp.h, MSVC/strlcat.c, MSVC/strlcat.h, MSVC/vasprintf-msvc.c, Networking/WebSockets/BuiltInWebSocket.cc, REST/RESTListener.cc, Replicator/DBAccess.cc, Replicator/Pusher+Revs.cc, Replicator/ReplicatedRev.hh, Replicator/tests/ReplicatorCollectionSGTest.cc, build_cmake/scripts/run-clang-format.sh
Re-open of PR because Jenkins MacOS build & test was consistently failing a certificates test.
=> CBL-4330: Add Clang-Format to GH Actions

REST/RESTListener+Replicate.cc, REST/tests/RESTListenerTest.cc
This fixes PR validation. There is another PR up (CBL-4399) to add commits to Blame Ignore file. Once this PR is merged, the commit hash will be added to the file in that PR.
=> CBL-4400: Final formatting changes so Actions Linter can pass

.github/workflows/clang-format-check.yml, C/tests/c4DatabaseEncryptionTest.cc, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/tests/DataFileTest.cc, Networking/NetworkInterfaces.cc, Networking/Poller.cc, Replicator/tests/PropertyEncryptionTests.cc, Replicator/tests/ReplicatorSGTest.cc, build_cmake/scripts/run-clang-format.sh
And some formatting changes between clang-format v15 and v16.
=> CBL-4430: Update clang-format-check to clang-format-16

Replicator/DBAccess.cc
Port from Helium to Beryllium.
=> CBL-4334: Data getting corrupted during collection replication (Port)

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryParserTest.cc
The JSON format already has LOCALE property. This PR extends the SQL++ grammar to include it.
=> CBL-4167: SQL++ to allow UNICODE with LOCALE parameter.

.gitignore, LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RawRevTree.hh, LiteCore/RevTrees/RevID.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/RevTrees/RevTreeRecord.hh, LiteCore/RevTrees/VectorRecord.cc, LiteCore/RevTrees/VectorRecord.hh, LiteCore/RevTrees/Version.cc, LiteCore/RevTrees/Version.hh, LiteCore/RevTrees/VersionVector.cc, LiteCore/RevTrees/VersionVector.hh
No notable changes in this one.
Also a small addition to gitignore for CLion config files (I didn't feel like this justified a ticket).
=> CBL-4227: Analysis Warnings (7/13) LiteCore/RevTrees

Replicator/tests/data/docker/docker-compose.yml, Replicator/tests/data/docker/sg/Dockerfile
Haven't actually tested this on an x86 machine, but it seems to work well for arm64 so I'm pretty confident. Perhaps @jianminzhao you can test it if you still have an Intel Mac? Otherwise I'll go through the long-winded process of getting Docker installed and set up on my Windows machine.
=> CBL-4545: Docker - Auto-detect SG arch to download

LiteCore/tests/DataFileTest.cc, LiteCore/tests/DocumentKeysTest.cc, LiteCore/tests/FTSTest.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/LiteCoreTest.hh, LiteCore/tests/LogEncoderTest.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/PredictiveQueryTest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryParserTest.hh, LiteCore/tests/QueryTest.cc, LiteCore/tests/QueryTest.hh, LiteCore/tests/SQLiteFunctionsTest.cc, LiteCore/tests/SequenceTrackerTest.cc, LiteCore/tests/UpgraderTest.cc, LiteCore/tests/VersionVectorTest.cc, LiteCore/tests/c4BaseTest.cc, LiteCore/tests/c4DocumentTest_Internal.cc
=> CBL-4228: Analysis warnings (8/13) LiteCore/tests

LiteCore/Support/Instrumentation.cc, Xcode/xcconfigs/C4Tests.xcconfig, Xcode/xcconfigs/Project.xcconfig
- leftover of https://github.com/couchbase/couchbase-lite-core/pull/1807
- indent fix
=> C4Tests min target MacOS 10.14

Xcode/xcconfigs/C4Tests.xcconfig, Xcode/xcconfigs/Project.xcconfig
CBL-4631: Update iOS target version to 11.0
And updated Fleece's target versions
=> CBL-4625: Set macOS target version to 10.14

Replicator/tests/ReplicatorCollectionTest.cc
Protect againt spurious wake-up of condition variable. Also log the fact of time-out.
=> CBL-4554: flaky test, "Multiple Collections Incremental Revisions"

REST/CertRequest.cc, REST/CertRequest.hh, REST/Listener.cc, REST/Listener.hh, REST/RESTListener+Handlers.cc, REST/RESTListener+Replicate.cc, REST/RESTListener.cc, REST/RESTListener.hh, REST/REST_CAPI.cc, REST/Request.cc, REST/Request.hh, REST/Response.cc, REST/Response.hh, REST/Server.cc, REST/Server.hh, REST/c4Listener.cc, REST/c4ListenerInternal.hh, REST/netUtils.cc, REST/netUtils.hh, REST/tests/CertHelper.hh, REST/tests/ListenerHarness.hh, REST/tests/RESTClientTest.cc, REST/tests/RESTListenerTest.cc
=> CBL-4233: Analysis Warnings (13/13) REST + REST/tests

LiteCore/RevTrees/HybridClock.cc, LiteCore/tests/VersionVectorTest.cc
At Jim's suggestion, replace the platform-specific code with `std::system_clock`. I also added some tests to verify the clock has high enough resolution, since it can vary by platform.
=> Use C++ std::system_clock for RealClockSource

LiteCore/tests/LogEncoderTest.cc
For some machines, log rotation may generate more files. We now handle any number of files.
=> CBL-4766: Test case, "Logging rollover" may fail

.gitignore, C/tests/c4DatabaseTest.cc, C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Storage/BothKeyStore.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/QueryParserTest.cc
Also update .gitignore.
Used cherry-pick to port. Had a fair few conflicts due to formatting changes.
Ran CppTests, all passing. Hopefully CI validation is as agreeable.
=> CBL-4801: Port CBL-4377 to Beryllium

C/tests/c4DatabaseTest.cc
From a longstanding TODO comment. Was actually pretty fun figuring out how to add blobs to documents, and now I probably understand it a bit better.
=> CBL-4708: C4DatabaseTest "Database Create Upgrade Fixture" - Add blob creation

C/include/c4DocumentTypes.h, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/Inserter.hh
Ported from release/3.1, #a4b49f509b9f
=> CBL-4839: Attachments/Blobs got deleted after compaction&re-sync

Xcode/build_setup.sh, jenkins/build_server_ios.sh, jenkins/jenkins_ios.sh
Portd from release/3.1 #bc52ab02
=> CBL-4495: Remove bitcode from iOS builds

jenkins/couchbase-lite-core-black-duck-manifest.yaml
Note that this is relative not to this repo, but to the file inside of the build server tarball.
=> Fix faiss path for blackduck

.gitignore, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Inserter.cc, Replicator/Puller.cc, Replicator/Puller.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/tests/ReplicatorCollectionSGTest.cc
Backport (cherry-pick) from CBL-5033 (114b4fd)
=> CBL-5127: Puller revoked docs should queue with other revs

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/Query/SQLiteFleeceUtil.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/Query/SQLitePredictionFunction.cc, LiteCore/tests/SQLiteFunctionsTest.cc
Add test for array_agg failure.
Make sure scopes are constructed and stay alive for Query Fleece values.
Many thanks to @snej who found the exact issue and gave me the fix.
=> CBL-5335: array_agg seem to fail under some circumstances

build_cmake/scripts/check_bd_versions.py, jenkins/couchbase-lite-core-black-duck-manifest.yaml
Cherry picked from ae4d928.
@jianminzhao I assume the change to the `check_bd_versions.py` is necessary?
=> CBL-5410: Upgrade to SQLite 3.43.0

.gitignore, Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/tests/ReplicatorCollectionSGTest.cc
`hasBlobReferences` is copied in from master.
You can show the fix works locally, if you comment out the 3 lines added in `IncomingRev.cc`, the test fails
=> CBL-5448: Attachments flag dropped when applying delta to incoming rev

Replicator/IncomingRev.cc, Replicator/tests/ReplicatorCollectionSGTest.cc
Port from release/3.1, CBL-5448.
With the addition of @pasin's optimisation; `else if ( didApplyDelta )`
=> CBL-5449: Attachments flag is dropped when applying delta to incoming rev

LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser+VectorSearch.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteKeyStore+VectorIndex.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/VectorQueryTest.cc, LiteCore/tests/VectorQueryTest.hh
See the individual commits.
This also fixes dups CBL-5465, CBL-5460
=> Several vector search fixes (CBL-5444, CBL-5476, CBL-5466)

C/c4CAPI.cc, C/c4Query.cc, C/c4QueryImpl.hh, LiteCore/Query/Query.hh, LiteCore/Query/SQLiteQuery.cc, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh
- Add logs to the critical path to c4query_run
- Add instruments to detect when column values are freed as column is encoded into JSON.
=> Add debug intruments for CBSE-16470

.github/workflows/clang-format-check.yml, LiteCore/Query/QueryParser+VectorSearch.cc, LiteCore/tests/QueryTest.cc
Bump Fleece for tz formatting fix.
Fix tests.
=> CBL-5488: DateTime Timezone offset inconsistent

LiteCore/Support/LogDecoder.cc, LiteCore/Support/Logging.cc, LiteCore/tests/LogEncoderTest.cc
Additionally ensure the output of text logs and binary logs match and adjust unit tests.
=> CBL-5591: Binary Decoder to account for the new Logging object path

LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc
Add test for ROUND_EVEN edge case.
=> CBL-5586: Beryllium Port - Fix ROUND_EVEN

LiteCore/Query/DateFormat.cc
I removed the variable which was causing the maybe-uninitialized warning.
=> CBL-5625: Jenkins build failure (centos7)

Replicator/Checkpointer.cc, Replicator/tests/ReplicatorCollectionSGTest.cc
=> CBL-5723: Replicator syncs from beginning when using prebuilt dbs syned from SG

Replicator/IncomingRev.cc
This reverts commit f3071f6055be04191789417a23173db70bbdfeef.
It fails consistently in Jenkins. Revert it to unblock Jenkins.
=> Revert "CBL-5634 (Fix): ReplacementRev puller enhancement (#2022)"

LiteCore/Query/LazyIndex.cc, LiteCore/Query/LazyIndex.hh, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Query/SQLiteKeyStore+VectorIndex.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/LazyVectorQueryTest.cc, LiteCore/tests/VectorQueryTest.cc
=> CBL-5814: (Beryllium) IndexUpdater allows setting index with invalid dimensions

LiteCore/tests/CMakeLists.txt, LiteCore/tests/LazyVectorAPITest.cc, LiteCore/tests/LazyVectorQueryTest.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/LiteCoreTest.hh, LiteCore/tests/QueryTest.hh
This includes all of the tests mentioned in the API spec. I've annotated each test with the number in the spec it relates to.
=> CBL-5754: Lazy Vector Index testing

C/Cpp_include/c4Database.hh, C/c4.exp, C/c4CAPI.cc, C/c4Database.cc, C/c4_ee.exp, C/include/c4Database.h, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Support/Extension.cc, LiteCore/tests/LazyVectorAPITest.cc, LiteCore/tests/VectorQueryTest.cc, LiteCore/tests/VectorQueryTest.hh
Does a sanity check on the extension as well so that it can fail fast
=> CBL-5860: New API for enabling extensions

C/include/c4Index.h
Port of #2070 (cherry picked 280d305)
=> CBL-5870: Added explanatory note to c4index_beginUpdate doc-comment

REST/tests/RESTListenerTest.cc
Allow several timeouts to the HTTP Request. For now, allowing 4 timeouts with each timeout being 5 seconds.
=> CBL-6100: Flaky test "REST root level"

LiteCore/Query/DateFormat.cc
- Use `std::nullopt` instead of `{}`. This alone fixed the errors.
- Simplified declarations by using the type instead of `auto`.
=> Fix DateFormat.cc some more (for GCC)

README.md
Because it took me wayyyyy too long to figure out how to build LiteCore on Linux yesterday.
=> README: Improved Linux build instructions

C/tests/c4QueryTest.cc, LiteCore/tests/QueryTest.cc
Added following tests:
- Deeply nested arrays: 10 levels deep with and without index.
- Triggers of unnest tables (for array indexes)
* insertion triggers
* deletion triggers
* update triggers
- Edge case, missing property at the unnestPath.
=> CBL-6320: Test multi level array index - Low Level

C/tests/c4QueryTest.cc, LiteCore/Query/SQLiteKeyStore+ArrayIndexes.cc
Delete the current index with the same name if it does not have the same IndexSpec.
=> CBL-6369: Recreate Array Index fails

C/tests/c4ArrayIndexTest.cc
The problem is only found when running the test in linux platform of the release Jenkins.
Also fixed two checks when we should recompile the query before the checks.
=> CBL-6375: fix a bug in validateQuery in c4ArrayIndexTest.cc.

LiteCore/Query/Translator/SelectNodes.cc, LiteCore/Query/Translator/TranslatorUtils.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/tests/N1QLParserTest.cc
Recognize collection name as an alias if not ambiguous.
=> CBL-6243: JOIN requires AS

Replicator/Pusher+Revs.cc
For the rev property of the rev message, We use the revID of the current version for Version Vector revisions and the rest of of the versions will be in the history property.
=> CBL-6636: Rev message contains the full history in the revID field

C/include/c4IndexTypes.h, C/tests/c4QueryTest.cc, LiteCore/Database/CollectionImpl.hh
Added field "where" to C4IndexOptions and implemented it.
=> CBL-6576: Implement Partial Index LiteCore API

tool_support/CMakeLists.txt
Link interface with FleeceStatic so that targets that use tool_support automatically consume FleeceStatic
=> Change tool_support linking

C/tests/c4QueryTest.cc, LiteCore/Query/IndexSpec.cc
Fix was really as simple as removing those parentheses :)
=> CBL-6883: Error when creating a partial value index with compound expressions

C/Cpp_include/c4Replicator.hh, Replicator/c4Replicator.cc
This is required by the EE PR, https://github.com/couchbase/couchbase-lite-core-EE/pull/50
=> Added C4Replicator::Parameters::removeCollection()

C/c4Log.cc
Refactor c4log_writeToCallback and c4log_setCallbackLevel so that they function independently of each other. In particular, calling setCallbackLevel with LevelNone won't remove the default logCallback. The new behavior matches with that of the pair of writeToBinary and setBinaryFileLevel.
=> CBL-7125: c4Log sometimes does not log anything

Crypto/PublicKey+Apple.mm
* The original issue where querying the number of children certificates (via the issuer's subject key) always returned zero occurred only on the iOS Simulator (not on macOS or an iPhone device). However, the problem disappeared after I reset the simulator data. The root cause remains unclear to me. While investigating, I have cleaned up and improved the deletion logic:
* Extracted the logic for retrieving the certificate chain from SecTrust, and for fetching attributes from a certificate obtained via SecTrust, into separate helper methods. In addition, skipped the trust validation process when getting the certificate chain from the SecTrust, as it's unnecessary.
* Improved the self-signed certificate check: instead of comparing entire certificates, it now compares the subject and issuer …
=> CBL-7167 : Improve iOS cert chain deletion logic

C/tests/c4DocumentTest.cc, LiteCore/Database/VectorDocument.cc
When a VV document adds an existing [pulled] revision, it now checks if it's a redundant merge: if it has the same body and the same merge parents (MV) as the current revision, even if the revID (CV) is different.
In this situation it doesn't update the current local revision, though it updates the remote's current rev as usual.
The example from the unit test I added:
- Doc's current VV is `8@*, 7@AliceAliceAliceAliceAA, 6@BobBobBobBobBobBobBobA; 4@CarolCarolCarolCarolCA` with body `{'ok':'go'}`.
- Pull revision `9@ZegpoldZegpoldZegpoldA, 7@AliceAliceAliceAliceAA, 6@BobBobBobBobBobBobBobA; 4@CarolCarolCarolCarolCA`, also with body `{'ok':'go'}`
- This is not treated as a conflict. Instead the current version is unaltered, though the remote's current version is updated.
=> Detect redundant merges when pulling revs [CBL-7457]
