couchbase/couchbase-lite-core

C/c4Key.cc, C/c4ViewQuery.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/VersionVectors/VersionVector.cc, LiteCore/VersionVectors/VersionVector.hh, LiteCore/tests/IndexTest.cc
It’s more efficient (saves copying) and also seems to avoid a weird crashing bug in the Genymotion emulator.
Fixes #29
=> Use Vector::emplace_back instead of push_back when possible

LiteCore/Support/Logging.cc
- Incorrectly handle domain value for Android case. This caused the crash in the exception.
=> Fixed #115 - Crash in litecore::error::_throw()

Java/jni/native_fleece.cc, Java/src/com/couchbase/litecore/fleece/FLEncoder.java, Java/src/com/couchbase/litecore/fleece/FLValue.java
- Casting long value to int causes data loss. LiteCore Integer value can handle 2^64, return value for integer should be long for Java
=> Fixed Android Issue 1158: getLong()/setLong() does not work as expected

Java/jni/native_c4document.cc, Java/src/com/couchbase/litecore/C4Document.java
Make JNI selectBody returns FLDict instead of FLValue to avoid another JNI call.
=> Make JNI selectBody returns FLDict instead of FLValue

C/c4Query.cc
Called sliceResult() method to create a retained C4SliceResult. Without doing this, I couldn't get the correct result when converting it to array.
=> Fix c4db_getIndexes’s result is not being retained

LiteCore/Storage/SQLiteKeyStore.cc
Reset getExistingSQL statement after using it.
#227
=> Fix database table locked when replacing an existing index

C/c4Query.cc, LiteCore/tests/QueryTest.cc
Fixes #236 
Normally I would just commit this but I wasn't sure if doing this step unconditionally would cause any problems.  The result columns are only populated currently if the result is ruled to be non-FTS.  That means that every select result in couchbase lite is null instead of what it should be.
=> Fixes #236 (Select results not getting populated in full text queries)

Java/CMakeLists.txt
- Issue [2.0: LiteCore build fails with NDK r15 or higher](https://github.com/couchbase/couchbase-lite-android/issues/1386)
=> Fixed  build issue with latest NDK.

build_cmake/scripts/get_repo_version.sh
When getting GIT_COMMIT, ignore (result to an empty value) if the command fails.
#286
=> Fix get_repo_version.sh fails when project is not in a git repo

CMakeLists.txt, README.md
I'm going to be a killjoy again with building on Linux: building on a relatively fresh Ubuntu 17.10 would fail because some `libc++` headers would search for `<xlocale.h>` which doesn't get found. This fixes, but I'm not 100% sure it's the cleanest plausible solution.
I also added `libicu` into the list of library dependencies as I noticed following failing with the provided build instructions on this fresh new system with relatively few common development dependencies included that it was missing at least on Ubuntu.
=> Fix to Ubuntu 17.10 xlocale.h associated build failure

MSVC/strptime.cc, MSVC/strptime.h, Replicator/CookieStore.cc, Replicator/tests/ReplicatorAPITest.hh
- Compilation error on windows using a class as a conditional
- Failure on multiple platforms with Cookie expiry parsing
Fixes #284 (cookiestore tests are failing on Linux because of incorrect 'expires')
Fixes #285 (ReplicatorAPITest build error on Windows)
=> Fixes for compilation and test errors

.gitmodules, LiteCore/tests/TokenizerTest.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, Xcode/xcconfigs/LiteCoreServ.xcconfig, tools/ArgumentTokenizer.cc, tools/ArgumentTokenizer.hh, tools/CMakeLists.txt, tools/Tool.cc, tools/Tool.hh, tools/cblite/cbliteTool+cat.cc, tools/cblite/cbliteTool+ls.cc, tools/cblite/cbliteTool.hh
Almost entirely changes needed for running in interactive mode only.  Summary:
Replaced libedit with linenoise (fork with Windows support and UTF-8 input support)
Added a few headers and defines to make some previously undefined functions available (isatty, fnmatch)
=> Cross platform implementation of ‘cblite’ tool

Java/src/com/couchbase/litecore/fleece/FLDict.java
Fixed Null Pointer Exception in case return value from FLDictIterator.getKey() is null.
=> Fixed Null Pointer Exception

Java/src/com/couchbase/litecore/C4Replicator.java, Java/src/com/couchbase/litecore/C4Socket.java
The remaining logging should go through C4Log, not android.util.Log,
but I don't know how to do that from Java.
Fixes #343
=> Java: Removed overly verbose C4Socket and C4Replicator logging

C/c4.def, C/c4.exp, C/c4Observer.cc, C/include/c4Observer.h, C/tests/c4ObserverTest.cc, C/tests/c4ThreadingTest.cc, CSharp/src/LiteCore.Shared/Interop/C4Observer_native.cs, CSharp/test/LiteCore.Tests.Shared/ObserverTest.cs, CSharp/test/LiteCore.Tests.Shared/ThreadingTest.cs, LiteCore/Database/SequenceTracker.cc, LiteCore/Database/SequenceTracker.hh, Replicator/DBWorker.cc
You MUST now call the new function c4dbobs_releaseChanges() after
you're done with the info you got from c4dbobs_getChanges(), otherwise
memory will be leaked.
Fixes #418 (again)
=> Fixed memory-management bug with c4dbobs_getChanges(); API CHANGE!!

Replicator/IncomingBlob.cc, Replicator/IncomingBlob.hh, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Pusher.cc, Replicator/tests/ReplicatorLoopbackTest.cc
* Changed IncomingRev to pull only one blob at a time.
* Changed IncomingBlob to delay opening the write stream until it
receives the first bytes from the response.
Fixes #420
=> Reduce number of file descriptors opened while pulling blobs

build_cmake/scripts/build_macos.sh
Before this change, I was getting the following error running the `build_macos.sh` script:
./build_macos.sh: line 11: [-d: command not found
After the change the problem went away.
=> Fix error:  [-d: command not found

Java/jni/native_fleece.cc, Java/src/com/couchbase/litecore/C4Document.java, Java/src/com/couchbase/litecore/SharedKeys.java, Java/src/com/couchbase/litecore/fleece/FLDict.java, Java/src/com/couchbase/litecore/fleece/FLSharedKeys.java, Java/src/com/couchbase/litecore/fleece/FLValue.java, Java/src/com/couchbase/litecore/fleece/MDict.java
- move synchronization lock from SharedKeys to FLShardKeys
- make all methods with sharedkeys thread-safe.
- removed unused cods
=> Java: make SharedKeys thread safe

Java/jni/native_c4observer.cc
This is needed now to keep the change data from being leaked.
=> Java: Added call to c4dbobs_releaseChanges in JNI getChanges method

C/c4.def, C/c4.exp, C/c4Document.cc, C/tests/c4DocumentTest.cc
I had to replace the implementation of c4doc_update with one that just
uses c4doc_put, so it won’t be as fast. (It’ll do a read-modify-write
instead of just modify-write.) But it’s the only thing I can think of
that’s safe to do for 2.0.0.
Still needs a unit test.
Fixes #478
=> Stop c4doc_update() from clobbering remote-revID state

LiteCore/Support/FilePath.cc, LiteCore/Support/FilePath.hh, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/tests/LogEncoderTest.cc
Deletes all but 10 log files in the given directory by examining each file for the logging magic number, and then sorting the entries by modification date and deleting the (x - 10) oldest.
Note: An actual log rotation implementation is on the `feature/log-rotation` branch.
=> Purge old log files

LiteCore/Query/QueryParser.cc, LiteCore/Storage/UnicodeCollator.cc, LiteCore/tests/QueryParserTest.cc
- In QueryParser::writeCollation(), add double quote to mark the collation name as identifier; this will allow to have unexpected chars such as ‘-‘ in the name.
- In Collation::sqliteName(), support long locale name. The locale name can be a free string even though it might not be a valid locale name.
#550
=> Fixed #550 : Unicode collator issue with long locale name and minus char

LiteCore/Query/QueryParser.cc
Fixes #555
Test added on lite-ios branch issue/litecore-555
Can't figure out why I can't build on the latest master, but I did get this building once on slightly older code and it seems to work.
=> Fix issue with high precision floats in query

Replicator/Puller.cc
If sequence exists, made sequence completed to mark that the sequence has been successfully pulled and allowed the unitsCompleted to be updated correctly.
#571
=> Fixed #571 unitsCompleted not being updated when norev is handled

C/c4Document.cc, C/include/c4Document+Fleece.h, C/tests/c4DocumentTest.cc, LiteCore/Database/LegacyAttachments.cc, REST/RESTListener+Handlers.cc, Replicator/IncomingRev.cc
* In `_attachments`, 2.0 blob key will be in `blob_<number>` format, while 2.1 blob key will be in `blob_/<property-pointer>` format.
* In LegacyAttachments.encodeStrippingOldMetaProperties(root, key), detect 2.0 blob key by checking whether the suffix after `blob_` is a digit or not. If 2.0 blob key is detected, remove the attachment and continue.
* Made c4doc_encodeStrippingOldMetaProperties(doc, sk, outError) returns out error.
* When handle incoming rev, check the error when calling c4doc_encodeStrippingOldMetaProperties() and return 500 error code if there is an error occurs. Similar thing was done in RESTListener+Handlers.cc
* Updated c4DocumentTest
#565
=> Handle blob from 2.0.0 when stripping legacy _attachments

LiteCore/Support/Logging.cc, LiteCore/tests/LogEncoderTest.cc
purgeOldLogs() would get fooled if it couldn’t open a file in the log directory, and might assume it was a log file, then try to delete it. Bad news if logging is going to the system temp directory with lots of unrelated files belonging to other processes in it…
Fixes #576
=> Fixed log-rotation deleting non-log files

LiteCore/Database/PrebuiltCopier.cc, LiteCore/Support/FilePath.cc, LiteCore/Support/FilePath.hh, LiteCore/tests/DataFileTest.cc
* It will require a "hint" directory, and check that the default temp directory is both on the same device as the hint, and also writeable.
* Made `/data/local/tmp` default temp directory for Android.
=> Fixed #575  Build a more robust tempDirectory call

.travis.yml, CMakeLists.txt, build_cmake/scripts/build_unix.sh
- fix build_cmake/scripts/build_unix.sh to return not 0 on error
=> use travis for testing linux build on Ubuntu 14.04.5 LTS

Java/jni/native_c4database.cc, Java/jni/native_c4document.cc, Java/jni/native_c4replicator.cc, Java/src/com/couchbase/litecore/C4Database.java
- c4db_free is now not returning any value 
- doc constructor takes alloc_slice as fleece data instead of FLSLice 
- documentEndedCallback accepts two more parameters (C4HeapString revID, C4RevisionFlags flags) and parameter docID is C4HeapString instead of C4String
=> Update JNI Binding base on the latest change in LiteCore

Java/androidTest/java/com/couchbase/litecore/C4DatabaseTest.java, Java/jni/native_c4database.cc, Java/jni/native_c4document.cc, Java/src/com/couchbase/litecore/C4Database.java, Java/src/com/couchbase/litecore/C4Document.java
Base on API, in setDocumentExpiration, we set null to remove expiration from document, and in getDocumentExpiration, we get null when the document has no expiration set.d in getDocumentExpiration, we get null when the document has no expiration set.
=> Document expiration

LiteCore/Storage/KeyStore.cc
The time() function doesn’t return the correct time since Epoch for android. Used std::chrono::system_clock::now().time_since_epoch() instead for Android.
=> Fix KeyStore.now() function for Android

C/c4Base.cc, build_cmake/scripts/get_repo_version.ps1, build_cmake/scripts/get_repo_version.sh
In EE builds, return the actual Git commit ID as well as the build ID ($VERSION).
Tested by modifying the script to set VERSION and BLD_NUM, then verifying the unit tests log the right info.
Fixes #613
=> c4log_getBuildInfo: Return correct Git ID in EE build

LiteCore/Query/SQLiteKeyStore+PredictiveIndexes.cc, LiteCore/tests/PredictiveQueryTest.cc
* Allowed to create a PredictiveIndex without properties specified so that the index can be used as a result cache only.
* Allowed to create a compound PredictiveIndex with multiple properties specified.
* Added unit tests.
=> Update PredictiveIndex to support only-cache index and compound index

Java/src/com/couchbase/litecore/fleece/Encoder.java, Java/src/com/couchbase/litecore/fleece/FLEncoder.java
I was going to ask this as an issue but thought it might be easier as a PR with a diff. 
I got the following exception saving data containing `Short` values using CBL 2.1.0 on Android:
java.lang.ClassCastException: java.lang.Short cannot be cast to java.lang.Float
I think it is just a missing case in these two encoders. I've haven't been able to test it properly and may have completely misdiagnosed the issue, in which case please just close this. 😄 
(Maybe also consider adding `Byte`, `BigInteger`, `BigDecimal`?)
=> Support for encoding java.lang.Short numeric values

LiteCore/Support/Logging.cc
Ensure that the sLogDirectory get parsed fully as the directory when creating the FilePath object. Otherwise, the last path component of the the directory without `/` at the end will get truncated.
=> Fix creating log directory FilePath object

LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/PredictiveQueryTest.cc
* The cache-only predictive index doesn’t create an actual index so the index schema doesn’t exist.
* Updated the schemaExistsWithSQL() function to check if the given sql is empty or not. If the given sql is empty, return true if the scheme doesn’t exist, otherwise return false.
* Updated the predictive index unit tests to also test creating index twice.
#663
=> Fix predictive cache table getting dropped when creating the same index again

LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
This PR will move the log object refs to a central location so that everything has a consistent view.
This will allow a consistent view of objects between all objects that need them
Fixes #671
=> Fix for incorrect logging refs

LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
Instead of LogEncoder asking for objects, provide them upfront.  This prevents a deadlock on LogDomain's mutex.
Fixes #680
=> Remove spaghetti flow between LogDomain and LogEncoder

C/c4Document.cc, C/include/c4.hh, C/include/c4Base.h, C/tests/c4DocumentTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, LiteCore/Database/Document.hh, LiteCore/Database/TreeDocument.cc, LiteCore/Database/Upgrader.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, LiteCore/Support/Error.cc, LiteCore/Support/Error.hh, LiteCore/Unix/arc4random.h, LiteCore/tests/LiteCoreTest.cc, Replicator/DBWorker.cc, Replicator/DBWorker.hh, Replicator/IncomingBlob.hh, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.hh, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.hh, Replicator/Worker.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
I wrote a unit test that tries to reproduce the customer scenario in #669 by running a continuous bidirectional replication (in no-conflicts mode) and rapidly updating the same document on both sides. It revealed several replicator bugs, which I've fixed. Along the way, I improved replicator logging and added functionality to the ReplicatorLoopbackTest class.
I'm making this a PR so the branch is easy to find and test ... it seemed better not to dump this stuff into master right away. 🤓
Fixes #669
=> Fix bidirectional replication conflict handling

LiteCore/Query/SQLiteQuery.cc, LiteCore/tests/FTSTest.cc
Stop-words should not be removed in the target of a MATCH if immediately followed by a “`*`”, since in that case they’re just prefixes. For example, “`he*`” should not be removed.
Fixes #626
=> Fixed stop-word processing in MATCH target strings

C/tests/c4QueryTest.cc, C/tests/c4Test.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh
A query that uses both FTS and aggregation should not add the implicit `offset()` result column, because it doesn’t make sense as an aggregate result.
I also cleaned up some of the other logic in the `writeSelect` method. Nothing calls `setBaseResultColumns` so I was able to remove the `_baseResultColumns` member var, for example.
Fixes #703
=> Fixed SQL error in FTS queries using aggregation

LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh
To prevent a race between the timer callback and deleting the timer, delete the timer in a deterministic fashion.  The explicit delete, and subsequent lack of value, should prevent scheduling after deletion.
Fixes #706
=> Delete the timer of the LogEncoder eagerly

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/tests/QueryTest.cc
* When getting a SQLite integer value, get it as int64 instead of int.
* Added a unit test that queries a dictionary literal with all basic value types.
#709
=> Fix writing int64 values when selecting dictionary literal

LiteCore/Database/SequenceTracker.cc, LiteCore/Database/TreeDocument.cc, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Support/Logging.hh, Replicator/DBAccess.cc, Replicator/IncomingBlob.cc, Replicator/Inserter.cc, Replicator/Puller.cc, Replicator/Pusher+DB.cc, Replicator/Pusher.cc, Replicator/Worker.cc
There is problem with 64 bit types and printf specification. 
Normally `int64_t` is `long long` on 32 bit platform, and `long` on 64 bit platform.
So it impossible to choose right variant from `%ld` or `%lld`, that's why there is 
https://en.cppreference.com/w/cpp/types/integer and `PRIdx` and similar specifiers.
This PR should makes code more portable, plus fix bunch of warnings.
Plus after merge PR against vendor sub repositories it would be possible to turn on `-Werror=format` for clang based platforms.
=> fix clang warnings about wrong fmt arguments

Replicator/DBWorker+Pull.cc, Replicator/tests/ReplicatorLoopbackTest.cc
Applying a delta was failing when there was a pullValidator present,
and the delta JSON contained a new doc property not yet in the DB’s
SharedKeys.
In this situation the DBWorker now re-encodes the current rev body so
it doesn’t use the DB’s SharedKeys, before applying the delta to it.
None of the unit tests triggered this, because the delta tests didn’t
use a pullValidator (or vice versa.) I’ve remedied that.
Fixes #732
=> Fixed delta sync when pull filter present

LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh
This was supposed to be fixed long ago, but SQLiteDataFile was doing things in the wrong order: calling the super close method, which decrements the file’s in-use count, before actually closing the SQLite db. That meant that another thread calling deleteDatabase would unblock and delete the file before the first thread was done closing.
Fixes #739
=> Ensure all dbs are closed before deleting file

Java/src/com/couchbase/litecore/fleece/FLDict.java, Java/src/com/couchbase/litecore/fleece/MDict.java
Instead of checking whether the key string is null, check the value instead. When a dictionary is empty, calling getKeyString() will result to the an invalid address as the internal _key of the Dict will be null.
https://github.com/couchbase/couchbase-lite-android/issues/1899
=> Fix JNI iterator that checks key string instead of value

CMakeLists.txt
I use some tool `XYZ` that care about modification time of source files.
And every rerun of cmake cause `empty.cpp` update,
and cause `XYZ` rerun for nothing.
I don't know why generate this source file via cmake and don't just add it into repository,
but do not touch if file already exists seems good thing for me and for SSD disk lifetime.
=> do not change timestamp of source file every time of cmake run

Replicator/CookieStore.cc, Replicator/tests/CookieStoreTest.cc
Alter the test to check such.  Fixes #510.
=> Cap 32-bit linux cookie date to the max value

LiteCore/Query/QueryParser+Prediction.cc, LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh
It now operates on property paths using Fleece’s Path class, instead of first parsing them and then converting to strings and then parsing the strings again.
(There have been enhancements to the Path class too, in Fleece.)
=> Fixed some technical debt in QueryParser (path parsing)

LiteCore/Database/Database.cc
Race condition where a C4Database is freed while another C4Database on the same file ends a transaction.
Fixes #776
=> Fixed race condition crash during c4db_endTransaction

LiteCore/Database/Database.cc, LiteCore/Storage/DataFile+Shared.hh, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh
Instead of trying to lock, use another method that indicates that a data file is in the process of closing.
See #776
=> Alternative solution for close vs transaction race

LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/tests/ReplicatorLoopbackTest.cc
* adds the unresolved docs to the docs-ended queue so that it tries to resolve when status changes.
* add method in DBAccess to return the docEnumerator, instead of vector<docInfo>, which can avoid one iteration of all docs.
* RevToSend was push, which will not work in docsEnded method in CBL side.
* include c4Error with conflict, so that it is handled like wise in CBL.
=> feat: unresolved documents when restarting replicator

Replicator/Replicator.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.hh
On a connection failure, the replicator will sometimes go from
Connecting to Busy state before going to Stopped. This confuses the
platform code that handles retries of failed connections, because it
looks like the connection initially succeeded.
I changed Replicator::computeActivityLevel() so that, when the
connection is closed but the replicator has more work do do, it will
report the status Connecting instead of Busy if its previous status
was Connecting.
I updated the "API Connection Failure" test to assert that the
replicator status never goes to busy -- this new assertion then
failed until I implemented the above fix.
Also added some test assertions to make sure that Stopped is always
the final state.
Fixes [CBL-45](https://issues.couchbase.com/browse/CBL-45)
=> Replicator shouldn't go to Busy on disconnect if it never connected

C/tests/c4Test.cc, C/tests/c4Test.hh, LiteCore/Database/TreeDocument.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, Replicator/Pusher+DB.cc, Replicator/Pusher.hh, Replicator/ReplicatorTypes.cc, Replicator/ReplicatorTypes.hh, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorSGTest.cc
Pusher::revHistoryString() would sometimes write every revision to
the history, ignoring the maxRevTreeDepth limit. If there were
thousands of revs in the history, this could overflow the BLIP
message's properties and cause an exception on the receiving end.
I fixed this. (Also moved the method to RevToSend, since it makes
more sense there.)
On the receiving side, I changed RevTree::insertHistory so it won't
complain about truncated histories, as long as the truncated part is
revs that would be pruned anyway.
Unit tests added for both loopback and SG replications.
Fixes [CBL-106](https://issues.couchbase.com/browse/CBL-106)
=> Fixed C++ exception pushing huge numbers of revs

Replicator/DBWorker+Pull.cc, Replicator/DBWorker.hh, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.cc
If the puller receives a `changes` message with a docID that's already
got a pending rev coming in, don't return any ancestor rev IDs for it.
That way we won't receive a delta with a base revision that's no
longer current and we don't have the body of.
Fixes CBL-136
=> Fix for super-fast pulls with deltas (CBL-136)

Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.cc
The replicator never went to Stopped after >100 docs were rejected by
the client's validation filter.
The bug was that IncomingRev didn't clear its _provisionallyInserted
flag when it was reused a second time; this then caused the Puller to
not decrement _activeIncomingRevs when that IncomingRev finished,
which meant the Puller remained in Busy state.
Fixes CBL-171
=> CBL-171: Fix Puller not stopping after filter rejects docs

C/c4.def, LiteCore/Support/FilePath.cc
* return type for the `CopyFileW();` success return value is 1 where as `CopyFile2` which is zero. 
* add references to remove gradle build failure.
=> CBL-160: fix: java issues on windows 

LiteCore/Query/Query.cc, LiteCore/Query/Query.hh, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/tests/QueryTest.cc
We can't leave any active sqlite3_stmt when closing a DataFile,
because if the database is deleted its files will still be open,
which causes errors on Windows. This situation occurs when a Query
instance still exists, since SQLiteQuery owns a sqlite3_stmt.
Freeing the C4Query objects isn't always possible because if CBL is
implemented in a garbage collected language the objects' finalizers
may not yet have run.
The fix is to have the DataFile track all open Query instances and
tell them to close when it closes. SQLiteQuery closes its statement
when it closes.
Added some logic to DataFile::deleteFile to enforce that no handles
are left open when closing a db that's about to be deleted. This
allowed me to write a unit test to verify the fix even on non-
Windows platforms.
Fixes CBL-214
=> Close existing Query objects when closing DataFile

Replicator/DBAccess.hh, Replicator/DatabaseCookies.cc, Replicator/IncomingBlob.hh, Replicator/IncomingRev.hh, Replicator/Inserter.hh, Replicator/Puller.hh, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.hh, Replicator/RevFinder.hh, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/c4Replicator.cc
Added NONNULL to all applicable method parameters in headers.
Changed C-style casts to dynamic_cast<> where feasible.
(I just went through the replicator code, not all of LiteCore...)
=> Use NONNULL and dynamic_cast in replicator code

C/tests/c4Test.cc, C/tests/c4Test.hh, Replicator/Puller.cc, Replicator/Pusher.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh
It needs to wait until all the unfinished incoming revisions are done.  These are interjected in a thread-suspicious way by the Inserter.
=> CBL-221 Keep Puller in busy status longer

C/tests/c4QueryTest.cc, C/tests/c4QueryTest.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/QueryParserTables.hh
Note:  Inside of the actual JSON, since there is another level of escaping, all backslashes need to be double escaped.  Perhaps consider a different escape character?
=> CBL-175 Escape backslash inside of LIKE expressions

Jenkinsfile, jenkins/jenkins_unix.sh, jenkins/jenkins_win.ps1
No need to check which repo we are in, because we know already by virtue that this Jenkinsfile / script set is getting executed
=> Trim down the excess functionality in PR validation

C/c4.def, C/c4.exp, C/include/c4Replicator.h, Replicator/c4Replicator.cc, Replicator/tests/ReplicatorAPITest.hh
It's possible for a replicator to start and call a progress callback
before the c4repl_new function returns; in that case the client
hasn't yet set the C4Replicator handle, so if the callback references
it, it will get null (or worse, garbage.)
This is a pretty rare situation given the timing required, but it
does happen to the ReplicatorAPITest occasionally on Jenkins and
causes a test failure.
To address this, I added a flag to the options that if set prevents
c4repl_new from starting the replicator. Then the client, once it has
the C4Replicator handle, can call a new function c4repl_start.
=> Fixed race condition starting replicators

LiteCore/RevTrees/RevTree.hh
=> RevTree.hh: UINT_MAX used, but there is no climits include

Replicator/tests/ReplicatorAPITest.hh
Sometimes the error comes so fast that it's already stopped by the time it reaches the first check to see if it started.  Only allow this in the case where we expect failure though.
=> Plug another race in the replicator tests

Replicator/Replicator.cc, Replicator/Replicator.hh
If for some reason an HTTP 409 is received, then the checkpoint should be refreshed and updated again.
=> CBL-112 Refresh the remote checkpoint when necessary

C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc
Query was compiling and causing the error, `CouchbaseLite Database ERROR: SQLite error (code 1): no such column: db.db.rowid` 
* was under the impression that, issue is with including same db-alias twice. instead of `db.db.rowid`, it should be `db.rowid`
```
let q = QueryBuilder.select(SelectResult.expression(Expression.property("sentence")
.from(alias)))
.from(DataSource.database(db).as(alias))
.where(FullTextExpression.index("sentence").match("'Dummie woman'"))
.orderBy(Ordering.expression(FullTextFunction.rank("sentence")).descending())
```
```
{"WHAT":[[".db._id"],[".db.sentence"]],"WHERE":["MATCH","sentence","'Dummie woman'"],"FROM":[{"AS":"db"}],"ORDER_BY":[["DESC",["RANK()","sentence"]]]}
```
```
"SELECT "db".db.rowid, offsets(fts1."kv_default::sentence"), fl_result("db".key), …
```
=> CBL-369: no such column: db.db.rowid

Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.cc
*Chery pick:* 7380a17c45e50ce51eeb3740a1d5f42c02ba757f
```
The replicator never went to Stopped after >100 docs were rejected by
the client's validation filter.
The bug was that IncomingRev didn't clear its _provisionallyInserted
flag when it was reused a second time; this then caused the Puller to
not decrement _activeIncomingRevs when that IncomingRev finished,
which meant the Puller remained in Busy state.
- Fixes CBL-171
```
=>  CBL-171: Fix Puller not stopping after filter rejects docs

C/tests/c4QueryTest.cc
* corrected format 'diacritic': false, to 'diac': false
* CBL-412
* duplicate three diacritic artist names got removed, since it is false. 
- [406] "Dälek"
- [590] "Félix"	
- [707] "György Ligeti"
=> CBL-412: fix: collate diac key

C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/Storage/UnicodeCollator.cc, LiteCore/Storage/UnicodeCollator.hh, LiteCore/Support/StringUtil.cc, LiteCore/Support/StringUtil.hh
A few things go into making this possible:
- Add a new entry into the parser table function spec indicating if a function can take a collation, if offered.  It will always be the last thing passed to it.
- Replace LIKE with FL_LIKE() (breaking change for CBL!)
- FL_LIKE() and CONTAINS() now have both 2 and 3 argument variants
- Split UTF8Length into two functions, the latter returning the number of bytes in the next character (useful for comparing slices char by char in a multibyte friendly way)
=> CBL-52 Make the LIKE and CONTAINS functions collation aware

Replicator/Replicator.cc, Xcode/xcconfigs/Project.xcconfig
CBL-468: Null dereference during pull-only replication
_pusher will be null if push is disabled
Change-Id: I2f1686e8785fb74439a53e15e002ca037245cb77
=> 2.6.2 release candidate

C/tests/cmake/platform_linux.cmake, CMakeLists.txt, LiteCore/tests/cmake/platform_linux.cmake, cmake/platform_linux_desktop.cmake
- Use CMake tools to find zlib, rather than depending on compiler
(because on Centos 6 we need to use version from cbdeps)
- Find additional ICU libs
- Fix issue looking up git commit SHA
- Add -D__STDC_FORMAT_MACROS
- Only use cbdeps-provided headers for libcxx if they don't exist on system
(because Centos 6 build slave provides them and gets confused if we use
a different set)
=> MB-36238: Numerous build cleanups, partly for Centos 6

Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/ReplicatorTypes.hh, Replicator/tests/ReplicatorLoopbackTest.cc
At least in some cases.  The goal here is to have certain error types being transient a limited number of times, but permanent after that.
=> CBL-123: Keep track of the retry count of pushable revisions

C/tests/c4DatabaseInternalTest.cc, C/tests/c4DocumentTest.cc, CMakeLists.txt, LiteCore/Database/TreeDocument.cc, LiteCore/Support/crc32c.cc, LiteCore/Support/crc32c.h, LiteCore/Support/crc32c_armv8.cc, LiteCore/Support/crc32c_sse4_2.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, cmake/platform_android.cmake, cmake/platform_apple.cmake, cmake/platform_base.cmake, cmake/platform_linux.cmake, cmake/platform_win.cmake
Switching the revision ID algorithm from SHA-1 to CRC32-C.  This revision ID is not required to be secure, so this algorithm will be faster.  It is especially fast in the presence of SSE4.2.  It also has hardware instructions on armv8 but it is still unclear how to compile them in a safe way (to check for older devices that may not support the CRC extensions).  I will leave in the implementation because by default the compiler defines are off and thus it is compiled out.  
I have a feeling that we won't be able to take advantage of the armv8 instructions until we raise our minimum versions of Android / iOS in the future.
=> CBL-242 Switch to CRC32C for revision ID

LiteCore/Database/Upgrader.cc
Any document ID which starts with an underscore will be skipped when
upgrading the database from CBL 1.x to 2.x.
Discussion and suggestion for this change can be found here:
https://forums.couchbase.com/t/doc-with-invalid-id-from-cbl-1-x-crashes-app-when-upgrading-to-cbl-2-x/23534/11
=> Skip upgrading docs with underscore prefix

Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
Make sure everything is torn down cleanly if a C4Replicator is
released without having ever been started. There are reference
cycles in the underlying objects that need to be untangled.
Fixes CBL-524
Part of the fix is in BLIP-Cpp -- [here's the commit](https://github.com/couchbaselabs/BLIP-Cpp/commit/8bbba50dcb3d023eb07df0f0649389e7c8c003a9)
=> Don't leak objects if C4Replicator is released w/o being started

Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
Two main things are needed to make this work:
1. Most of the logic needs to move from Pusher to Replicator since Pusher is null after stop
2. Db cannot be set to null on stop because it is essential that the Replicator still have DB access in order to get documents to check if they are pending (and to create iterators).  So reset it unconditionally in terminate, and don't reset it after stop
=> CBL-528 Fix accessing pending document IDs after stop

C/tests/c4QueryTest.cc, LiteCore/Query/Query.hh, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh
Use it in conjunction with last sequence in order to properly refresh a C4Query after a purge operation on the database
=> CBL-444 Add a purge count to the database

LiteCore/Support/SequenceSet.hh, Replicator/Pusher.hh
* It wasn't thread-safe, because SequenceSet wasn't
* The logic was wrong in that it would return false for a sequence newer (greater) than any seen by Pusher::gotChanges.
=> Fixed problems with Pusher::isSequencePending()

C/c4DocEnumerator.cc, C/include/c4DocEnumerator.h, LiteCore/Database/Database.cc, LiteCore/Query/SQLiteKeyStore+Indexes.cc, LiteCore/Storage/RecordEnumerator.cc, LiteCore/Storage/RecordEnumerator.hh, LiteCore/Storage/SQLiteEnumerator.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/DataFileTest.cc, Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/Replicator.cc, Replicator/tests/ReplicatorLoopbackTest.cc
C4DocEnumerator:
* Added option flag for unordered results.
* Conflicts-only option is passed through to the RecordEnumerator.
* Stripped out unused/unneeded functionality, like filtering.
RecordEnumerator:
* Added options for conflicts-only & unordered results.
* With Debug-level query logging, it explains its query plan.
Database:
* Added SQLite partial indexes for conflicted docs and docs with blobs.
* During compaction, enumeration of docs with blobs is now unordered.
Replicator:
* The conflicted-docs scan is unordered, to speed it up.
* Logging before and after the scan, including the time taken.
Fixes [CBL-536](https://issues.couchbase.com/browse/CBL-536) (but hasn't been benchmarked on large dbs!)
=> Optimized pre-pull scan for conflicted docs

LiteCore/Storage/DataFile+Shared.hh
Otherwise there is a small window in which non-deterministic garbage collection from a managed language could destroy the shared object after it is returned from the `forPath` method.  Both usages of this method already retain it anyway.
=> CBL-527: Retain shared memory object earlier

C/tests/c4DatabaseEncryptionTest.cc, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh
The schema upgrade required for purgeCount in 2.7 was causing an
exception when opening a database read-only.
* Made some logic changes to skip the upgrade if the db is read-only.
The purgeCount() method will return 0; it isn't needed in read-only
mode anyway because the db won't change.
* Also catch + ignore the SQLITE_READONLY exception thrown if the
db _file_ is read-only.
* Throw a better exception (CantUpgradeDatabase) if the database is
writeable but not upgradeable.
* Improved readability & reliability with a snazzy custom enum class
for the schema versions. ^_^
* After all that, updated the test to skip the kC4DB_NoUpgrade mode
since it still fails. (But at least kC4DB_ReadOnly works now!)
Fixes CBL-562
=> Restore ability to open pre-2.7 dbs read-only

Replicator/c4Replicator.hh
For example, db1 -> db2 should use db2 URL as the remote an db1 -> db3 should use db3 URL but they are both using db1 URL
=> CBL-594 Correct the URL of LoopbackSocket

C/c4Base.cc
There are quite a few cases where it is permanent (e.g. sync function exception)
=> CBL-590: Remove HTTP 500 from transient error list

LiteCore/Storage/DataFile.cc, Replicator/DBAccess.cc
Plug it on both sides for extra safety.  The fleece commit stops an arbitrary int from being encoded as a shared key, and this commit stops a gap between creation and refresh of shared keys where incorrect count / state data will be returned.
=> CBL-619: Try to plug a rare race in SharedKeys

C/c4.def, C/c4.exp, C/c4.gnu, C/c4Query.cc, C/include/c4Observer.h, C/scripts/c4.txt, C/tests/c4QueryTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
After a thread creates an observer, it was possible for the callback
to be called (on another thread) before c4queryobs_create returned.
In this case the app's reference to the observer wouldn't be set yet,
which could cause problems (as in one of our unit tests.)
To prevent this case, a query observer now has to be enabled before
its callback will be invoked.
This API also makes it possible to disable an observer without
freeing it, which could be useful in situations like a backgrounded
app.
=> API: Added c4queryobs_setEnabled, to prevent a race condition

Replicator/Checkpointer.cc, Replicator/Checkpointer.hh
Only occured in P2P replication (or unit tests), and only when "SyncBusy" logging is enabled.
This is a regression from the dev-branch merge, so won't affect any released versions.
Fixes CBL-643
=> Fix null-Checkpoint logging crash

C/c4PredictiveQuery.cc, Replicator/Pusher.cc
1. Don't call `_checkpointer` after the Replicator (which owns it) is gone.
2. Incorrect conversion of DataFileDelegate* to c4Database* (due to the intricacies of C++ multiple inheritance), manifesting as a bogus C4BlobStorage* passed to c4blob_getContents. (CBL-648)
Fixes CBL-648
=> Fixed two crashes (Checkpointer & C4PredictiveModel)

Jenkinsfile, LiteCore/tests/cmake/platform_linux.cmake, Networking/TCPSocket.hh, cmake/platform_linux_desktop.cmake
Basically work around a G++ optimizer bug, and disable LTO because it fails to build
=> Fix GNU toolchain build

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/Query/SQLiteFleeceUtil.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/Storage/UnicodeCollator.cc, LiteCore/Storage/UnicodeCollator.hh, LiteCore/Storage/UnicodeCollator_Apple.cc, LiteCore/Storage/UnicodeCollator_ICU.cc, LiteCore/Storage/UnicodeCollator_Stub.cc, LiteCore/Storage/UnicodeCollator_winapi.cc
Avoid creating new CollationContext objects on every call.
NOTE: I have not tested on Linux or Windows, although it makes some changes to platform specific code. @Dushistov, could you check whether this works and fixes the slowdown?
Fixes #902 (speculatively)
=> Sped up N1QL 'LIKE' and 'contains' functions

Networking/BuiltInWebSocket.cc, Networking/BuiltInWebSocket.hh
The ad-hoc self-retain/release calls in BuiltinWebSocket didn't work in all circumstances, causing leaks.
Use a Retained<> instance instead, which is safer, and clear it in closeWithError() which is always called on close.
=> Fixed BuiltinWebSocket leak

Replicator/Puller.cc, Replicator/Pusher+DB.cc, Replicator/Pusher.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/Worker.cc, Replicator/Worker.hh
The only way the crash in CBSE-7927 could occur, I think, is from `Puller::_revWasProvisionallyHandled()` being called after `_disconnected()`. Added a test to the former method to keep it from initiating any more activity that requires a connection.
**The actual crash fix is at Puller.cc:267, where it now skips creating any IncomingRevs if no longer connected.**
The rest of the patch adds more robustness:
* `connection()` method now asserts `_connection != nullptr`, and returns a reference to reinforce that it won't return null.
* Added `connected()` method returning `bool` for the majority of cases that just want to check whether they're connected.
* Worker constructor (that crashed) now calls `connection()` to get that assertion check. It also now has NONNULL pointer parameter …
=> Speculative fix for replicator crash in Worker::Worker (CBSE-7927)

LiteCore/Query/QueryParser.cc, LiteCore/tests/QueryTest.cc
In a WHAT clause, ["IN", "foo", "col1"] should create a result column whose value is the string literal "foo", with alias "col1". Instead, "foo" was being interpreted as a property name. Fixed.
The bug was due to an ugly hack where QueryParser::parseStringLiteral() interprets the string as a property not a literal, if it's in the context of a column-list or result-list. I took out the "...or result-list" part, and moved that special case into the AS-handling code where it belongs.
Fixes CBL-698
=> Fixed interpretation of string literals as result aliases

Replicator/IncomingBlob.cc
Fixes an edge condition where, if the socket disconnects unexpectedly,
the replicator might add a pulled document even though its blobs
haven't been downloaded.
Fix is for IncomingBlob to set an error status when it fails to read
the entirety of its streamed BLIP message. That tells its parent
IncomingRev that everything is not OK, so it won't try to save the
revision.
We don't have any good way to unit-test this, unfortunately.
Fixes CBL-608
=> CBL-608: Speculative fix for missing pulled blobs

C/c4Base.cc, C/include/c4Socket.h
* transient and permanent status codes by user was previously handled in platform side, now moving it to lite core. 
* include the transient code maybe_transient method. 
linking closed PR: https://github.com/couchbase/couchbase-lite-core/pull/923
=> CBL-704: Fix: Include user generated websocket closure codes

C/tests/c4BlobStoreTest.cc, LiteCore/BlobStore/BlobStore.cc
If, for some reason, a blob file is open for reading or writing by another thread (or process) then installing a blob will fail with EACCES.  However, since a blob's contents are cataloged by filename it means that if an attempt is being made to write to the same blob filename, it means that an identical blob already exists and the write can be skipped.
=> CBL-670: Fix Windows issue with blob permissions

LiteCore/Database/TreeDocument.cc, Replicator/Puller.cc
The while loop in question now becomes a delayed loop.  The next batch will be processed when the unfinished rev count reaches zero, meaning all the currently requested revisions have been received.
=> CBL-578 Don't process change messages immediately in parallel

Replicator/c4IncomingReplicator.hh, Replicator/c4RemoteReplicator.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, jenkins/jenkins_unix.sh, jenkins/jenkins_win.ps1
If the DB is reopened immediately in the call to the various c4repl_new functions, then it remains open for the life of the C4Replicator.  It only needs to be reopened for the actively replicating part of the replication, so reopen it in the C++ replicator class instead so that it goes away after stop.
=> CBL-683: Don't reopen the DB so early in the replication process (CE part)

C/include/c4Replicator.h, Replicator/c4RemoteReplicator.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh
Introduce a new replicator status "stopping" to indicate that we are in transit so that we can ignore or properly handle subsequent calls happening between the impetus for the stop or offline, and the actual stop / offline status change.  In particular two cases are handled better now:
1. Suspending while a stop is in progress
2. Unsuspending while suspending is in progress
=> CBL-722 / CBL-729: Fix corner cases with suspending and unsuspending

C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/tests/QueryParserTest.cc
Implement getting the document’s revisionID through query via _revisionID property.
=> CBL-767 : Support _revisionID in Query

Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/tests/ReplicatorLoopbackTest.cc
First commit defers retrying the revisions in `_revsToRetry` until other work is done, i.e. until the Pusher would otherwise go idle.
Second commit fixes a bug where a revision isn't pushed due to a false conflict, when:
* Pusher gets a 409 status proposing a revision to send
* Puller receives 'change' message including newer rev of the same
doc, which already exists locally (so no new rev is added but the
remote-rev property is updated.)
In this situation the Pusher should retry the revision, with the newer remote-rev. This is tricky to implement because it requires coordination between the Pusher and Puller. I made the Puller notify the Pusher when a doc's remoteRevID is changed without adding a new revision. The Pusher keeps track of a set of conflicting revs, and will retry one when …
=> CBL-726: Re-push a failed rev if its remote-ancestor changed

C/c4Internal.hh, C/c4PredictiveQuery.cc, C/c4Query.cc, C/c4Query.hh, C/c4QueryEnumeratorImpl.hh, C/c4QueryObserver.hh, C/include/c4Observer.h, C/tests/c4QueryTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, LiteCore/Database/BackgroundDB.cc, LiteCore/Database/BackgroundDB.hh, LiteCore/Database/Database.cc, LiteCore/Database/Database.hh, LiteCore/Database/LiveQuerier.cc, LiteCore/Database/LiveQuerier.hh, LiteCore/Database/SequenceTracker.cc, LiteCore/Query/Query.cc, LiteCore/Query/Query.hh, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, Replicator/c4Replicator.hh, Xcode/LiteCore.xcodeproj/project.pbxproj
I reported the issue as "C4QueryObserver does not trigger when a doc is purged", but that turned out not to be the case; the problem is a race condition that makes it miss some changes. To fix that I changed the way that it gets triggered: now it's only on transaction commits, not on individual changes.
**NOTE:** It's probably best to read through the individual commits rather than the merged view.
Fixes CBL-688
=> Fixed C4QueryObserver (LiteCore's LiveQuery)

Replicator/Replicator.cc
Before switching to the stopped state, the replicator should wait for the puller (and the pusher, but that is less likely to be an issue)
=> CBL-799: Replicator should wait for Puller

LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/QueryTest.hh
Takes 2+ parameters, converts each to a string and concatenates them.
Returns MISSING if any parameter is MISSING.
The existing '||' operator now translates into a 'concat()' call
because a regular SQLite '||' expression doesn't know what to make of
nulls or collections.
=> Implemented N1QL concat() function

C/c4Certificate.cc, C/include/c4Certificate.h, Crypto/Certificate.cc, Crypto/Certificate.hh
This allows clients to set arbitrary names if they want.
Fixes CBL-814
=> C4CertNameAttributeID is now a string (slice) not an enum [API CHANGE]

C/tests/c4DatabaseTest.cc, LiteCore/Support/Timer.cc, LiteCore/Support/Timer.hh
It was possible for a Timer instance to be rescheduled even while its
destructor was being called. The Timer would then be invoked later on
when it was garbage, likely causing a crash or corrupting whatever
other object occupied the addresses of the Timer's _triggered and
_state fields.
Sequence to reproduce:
1. Timer's callback is called (on Timer thread)
2. Timer's destructor is called (on another thread), blocks...
3. The callback calls timer->setFireTime() to reschedule
4. Callback exits
4. ...destructor exits now that callback is done.
5. Later, the Timer::Manager triggers the deleted Timer; boom.
Fixed this by having the Timer's destructor move it to a new kDeleted
state, and having setFireTime() do nothing if the timer is in that
state.
I believe this was the cause of CBL-854 …
=> Fixed a crashing Timer bug

C/include/c4Listener.h, REST/RESTListener.cc, REST/tests/ListenerHarness.hh
Instead of using C4Slice for setting the private key, certificate and rootClientCerts, use C4KeyPair and C4Cert accordingly.
#CBL-897
=> Use C4KeyPair and C4Cert in C4TLSConfig

LiteCore/Support/Actor.hh, Networking/BLIP/cmake/platform_base.cmake, Xcode/xcconfigs/Project.xcconfig
* Changed `*_DEPLOYMENT_TARGET` definitions accordingly.
* Changed `VALID_ARCHS`; there is no armv7a but there is armv7s.
* Added `-fno-aligned-allocation` compiler flag on armv7/armv7s builds to avoid an annoying build error (see the issue)
* `#ifdef`-d out the experimental Async class from Actor; this didn't turn out to be needed to fix the above errors, but it's a good idea anyway.
Fixes CBL-734
=> Xcode: Restore iOS 9 and 32-bit iOS support

Crypto/CertificateTest.cc, Crypto/PublicKey+Apple.mm, Crypto/PublicKey.hh
* Made iOS support PERSISTENT_PRIVATE_KEY_AVAILABLE
* Fixed PublicKey+Apple to support both iOS (10.0+) and MacOS.
* Tested manually from CBL side on iOS 13.4.1 (Simulator and Device).
* Plan to test on all supported iOS and MacOS versions on the AWS device farm when the device farm permission is granted.
CBL-860, CBL-861
=> Enable iOS support in PublicKey.hh

C/c4Certificate.cc, C/include/c4Certificate.h, Crypto/Certificate.cc, Crypto/Certificate.hh, Crypto/CertificateTest.cc, Crypto/PublicKey+Apple.mm
* Instead of save, load, and delete certs using database, use Keychain instead.
* When save the certificate chain, the first cert (leaf cert) will be labelled with the specified label so that it can be queried by using the label. On macOS, need to update the label again after save.
* Use an evaluated trust to load the certificate chains; the trust evaluation result could be ignored.
* Replaced makePersistent() with save().
#CBL-910
=> CBL-910: Reimplement save, load, and delete certs using Keychain

LiteCore/Support/Error.cc, LiteCore/tests/c4BaseTest.cc, Networking/TCPSocket.cc, REST/Server.cc, REST/tests/RESTListenerTest.cc, REST/tests/SyncListenerTest.cc
This has the side effect of not being able to restart a listener for up to 60 seconds on some platforms as their sockets linger in TIME_WAIT or whatever it is called.
=> CBL-848: Don't allow two listeners on the same port

C/include/c4Replicator.h, Replicator/Checkpointer.cc, Replicator/Checkpointer.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4RemoteReplicator.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
As a part of making the replicator restartable, instead of passing the option as part of initialization pass the reset flag in the start method
=> CBL-895: Provide reset option to c4repl_start

C/c4Certificate.cc
Before assigning to the out parameter, check first if it’s null or not.
CBL-943
=> Fix potential crash in c4cert_getValidTimespan

C/include/c4Base.h, C/include/c4Listener.h, LiteCore/Support/Error.cc, Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/TLSContext.cc, Networking/TLSContext.hh, Networking/WebSockets/WebSocketInterface.hh, REST/Listener.cc, REST/Listener.hh, REST/RESTListener.cc, REST/RESTListener.hh, REST/Request.cc, REST/Request.hh, REST/Server.cc, REST/Server.hh, REST/c4Listener.cc, REST/tests/ListenerHarness.hh, REST/tests/RESTListenerTest.cc, REST/tests/SyncListenerTest.cc
* Optional cert-validation callback
* Optional HTTP auth callback
* c4listener_connectionCount() returns number of connected clients
Improved error handling for rejected TLS certs. When the peer rejects the TLS handshake, what comes back is a "fatal alert" code, which for some reason mbedTLS reports as a single error code even though there are many possible causes. I had to detect this error in sockpp and return a range of fake error codes to pass the actual alert codes up to TCPSocket.
Fixes CBL-679
=> C4Listener: added auth callbacks & connection-count

Networking/NetworkInterfaces.cc
As pointed in manual page getifaddrs(3) `ifa_addr` can contains null
> The  ifa_addr  field points to a structure containing the interface ad‐
>   dress.  (The sa_family subfield should be consulted  to  determine  the
>      format  of  the  address  structure.)   This  field  may contain a null
>      pointer.
In my case "tun0" interface was "up" but have no IP address on my Linux machine,
so call of `litecore::net::Interface::all` cause SIGSEGV
=> fix SIGSEGV if interface is up, but have no IP address

C/include/c4Replicator.h, Replicator/c4RemoteReplicator.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh
Clients can customize the number of retry attempts after the first, from the default of 2.
For CBL-945
=> Added kC4ReplicatorOptionMaxRetryInterval [API] CBL-945

C/c4.def, C/c4.exp, C/c4.gnu, C/c4Database.cc, C/include/c4Database.h, C/scripts/c4.txt, C/tests/c4DatabaseInternalTest.cc, C/tests/c4DatabaseTest.cc, C/tests/c4QueryTest.cc, LiteCore/Database/Database.cc, LiteCore/Database/Database.hh, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/tests/DataFileTest.cc
* Merged the `c4db_maintenance` commit from #963 into master.
* Added maintenance option for compaction, obsoleting `c4db_compact()` (now informally deprecated)
* Added maintenance option for SQLite integrity check.
=> (More) database maintenance

Jenkinsfile, Networking/TCPSocket.cc, REST/Listener.hh, REST/RESTListener.cc, REST/RESTListener.hh, REST/c4Listener+RESTFactory.cc, REST/c4Listener.cc, REST/c4ListenerInternal.hh, cmake/platform_apple.cmake, jenkins/jenkins_unix.sh
This allows RESTSyncListener to keep itself alive until the last replicator stops, avoiding a use-after-free crash.
(Requires litecore-EE branch `fix/refcount-listener`, [commit 98f310b5](https://github.com/couchbase/couchbase-lite-core-EE/commit/98f310b51f9540a3726fa153f37f3c3a1f8ad9af))
Fixes CBL-975
=> Ref-count C++ Listeners

C/tests/c4DatabaseTest.cc, LiteCore/Database/BackgroundDB.cc, LiteCore/Database/BackgroundDB.hh, LiteCore/Database/Housekeeper.cc, LiteCore/Support/Actor.cc
Each commit here is a separate fix, except the last which is a unit test.
* Fixed stack-corrupting bug in Actor (crashed in BackgroundDB::close) -- CBL-984.
* Fixed a crash in Housekeeper closing a database -- a simple null-pointer deref when the BackgroundDB has already been closed.
* Fixed deadlock in BackgroundDB -- I added a separate mutex for the transaction observers, to avoid a lock ordering problem -- CBL-980.
* Added "Database BackgroundDB torture test" -- a test that rapidly opens the database, creates a document with expiry, waits a short random interval, then closes the database and starts over. On my Mac this reproduced all three above bugs within a few seconds, but _only_ with AddressSanitizer turned off(!)
=> Fixed BackgroundDB and Housekeeper crashes

C/tests/c4DocumentTest.cc, LiteCore/Database/Document.hh, LiteCore/Database/TreeDocument.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh
Unnecessary stuff gets left behind after a conflict is resolved: the revision metadata of the conflict branch (up to about 1KB), and worse, the body of the losing revision (could be big!) I have a copy of a customer database that has about 4MB of unnecessary overhead due to this.
This PR has two commits:
1. Prunes the entire losing branch during a merge.
2. Makes sure older revisions on the surviving branch don't have the kKeepBody flag set, which keeps their bodies around.
I updated the "Document Conflict" unit test to check this. (Most of the source changes there are just to use constants for the revIDs instead of repeating the strings over and over.)
Fixes CBL-708
=> CBL-708: Don't leave obsolete revs behind after a merge

CMakeLists.txt, cmake/platform_apple.cmake
Note that this changes nothing (the option turn on by default),
and you need explicity set to to OFF to change behaviour before patch.
To reproduce problem you need old enough cmake (I used cmake 3.9.6 in CI builds).
This mainly to fix CI issue in my attempt to migrate to current master (Dushistov/couchbase-lite-rust#22), but I suppose it is not bad idea to have this options to make possible to have Debug build without huge memory consumptions caused by santizers.
Related part of my CI failure that this patch fix:
```
[couchbase-lite-core-sys 0.1.0]   "___asan_report_load1", referenced from:
[couchbase-lite-core-sys 0.1.0]       fleece::impl::Value::isUndefined() const in libFleeceStatic.a(Fleece.cc.o)
[couchbase-lite-core-sys 0.1.0]       fleece::impl::Value::isUnsigned() const in …
```
=> add ability to build debug build without -fsanitize on macos

C/c4.def, C/c4.exp, C/c4.gnu, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/scripts/c4.txt, C/scripts/c4_ee.txt, C/scripts/generate_export_list.py, C/tests/CMakeLists.txt, CMakeLists.txt, Replicator/c4Replicator.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, Xcode/xcconfigs/LiteCore-dylib.xcconfig, cmake/platform_apple.cmake, cmake/platform_linux.cmake, cmake/platform_win.cmake, jenkins/jenkins_ios.sh
.NET bindings need all symbols to be exported from a dynamic library.  This has the side effect of putting in some logic that is unused in CBL into the CE build, but to get around that there would have to be a lot of rewrites to the `c4listener` API to remove the unused HTTP REST mode.
=> Compile LiteCoreREST and LiteCoreWebsocket into shared lib

C/tests/c4DocumentTest.cc
final fix #978
plus small fix to make static analyzer happy: correct typo`val = val`
It is much more simple to fix in tests in compare to create suppression file for fsanitize=leak or valgrind,
which I plan to add to CI for my Rust wrapper around this project.
=> fix memory leak in c4db_findDocAncestors tests

C/include/c4Listener.h, REST/RESTListener.cc, REST/RESTListener.hh, REST/c4Listener.cc, REST/tests/RESTListenerTest.cc
The caller must now specify which API they are intending to get the server addresses for
=> [API] CBL-948: Make listener return correct scheme for server mode

Xcode/build_setup.sh, Xcode/xcconfigs/Project.xcconfig
* 32 bit build was failing due to mbedTLS missing arch.
* TestServer also requires 32 bit modules. 
* Plan for dropping 32-bit architecture, will be postponed.
=> CBL-933: 32 bit config for simulators

Crypto/Certificate.cc, Crypto/Certificate.hh, Crypto/PublicKey+Apple.mm, Crypto/PublicKey.cc, Networking/TLSContext.cc, Networking/TLSContext.hh, REST/tests/RESTClientTest.cc
iOS for some reason doesn't make the list of trusted root certs available to 3rd party apps. This means we can't give mbedTLS the list of roots, so it can't validate peer certificates.
However, mbedTLS _does_ have an API to register a callback that will be asked to find the root cert that signed a given peer cert, and we _can_ do that on iOS using SecTrust.
Includes tiny change to mbedTLS's config header to enable the function we need.
Includes addition to sockpp's mbedtls_context to provide a callback.
Fixes [CBL-995](https://issues.couchbase.com/browse/CBL-995)
=> Fix cert validation on iOS (CBL-995)

LiteCore/Database/TreeDocument.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, Networking/HTTP/HTTPTypes.hh, Replicator/Inserter.cc, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/ReplicatorTypes.cc, Replicator/ReplicatorTypes.hh, Replicator/RevFinder.cc, Replicator/Worker.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
Fixing CBL-986, manifested by transient failures of the "Continuous Push From Both Directions" unit test.
* RevToSend now preserves the order of its `ancestorRevIDs` so that
the peer's preferred rev can be used as the delta source. It used
to use a `set`, which sorts the revIDs, meaning that the _oldest_
one (lowest gen) would be tried first, which is bad!
* If c4doc_put can't reassemble the doc body because the delta source
revision isn't available, _and_ the operation would fail anyway
because it would create a conflict, then it now returns
kC4ErrorConflict instead of kC4ErrorDeltaBaseUnknown. That helps
the replicator & app handle the situation more appropriately.
* Added some more logging (mostly debug-level) to make it easier to
debug situations like this in the future.
* Inserter …
=> Fixed some delta-sync race conditions

Crypto/CertificateTest.cc, Crypto/PublicKey+Apple.mm
* If the cert is failed to update its label on MacOS, rollback by deleting the added cert.
* In “Persistent key and cert" and "Persistent save duplicate cert or id" test, delete cert label "Jane Doe" that causes the test failure on some machines.
=> CBL-1036 : Rollback when fail to update label to cert on MacOS

Replicator/Puller.cc, Replicator/Replicator.hh, Replicator/RevFinder.cc, Replicator/Worker.cc, Replicator/Worker.hh
Puller::updateLastSequence calls replicator(), which fails an assertion
if the parent link has already been cleared. It was clearly trying to
call the replicator only if it's still available; I fixed it to do
that, by adding replicatorIfAny() which is like replicator() without
the assertion.
This led me to notice that going up the `_parent` chain isn't thread-
safe, since your parent could clear its parent link at any moment on
its actor thread. So I'm now doing it in a safer way that grabs a
retained reference at each step, and ends up returning a retained
reference to the Replicator.
Fixes CBL-1043
=> Fixed race condition in Puller

Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
Blake discovered that c4repl_isDocumentPending calls the replicator's
validation callback while holding the replicator mutex, which can lead
to a deadlock if the callback calls something else that locks a mutex.
Fixed this by changing the implementation to lock the replicator,
grab the necessary state, unlock, then use the state to get the
results. It actually adds a little helper class encapsulating the
state, which seemed the cleanest way to do it.
=> Fixed potential deadlock in pending-docs API

Networking/WebSockets/WebSocketImpl.cc, Replicator/tests/ReplicatorAPITest.cc
If a stop is requested, just end the connection without waiting for the onConnect callback that might never happen.
=> CBL-988: Stop replicator immediately in connecting state

C/c4Base.cc, REST/tests/SyncListenerTest.cc, Replicator/Pusher.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/tests/ReplicatorAPITest.hh
Now if a listener is set up to not allow a certain replication mode (push or pull), an attempt to exercise that path will result in a 403 error and replication termination.  The following things needed to happen to achieve that goal:
1. Instead of returning `websocket::kCodeUnexpectedCondition` for every error that can stop the replication (regardless or whether it is fatal or not), return `websocket::kCloseAppPermanent` if it is fatal (to avoid retrying) and `websocket::kCloseAppTransient` if the library should retry (for example, in the case of 503, which stops replication to back off and try later)
2. Modify an assert in ReplicatorAPITest that checks that an error never happens during a busy state
3. Call doneWithRev on all currently processing revs so if an error BLIP message is …
=> CBL-954: Return 403 and stop for readonly violation

C/include/c4Listener.h, Networking/NetworkInterfaces.cc, REST/Server.cc, REST/tests/SyncListenerTest.cc
During this process I also uncovered that specifying an IPv6 address to bind to was essentially a no-op because only IPv4 "any" addresses were being considered.  The P2P Server Addresses test was added to make sure this does not regress.  The main fix here is to use inet6_address in our Server class whenever possible since it also handles IPv4 socket operations.  This was added in the following locations
- When no network interface is specified, an inet6_address instance should be created instead of inet_address
- When looking at the acceptor address to determine if the address is not constrained, the family of the socket needs to be considered
Note: The inspection of the "any" IPv6 address is a bit hacky, but the alternative is about 5 different ifdef due to the lack of consistency in …
=> CBL-1008: Fix IPv6 addresses being reported, but not connectable

C/c4Certificate.cc, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Certificate.h, C/scripts/c4_ee.txt, Crypto/PublicKey.cc, Crypto/PublicKey.hh
Support for externally-stored keys, to allow integration with the platform's secure key storage mechanism (e.g. the iOS Keychain.)
=> API: Added c4keypair_fromExternal()

Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
This manifests in a very hard to hit situation where a replicator cannot connect to the other side because of a transient error, but since it has already switched to offline it has no connection to close and so the call to stop has no effect other than to change the status to stopping.  This needs to be detected in the status changed callback and the offline handling should be skipped.
=> CBL-1054: Don't do offline handling after c4repl_stop

C/include/c4Replicator.h, Networking/TCPSocket.cc, Networking/TLSContext.cc, Networking/TLSContext.hh, Networking/WebSockets/BuiltInWebSocket.cc, REST/tests/SyncListenerTest.cc, Replicator/tests/ReplicatorAPITest.hh
This needs to live in harmony with the other modes, and furthermore it needs to disrupt normal processing by ignoring the normal CA validation.  Only self signed certificates will be accepted.  The motivation for this is due to our commitment to make an insecure mode as difficult to achieve as possible.  If this were simply a mode to allow self signed certificates in addition to valid ones, then this could easily be overlooked and put into production thereby making a product using the library easily attackable.  On the other side, many P2P implementations will have dynamically generated self signed certificates floating around and those should work by default if that mode is desired.  So the basic thinking is that in P2P the self signed mode will be used, and with non-P2P the normal mode …
=> CBL-1044 Add self-signed validation mode

LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/DataFileTest.cc
Just discovered this problem while testing some new code for CBL-C, where I've refactored the Checkpointer class a bit.
1. Start with a new database
2. Try to save a peer checkpoint with a mismatched revID (i.e. any non-null revID.) This will, as expected, fail with a revision-conflict error.
3. Now try to save a valid peer checkpoint — this will incorrectly fail with the SQLite no-such-table error.
The bug: If a new KeyStore is created in a transaction, and then the transaction aborts, the KeyStore object still exists but its SQLite table doesn't. From then on, using that KeyStore will throw a SQLite no-such-table error, until the database is closed and reopened.
I fixed this by having SQLiteKeyStore keep track of whether its table is still uncommitted. If so, and it's notified that the …
=> Handle KeyStore creation in an aborted transaction

C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Replicator.h, C/scripts/c4_ee.txt, C/tests/c4Test.cc, C/tests/c4Test.hh, C/tests/c4ThreadingTest.cc, Networking/BLIP/BLIPConnection.cc, Networking/BLIP/BLIPConnection.hh, Networking/BLIP/CMakeLists.txt, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/BuiltInWebSocket.hh, Networking/WebSockets/WebSocketInterface.hh, REST/tests/SyncListenerTest.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.hh
This is a simple action to desire, but it needs to break through about 7 or so layers of indirection and decoupling in order to get there, so the PR is pretty massive.  The certificate is discarded very quickly in a failed handshake scenario and so the following needs to happen:
1. mbedtls_context needs to remember the certificate it received
2. mbedtls_socket needs to consult mbedtls_context if it can't get the peer certificate via the normal route of asking mbedTLS
3. BuiltInWebSocket needs to cache the certificate after it sends an HTTP request so that the certificate is not lost because the socket is not kept around if it fails to open
4. BLIPIO needs to to cache the certificate when the connection closes because otherwise it is lost when the mbedtls_socket is nulled
5. BLIPConnection …
=> Create the long and arduous path to extracting a peer certificate

LiteCore/Database/Database.cc, LiteCore/Database/TreeDocument.cc
There are two steps involved in this.  Ignoring conflicted documents is easy enough but then there is a potential that they are ignored later because the resolution process does not create any new sequences (i.e. the remote revision is accepted as-is).  So the documentSaved method needs to be "delayed" by both ignoring it for conflicts, and then calling it when certain conditions are met in the resolve conflict method.
=> CBL-1089: Pusher should ignore conflicted documents

C/c4Certificate.cc
* The estimated DER data size is about 38 bytes longer than key lenth instead of 14 bytes. This has been verified from the public key in DER format created by Java’s KeyGenerator and OpenSSL.
* Fixed publicKeyRawData() that returns DER instead of RAW data.
=> Fixed problems when getting public key data in ExternalKeyPair

Xcode/build_mbedtls.sh
During `xcodebuild archive` the TARGET_BUILD_DIR was not pointing to the products directory. 
For example,  while *archiving*
```
TARGET_BUILD_DIR=xxx/DerivedData/CouchbaseLite-xxx/Build/Intermediates.noindex/ArchiveIntermediates/CBL_EE_Swift/InstallationBuildProductsLocation/
BUILT_PRODUCTS_DIR=xxx/DerivedData/CouchbaseLite-xxx/Build/Intermediates.noindex/ArchiveIntermediates/CBL_EE_Swift/BuildProductsPath/Release_EE-iphoneos
```
In this case, copying mbedtls to the TARGET_BUILD_DIR is causing the linker failed to link, resulting in "ld: library not found for -lmbedtls"
But `xcodebuild build` the TARGET_BUILD_DIR and BUILT_PRODUCTS_DIR are same, so there is no issue with current build process.
```
TARGET_BUILD_DIR=xxx/DerivedData/CouchbaseLite-xxx/Build/Products/Release_EE-iphoneos …
```
=> CBL-1139: xcodebuild archive failure

Networking/BLIP/BLIPConnection.cc, Networking/BLIP/BLIPConnection.hh, Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/BuiltInWebSocket.hh, Networking/WebSockets/WebSocketInterface.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.hh
By pushing it instead of pulling it, we avoid thread-safety issues and simplify the code.
This reworks the implementation from 0da7c9acef06ba7a5dca5a56cf6676b7806b5e01 (#1022)
Fixes CBL-1125
=> Changed how peer cert is passed up to c4Replicator

Replicator/DBAccess.cc, Replicator/DBAccess.hh
The Thread Sanitizer warned about a data race accessing `DBAccess::_tempSharedKeys`. There's already a mutex for this, so I'm not sure why I didn't use it in this case; maybe a stupid attempt to save a few clock cycles. ¯\_(ツ)_/¯
=> Fixed thread-safety issue in DBAccess::_tempSharedKeys

cmake/platform_android.cmake
Otherwise, it doesn't seem able to handle file operations on already unlinked files (such as index sorts that exceed the memory limit)
=> CBL-1141: Defer SQLite temporary file unlinking for Android

Replicator/Replicator.cc
* add a debug line log which can be useful when getting confused why state is busy while connection already got signal to close.
* close PR, if feels like its noisy
=> debug log when connection closing, and state is busy

C/c4.def, C/c4.exp, C/c4.gnu, C/c4DocExpiration.cc, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Database.h, C/scripts/c4.txt, C/tests/c4DatabaseTest.cc, LiteCore/Storage/DataFile+Shared.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteEnumerator.cc, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh
For use by CBL-C so it can determine whether or not to call c4db_startHousekeeping when a DB opens.
(If it doesn't call it, we avoid opening a second db connection and starting a background thread.)
=> API: Added c4db_mayHaveExpiration

Replicator/Checkpoint.hh, Replicator/Checkpointer.cc, Replicator/Checkpointer.hh, Replicator/Replicator.cc, Replicator/Replicator.hh
The code to get/set peer checkpoints was buried inside `Replicator`'s BLIP message handlers. I extracted it into new methods on `Checkpointer`. This is cleaner, and allows that functionality to be used by new replicator implementations.
=> Moved get/save peer checkpoint code to Checkpointer

LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc
If an encoder is being used, go through the encoder to get the file position rather than querying the underlying file directly
=> CBL-1045: Plug a data race in the dylog method

Networking/TLSContext.cc
This is not a useful feature when validating certificates after being received, since having a CA list in the beginning prevents the certificates from ever being sent unless they are issued by one of the approved issuers
=> Activate mode to stop mbedTLS from sending CA list to client

LiteCore/Support/LogEncoder.cc
The LogEncoder destructor holds a mutex, and then deletes its flush timer.  If the timer has been triggered but not yet fired in this case a deadlock will occur because the destructor is waiting for the timer callback to complete, but the timer callback is waiting for the mutex that the destructor is holding.  It is safe to delete the timer before acquiring the mutex because usually all that happens is that the timer removes itself from scheduling.  The actual flush operation, however, still needs to be guarded since it uses shared objects.
=> Fix a deadlock that was revealed in the LogEncoder

Replicator/Puller.cc, Replicator/Puller.hh
If too many revision build up in the replicator, there is a path where they remain in the backpressure list without ever getting triggered to move to the active incoming list.  This means that the replicator will never think it is finished because it is missing 100 or so messages.
=> CBL-1112: Port backpressure hotfix to master

Networking/WebSockets/WebSocketImpl.cc
Fixes a regression in the logic of calling stop during the connecting phase that doesn't inform the replicator of the web socket's connection being fully closed which results in it never reaching the stopped state
=> CBL-1088: Make sure onClose is called after stop while connecting

LiteCore/Query/QueryParser.cc, LiteCore/tests/N1QLParserTest.cc
A test on a property path was missing a range test, so it blew up with an empty path.
(Originally reported as https://github.com/couchbaselabs/couchbase-lite-C/issues/54, with the trivial N1QL query `SELECT * FROM db`.)
Fixes [CBL-1191](https://issues.couchbase.com/browse/CBL-1191)
=> Fixed assertion failure parsing {'FROM':[{'AS':'db'}],'WHAT':[['.']]}

LiteCore/Database/SequenceTracker.cc, LiteCore/Database/TreeDocument.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, Replicator/tests/ReplicatorLoopbackTest.cc
If a conflict is resolved by using the already existing revision, due to a previous fix it gets added to the sequence tracker after it is resolved which means it might not be the newest sequence in the database.
=> CBL-1174: Correct regression when dealing with conflicts and SequenceTracker

Replicator/IncomingRev.cc, Replicator/Puller.cc, Replicator/Puller.hh, Replicator/Pusher.cc, Replicator/Pusher.hh
When a delta failure happens, the error response triggers the revision to be sent again as a full revision, but without going through the changes message first.  The changes message both adds progress and also adds pending rev message count that is balanced when the revision is received, and so needs to be re-added as part of the revision re-request.
=> CBL-936: Make sure Puller's counters react to a failed delta

Crypto/Certificate.cc
This is in order to accommodate the more modern and recommended diffie hellman ephemeral algorithm suites
=> CBL-1165: Add digital signature to default key usage of server

Replicator/Replicator.cc
And kWebSocketCloseAppTransient.  These are basically used to close the connection in the face of an underlying error, and that underlying error should be the one that persists in the consumer visible status.
=> CBL-1178: Suppress the recording of kWebSocketCloseAppPermanent

C/include/c4.hh
Otherwise, the following can go wrong as a result.  Given a vector of c4ref objects that is 2 or more long:
1. Call erase on any position in the array except the last
2. As the vector moves its contents around, it will overwrite the contents of the index being erased with the element that follows it
3. Since the move assignment operator does not release its object, this means it will leak a release when this happens and the object itself will leak
=> CBL-1033: c4::ref move assignment operator must release existing object

Networking/HTTP/HTTPLogic.cc
Changed header comparison from case sensitive to case insensitive,
according to https://tools.ietf.org/html/rfc7230#section-6.1 .
More details: https://github.com/couchbaselabs/couchbase-lite-C/issues/63
=> Fix header comparison casing

C/c4Base.cc, REST/RESTListener.hh, REST/tests/ListenerHarness.hh, REST/tests/SyncListenerTest.cc
Note, this requires removing web socket 1001 from the list of transient error codes because that is the code that is given when the other side closes the connection
=> CBL-1243: Freeing listener should stop running replicators

C/include/c4.hh
For convenience, add in null pointer assignment to allow _ref = nullptr, and keep the constructor so that assigning / reassigning a pointer to a ref means that a new ref is created and no ref is accidentally over released unless it was not retained to begin with
=> Remove raw pointer assignment to ref

modules/docs/pages/replication-protocol.adoc
This was somehow lost when this doc was moved from the Wiki:
https://github.com/couchbase/couchbase-lite-core/wiki/Replication-Protocol/_compare/17c1a008398ea84a28a6e4a8880b05df442d0556...947acd66e4c399e0a6645a67b466ef7e30c68b8c
=> Replication Protocol Doc: Restore noconflicts property for rev message

LiteCore/Query/SQLiteQuery.cc, LiteCore/tests/FTSTest.cc
FTS queries have some metadata columns in front, but it mistakenly writes in the missing columns as the raw column index, instead of the column index starting at the first user requested value
=> CBL-977: Skip "hidden" columns when calculating missing columns

C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/SQLiteFleeceEach.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/SQLiteFunctionsTest.cc
When used on a nested array/dict inside an array/dict, `fl_each` is called with Fleece data, not a `body` column value (which is a serialized RevTree.) This breaks the way it tries to access the Fleece.
Fixed this by taking advantage of the fact that the body-column case always also passes a 2nd parameter (the property path), so it can use the presence of that to tell how to interpret the data.
Fixes CBL-1248
=> Fix crash using nested ANY/EVERY

Crypto/PublicKey.hh, Replicator/Puller.cc, Replicator/Pusher.cc, Replicator/ReplicatorTuning.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/c4Replicator.hh, Xcode/LiteCore.xcodeproj/project.pbxproj, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/All.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore C Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore C++ Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore XCTests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore dylib.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore framework.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C Tests Optimized.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C++ Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-iOS Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-iOS-Carthage.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-iOS.xcscheme, Xcode/build_setup.sh
Cherry-picked from the dev branch
* Fixed warnings about redefined PERSISTENT_PRIVATE_KEY_AVAILABLE
* Avoid premature destruction of C4Replicator  
* Fixed two replicator regressions  
* Xcode 12: Turned off upgrade warnings  
* Fixed mbedTLS build for Xcode 12 GM release  
* Updated Fleece, for Catch macos-arm64 compatibility
=> Misc fixes

C/tests/c4DatabaseTest.cc, LiteCore/Database/Database.cc, LiteCore/Database/Database.hh
BEHAVIORAL CHANGE
LiteCore will now reject documents which explicitly contain any of the following keys at the top level: _id, _rev, _deleted
@snej I'm unsure how much of this logic is useful outside of debug mode, so if I left in more than is needed let me know.
=> CBL-862: Reject invalid top level keys

C/tests/cmake/platform_linux.cmake, Jenkinsfile, LiteCore/tests/CMakeLists.txt, LiteCore/tests/cmake/platform_linux.cmake
Without these changes the build will fail on CentOS 6 because the `clock_gettime` function used by CivetWeb will not be found.
=> Switch to gcc for future 2.7.x builds

C/c4.def, C/c4.exp, C/c4.gnu, C/c4Internal.hh, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Replicator.h, C/scripts/c4.txt, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.cc, Replicator/Puller.hh, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/ReplicatorOptions.hh, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/c4Replicator.cc, Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
[API CHANGE] Addition of c4repl_setProgressLevel in c4Replicator.h
This change has to work its way through the various actors involved:  C4Replicator -> Replicator -> Pusher / Puller
The old method will still continue to function for the time being, but will be removed before 3.0.  It emits a warning to the logs when it is used now.
=> CBL-1232: Allow progress level to be set after replicator start

Replicator/c4Replicator.hh
If adding a new internal status, it will need to be handled here as well.
=> CBL-1513: Don't leak internal stopping status

C/Doxyfile, C/c4Certificate.cc, C/c4Database.cc, C/c4Document.cc, C/c4Private.h, C/c4Query.cc, C/include/c4Base.h, C/include/c4BlobStore.h, C/include/c4Certificate.h, C/include/c4Compat.h, C/include/c4Database.h, C/include/c4DocEnumerator.h, C/include/c4Document+Fleece.h, C/include/c4Document.h, C/include/c4Index.h, C/include/c4Listener.h, C/include/c4Observer.h, C/include/c4PredictiveQuery.h, C/include/c4Query.h, C/include/c4Replicator.h, C/include/c4Socket.h, C/include/c4Transaction.hh, C/tests/CoreMLPredictiveModel.hh, C/tests/c4DatabaseInternalTest.cc, LiteCore/tests/c4BaseTest.cc, REST/c4Listener.cc, Replicator/c4Replicator.cc, Replicator/tests/ReplicatorAPITest.cc
Now using Clang's `_Nullable` annotation, along with the pragmas
`clang assume_nonnull begin` and `clang assume_nonnull end`. This is
the same mechanism used in Objective-C APIs. Its advantage over
`__attribute((nonnull))` is that it does not imply that passing null
is undefined behavior, so it doesn't affect code optimization in ways
that make it impossible to add an explicit null check inside the
function.
Because of this way this stuff works, the headers now explicitly tag
_nullable_ pointers, instead of ones that cannot be null.
Pointer fields in structs also cannot be NULL except when tagged as
nullable.
This stuff is wrapped in macros, defined in c4Compat.h, for compatibility: in between
C4_ASSUME_NONNULL_BEGIN and C4_ASSUME_NONNULL_END, all pointer
declarations *implicitly* …
=> Improved nullability annotations in C API

Crypto/PublicKey+Apple.mm, LiteCore/Support/Instrumentation.cc, Xcode/build_mbedtls.sh, Xcode/xcconfigs/Project.xcconfig
* fix deprecation warnings
* rootsdk = iphoneos
* mbedTLS flags passed in to set target for catalyst
* changed os log since the kdebugLog was deprecated. Created LiteCore os_log_t
* mbedTLS build type corrected to use `MinSizeRel`
=> make catalyst compatible

LiteCore/tests/c4BaseTest.cc, Replicator/Checkpointer.cc, Replicator/Checkpointer.hh, Replicator/URLTransformer.cc, Replicator/URLTransformer.hh, Xcode/LiteCore.xcodeproj/project.pbxproj, cmake/platform_base.cmake
Some platforms were passing in an explicit port, even for default 80/443, while others were just leaving it blank. This led to discrepencies between the platform checkpoints, as a remote URL is used for calculating a replication checkpoint.  If a preloaded database is used on a platform that differs in this manner, then the previous checkpoint will fail to be detected.  This commit solves this by checking for both variations during the previous checkpoint search.
=> CBL-1515: Aggregate the platform variations of URL for Checkpoint

Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
Do it properly!  I.e. don't use memset since the compiler can optimize it out.  This unfortunately means a bit more spaghetti but not much.
=> CBL-1049: Zero sensitive options on C4Replicator destruction

C/tests/c4QueryTest.cc, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/N1QLParserTest.cc
This requirement interferes with the current grammar for COLLATE suffix. Currently, COLLATE may lead multiple collation names. After the change, one may put multiple collation names inside parenthesis. The parenthesis may be omitted if it encloses only one collation name.
=> Make "AS" optional to lead the aliases for the column names. #CBL-1523

LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/Query/SQLiteFleeceUtil.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc
Before some of them remained integers which could be interpreted as boolean results, but now all functions and operators which are logically thought of as boolean will return true or false instead of 0 or 1.
=> CBL-49: Fully support booleans in queries

LiteCore/Query/QueryParser.cc, LiteCore/tests/QueryTest.cc
Path::Path(string) unquotes char[]{'\\', '$'} and stores '$'. Path::operator string() does the reverse: escapes '$' back slash. However, the escape here is only understood by QueryParser, but the audience that QueryParser produces is SQL.
=> Fixing a quoting error. CBL-1635

Crypto/PublicKey+Apple.mm, Crypto/PublicKey+Windows.cc, Crypto/PublicKey.cc, LiteCore/Database/Database+Upgrade.cc, LiteCore/Database/Housekeeper.cc, LiteCore/Database/TreeDocument.cc, LiteCore/Query/SQLitePredictionFunction.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/Storage/RecordEnumerator.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteEnumerator.cc, LiteCore/Support/Logging.hh, LiteCore/Support/ThreadedMailbox.cc, Networking/Poller.cc, Networking/TCPSocket.cc, Replicator/Checkpoint.cc, Replicator/Worker.cc
Add in LogError and LogWarn alongside LogTo, LogVerbose, and LogDebug.  Declare LogDebug inline instead of conditionally stripping it later.  Convert all LogToAt to one of the previous, to avoid accidentally logging debug in the future.
=> CBL-1660: Make sure all debug logging is not present in release

C/tests/c4DocumentTest.cc, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/VersionVector.cc, LiteCore/RevTrees/VersionVector.hh, Replicator/tests/ReplicatorLoopbackTest.cc
If the remote version wins, and there's no new merged body, then in
most circumstances we should just copy the remote version to local
without changing its vector.
This also adds more test cases in c4DocumentTest, because this
situation wasn't being tested before (all the tests involved a merged
body.)
CBL-1715
=> VV conflict resolution improvements when remote wins (CBL-1715)

C/tests/c4DocumentTest.cc, LiteCore/RevTrees/VectorRecord.cc
In VectorRecord::updateDocFlags, minus kDeleted from the current doc’s flag before applying with the new flags.
=> Fix kDeleted is carried forward to the new rev when using version vector

Networking/Poller.cc
If a socket has the `POLLNVAL` flag, it means that it is not valid for doing anything with and therefore no reads or writes should be attempted on it.  This is in contrast to `POLLHUP` which means that the socket is valid, but is no longer performing new reads and/or writes (but could still return values for remaining unprocessed ones)
=> CBL-1722: Don't call handlers on invalid socket

C/include/c4.hh, C/tests/c4DatabaseTest.cc, C/tests/c4QueryTest.cc, C/tests/c4Test.cc, C/tests/c4ThreadingTest.cc, Crypto/CertificateTest.cc, LiteCore/Database/LiveQuerier.cc, LiteCore/Storage/DataFile.cc, LiteCore/Support/TestsCommon.cc, LiteCore/Support/TestsCommon.hh, LiteCore/Support/Timer.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/LogEncoderTest.cc, Networking/WebSockets/WebSocketImpl.cc, REST/tests/SyncListenerTest.cc, Replicator/IncomingRev+Blobs.cc, Replicator/Pusher+Attachments.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
I recommend reviewing the two commits below separately. The second one has no actual effect on the code, it's just syntactic sugar.
Some tests are using delays to wait for events to occur, and either
the delay is too short to be reliable or it's too long and slows down
the test. Instead we should use loops with reasonably long timeouts
that exit as soon as the event occurs.
* I changed the relatively new `WaitUntil` function so it doesn't
itself trigger test failure, just returns a boolean.
* Added CHECK_BEFORE() and REQUIRE_BEFORE() macros that act like
CHECK and REQUIRE, for boolean conditions, but also take a maximum
time interval to wait for the condition to become true.
* Updated tests that were using their own `this_thread::sleep_for`
calls, to use these new tools instead.
With free …
=> More-reliable poll-waits in tests: CHECK_BEFORE(), etc. 

C/c4.def, C/c4.exp, C/c4.gnu, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/scripts/c4.txt, C/tests/c4DocumentTest.cc, LiteCore/Database/VectorDocument.cc, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C Tests.xcscheme
The bug is that the function would crash (throw an exception out of a noexcept method) if the doc's body wasn't loaded; but only in a version-vector doc. The unit test made this happen.
=> Export c4doc_getRevisionBody(), and fix bug therein

C/include/c4Compat.h
clang has changed its way of doing compilation and no longer allows the previous usage of C4_ENUM, so update the definition to match what Apple did since that is what the implementation is based on.
=> CBL-1749: Redo C4_ENUM and C4_OPTIONS

C/c4Database.cc, C/tests/c4DatabaseTest.cc
c4db_openNamed, c4db_exists, c4db_deleteNamed would crash with an uncaught C++ exception if the input database name or parentDirectory were a NULL slice. That's because the dbPath() subroutine would fail an assertion, and so throw an exception, but the call to dbPath() was not inside a try/catch block. Fixed.
=> Fixed uncaught-exception crash in c4db_openNamed etc.

LiteCore/Query/QueryParser.hh, LiteCore/Query/QueryParserTables.hh
* Used `using` to get rid of the large number of namespace prefixes
* Realigned comments & inline bodies
* Removed now-unnecessary `_sl` suffixes on slice literals
* `const` -> `constexpr` where it makes sense
* Added some comments
Should not affect the compiled code; this is just for readability.
=> No-op cleanup of QueryParser headers

LiteCore/Support/Error.cc
Then keep the error object as it is, so that any custom message is not lost
=> CBL-1770: If a call to standardized doesn't change code or domain

Replicator/c4Replicator.hh, Replicator/tests/ReplicatorAPITest.cc
Otherwise it will mistakenly override an explicitly set value via c4repl_setProgressLevel
=> CBL-1723: Only change progress level via options if explicitly set

C/c4Certificate.cc
Fixed issue that the persistent key's functions are not available on all platforms. Ensured to guard with PERSISTENT_PRIVATE_KEY_AVAILABLE.
=> Add missing PERSISTENT_PRIVATE_KEY_AVAILABLE guard

C/tests/c4QueryTest.cc, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/LogEncoderTest.cc, LiteCore/tests/QueryTest.cc
1. Functions propagate MISSING and NULL: functions return MISSING if any argument is MISSING, otherwise they return NULL if any argument is NULL.
2. Functions return NULL if any argument is out of the domain, instead of emitting error. "lower([1,2])," for example, returns NULL instead of erring out the query process.
3. Removed "regex" from reserved words.
4. Division operator, "/", performs floating number division even if both operands are integers.
5. The column title of array path, such as "orderLines[0]" becomes "$n", instead of "*".
=> Handle miscellaneous edge cases. #CBL-1840

LiteCore/Query/QueryParser+Prediction.cc, LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/SQLiteKeyStore+Indexes.cc, LiteCore/tests/QueryParserTest.cc
Defines a simple `quotedSlice` wrapper class around `slice`, which has a `<<` overload to write itself to an `ostream` in quoted form, using `std::quoted` (which I just discovered!) to do the actual string quoting/escaping.
This is used by some new functions
- `sqlString()` writes a SQL string literal, including the single-quotes of course
- `sqlIdentifier()` writes a SQL identifier, which will be wrapped in double-quotes only if it's not alphanumeric.
- `quotedIdentifierString()` is like `sqlIdentifier()`, except it returns a string instead of writing to a stream.
=> Cleaned up string/identifier quoting in QueryParser

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc
DIV(x, y)  = (double)x / (double)y,
IDIV(x, y) = (int64_t)x / (int64_t)y
We now translate traditional "/" to the new function DIV, so "select 2/0" no longer return MISSING, instead of NULL, because we are taking control of return.
=> Add two functions to n1ql, DIV, IDIV, #CBL-1858

C/c4Certificate.cc, REST/CMakeLists.txt
Otherwise consuming libraries have an implicit dependency on LiteCoreREST that goes unrealized.
=> Only add cert request support if asked for

C/c4Certificate.cc, LiteCore/Support/access_lock.hh
There is a bug in the MSVC 15.x compiler that Microsoft will not fix that prevents the use of guaranteed copy elision with deleted move constructors in some cases.  Use a workaround until upgrade to 16.x.
=> Fix MSVC build issue regarding copy elision

Networking/BLIP/cmake/platform_android.cmake, Networking/BLIP/cmake/platform_linux.cmake, Networking/BLIP/cmake/platform_win.cmake
For platforms that build it statically.  Otherwise grandchild dependents of BLIPStatic (e.g. Couchbase Lite C) will get linked in the wrong order on platforms that cannot reason about libraries that don't come in strict linear order (GNU...)
=> Add in zlib dependency for BLIP

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/QueryTest.cc
In 732eeef0ad9b5a8a, we changed it to DIV(), which is handled by our code and does floating number division. This commit reverts the change of 732eeef0ad9b5a8a with regard to '/'.
=> The division operator, '/', in N1QL is given to SQLite3 to handle.

C/include/c4Replicator.h, Replicator/c4RemoteReplicator.hh, Replicator/tests/ReplicatorAPITest.cc
Added two replicator options,
kC4ReplicatorOptionMaxAttempts        "maxAttempts" ///< Max number of attempts (int)
kC4ReplicatorOptionMaxAttemptWaitTime "maxAttemptWaitTime" ///< Max delay betw attempts (secs)
They will replace "maxRetries" and "maxRetryInterval", respectively. maxAttempts == maxRetries + 1.
=> maxAttempts, maxAttemptWaitTime. CBL-1941, CBL-1944, CBL-1943.

Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
The test expects there to be an error pushing its one document.
Most of the time there is, but if the two replicators interleave
their changes, the test can finish with no conflicts. For whatever
reason this has become more likely of late -- I like to think it's
because of my replicator and CRUD optimizations, but who knows.
This patch adds a new boolean flag to ReplicatorLoopbackTest that,
when set, makes it OK for there to be no document errors even if
the expected-errors sets are non-empty. This flag is set in the one
test that exhibits this problem.
=> Fix flaky "Continuous Push From Both Sides" test

Networking/BLIP/MessageOut.cc, Networking/BLIP/MessageOut.hh
With Debug logging, BLIPIO calls description() on ACK messages,
causing an exception when MessageOut::description() tried to read the
properties of an ACK message, which doesn't have any.
The fix is not to call _contents.getPropsAndBody() when the message's
type() is an ACK. To make this safer, I wrapped the call in a method
on MessageOut itself.
And to clean up a little technical debt, I changed the calling style
to return the two slices as a pair instead of as 'out' params.
The Fleece update is to fix a bug in slice_input that I discovered
while investigating, but which isn't actually triggered here.
Fixes CBL-2018
=> Fixed exception when BLIP logging set to Debug (CBL-2018)

C/Cpp_include/c4Document.hh, C/c4Document.cc, C/tests/c4DocumentTest.cc, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/RevTrees/VectorRecord.cc, LiteCore/RevTrees/VectorRecord.hh
Having c4doc_update return the same C4Document instance was a bad
idea:
* If the save failed, the document was left with the new revision
inserted.
* It didn't match the platform code's expectations that changes to the
original doc affected the new one.
To restore the original semantics I had to make a copy of the
C4Document object, and add the new revision to that and save it.
I also marked update() as `const` to enforce that it can't change the
document state.
=> Restore old semantics of c4doc_update (returns copy)

C/tests/c4ObserverTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, Replicator/tests/ReplicatorLoopbackTest.hh
For all test cases in c4Test and ReplicatorLoopbackTest, each test case is duplicated for RevTree and VersionVector. Since VersionVector is not the release focus for now, we skip them for now. Following are the time differences on my Mac,
c++ tests: 303s vs 510s, and
c   tests: 106s vs 161s.
=> Skip the duplicated version vector tests. #CBL-2000

Networking/HTTP/HTTPLogic.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4RemoteReplicator.hh
* To support both SG v2.x (use protocol BLIP3+CBMobile_2) and v3.0 (use protocol BLIP3+CBMobile_3), the replicator v3.0 will list both protocol versions in the "Sec-WebSocket-Protocol" request header using a command separated string format starting with the preferred protocol which is BLIP3+CBMobile_3.
* Replaced a constant kReplicatorProtocolName string with two static functions CompatibleProtocols() and ProtocolName(). The CompatibleProtocols() function is used by RESTSyncListener in EE repo to get a list of all supported protocols for accepting the proposed protocols by the replicator (client).
* Adjusted the logic in HTTPLogic and c4RemoteReplicator to support multiple protocols.
=> CBL-2019 : Support replication protocol version 2 and 3

C/tests/c4DocumentTest.cc, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc
When a C4Document is initially loaded without its rev-tree, and the
tree needs to be loaded later, the error handling needed to be
improved. In some cases TreeDocument was just ignoring the failure to
load the rev-tree.
=> Better handling of document change/purge when loading revs

LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/tests/FTSTest.cc
So `"FROM":[{"AS":"testdb"}],"WHERE":["MATCH()", "sentence", "words"]` is now legal again ... a regression had made it require `"testdb.sentence"`.
I improved QueryParser::FTSTableName to parse the FTS index name with the same logic as for regular property accesses, so it uses the same rules for when a DB alias is needed.
=> Fixed: 1st param of MATCH() doesn't need a db alias

C/tests/c4QueryTest.cc, LiteCore/Database/BackgroundDB.cc, LiteCore/Database/BackgroundDB.hh, LiteCore/Database/DatabaseImpl.hh, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/LiteCoreTest.cc, LiteCore/tests/LiteCoreTest.hh, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryParserTest.hh, LiteCore/tests/QueryTest.cc, LiteCore/tests/SQLiteFunctionsTest.cc
As per our meeting yesterday (6/17/21). To be precise:
* In JSON, this applies to the value of `SELECT.FROM.COLLECTION`.
* In N1QL, this applies to the name after `FROM` (which translates to the above.)
* `_` is now a synonym for `_default`, i.e. the default collection
* The database name is also a synonym for `_default`, _unless_ there is a collection with that name, in which case it refers to that collection.
- The logic above is added to `SQLiteDataFile::collectionTableName()`. 
- However, that class doesn't know the database name, only the path to the `db.sqlite3` file, so
- I added a `databaseName()` method to the `DataFile::Delegate` protocol.
- This is implemented primarily by `DatabaseImpl`, but also by `BackgroundDB` and `DataFileTestFixture`.
- The rest is unit tests.
=> In query allow "_" or db name as synonym for "_default"

C/tests/c4DocumentTest.cc, LiteCore/RevTrees/VectorRecord.cc, LiteCore/Storage/Record.hh
When a C4Document is loaded without its 'extra', and then a later
call causes 'extra' to be loaded, the KeyStore updates all the fields
of the Record including the 'body', swapping it out with a new
alloc_slice with the same data.
This means that after this call, the document's old body as used by
clients is no longer valid, causing nasty errors.
This commit changes Record's setters to ignore a change to 'body' or
'extra' that leaves the data the same.
=> Reading doc extra shouldn't replace body

C/c4.def, C/c4.exp, C/c4.gnu, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Base.h, C/scripts/c4.txt, Replicator/c4Socket.cc, Replicator/tests/ReplicatorAPITest.cc
Make platform code's life easier by giving it control over the lifecycle of a C4Socket instance.
Both these calls are fully thread-safe. (The only action other than refcount-bumping is freeing the C4SocketImpl, but if that happens, then by definition nothing else has a reference to that object, so it won't perturb other code.)
For CBSE-10309
=> API: Added c4socket_retain, c4socket_release [2.8.6]

C/c4.def, C/c4.exp, C/c4.gnu, C/c4_ee.def, C/c4_ee.exp, C/c4_ee.gnu, C/include/c4Base.h, C/scripts/c4.txt, Replicator/c4Replicator_CAPI.cc, Replicator/tests/ReplicatorAPITest.cc
Make platform code's life easier by giving it control over the
lifecycle of a C4Socket instance.
Both these calls are fully thread-safe.
=> API: Added c4socket_retain, c4socket_release [CBL-2120] (#1202)

LiteCore/Database/TreeDocument.cc
TreeDocument’s purgeRevision(revID) is called by the resolveConflict() function to purge the losing revision. The purgeRevision(revID) function calls updateFlags() which may release the given revID if the given revID is the same as the current _revID.
This commit prevents the use of the already released revID from updateFlags() by moving the code that checks for isSelectedRevID above the updateFlags().
CBL-2160
=> Fix using already released revID slice in TreeDocument’s purgeRevision()

C/c4BlobStore.cc, C/c4Database.cc, LiteCore/Database/DatabaseImpl.cc, LiteCore/Database/DatabaseImpl.hh
GCC 7 and 9 are fine but 8 results in ambiguous constructors when constructing an alloc slice from a file path
=> Fix weird GCC 8 issue with constructors

LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc
Implicit conversion from FLSliceResult rvalue to alloc_slice was calling the
wrong constructor and not releasing the FLSliceResult, causing leaks.
(See the Fleece commit for details.)
The fix required minor changes to two places in LiteCore that converted an
FLSliceResult _lvalue_ to an alloc_slice; this now has to be done explicitly.
Fleece PR: couchbaselabs/fleece#106
=> Updated Fleece to fix leaky FLSliceResult -> alloc_slice conversions

C/Cpp_include/c4BlobStore.hh, C/Cpp_include/c4Document.hh, C/c4BlobStore.cc, C/include/c4Document+Fleece.h, C/include/c4ReplicatorTypes.h, Replicator/DBAccess.cc, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/PropertyEncryption.hh, Replicator/PropertyEncryption_stub.cc, Replicator/Pusher+Revs.cc, Replicator/ReplicatorOptions.hh, Replicator/tests/PropertyEncryptionTests.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, cmake/platform_base.cmake
API addition: Defined encryptable-property constants in c4Document+Fleece.h and c4Document.hh.
The PropertyEncryption class takes a document's properties as a Dict and applies property-level encryption or decryption.
Its implementation is in the EE repo: see PR https://github.com/couchbase/couchbase-lite-core-EE/pull/15. There is a stub source file here that either #includes it or defines a stub CE implementation that does nothing but return an error if an encryptable property is found.
=> Implemented PropertyEncryption [API]

Networking/WebSockets/WebSocketImpl.cc
This is the assertion that frowns:
assert_precondition(off < size) in slice::operator[](size_t off)
=> Do not memcpy 0 bytes to avoid assertion. CBL-2169

LiteCore/Support/Logging.cc, LiteCore/Support/TestsCommon.cc, LiteCore/tests/LogEncoderTest.cc
It is technical tricky to throw exceptions from logging functions because of the non-recursive mutex they use and in the process raising exceptions, litecore::error attempts log the error and causes the (non-recursive) mutex to lock up.
=> Throw exceptions as the logger fails to open files, CBL-2077

REST/RESTListener+Replicate.cc, REST/Server.cc, REST/tests/RESTListenerTest.cc
We do it to avoid blocking the polling thread.
=> Handle client connections in separate threads. CBL-2210

C/Cpp_include/c4Document.hh, C/include/c4Document+Fleece.h, Replicator/PropertyEncryption.hh, Replicator/tests/PropertyEncryptionTests.cc, Replicator/tests/ReplicatorLoopbackTest.cc
Per change proposal, renamed the value of kObjectType_Encryptable from "EncryptedProperty" to "Encryptable”.
CBL-2266
=> API : Rename EncryptedProperty to encryptable

C/Cpp_include/c4Observer.hh, C/include/c4DocumentTypes.h, LiteCore/Database/CollectionImpl.hh, LiteCore/Database/SequenceTracker.cc, LiteCore/Database/SequenceTracker.hh, LiteCore/tests/SequenceTrackerTest.cc, Replicator/ChangesFeed.cc, Replicator/Pusher.cc
1. Fixed bug wherein Pusher stops getting notified of continuous changes, by making it check Changes.askAgain.
2. Restored bodySize in C4DatabaseChange, and hence in RevToSend, so progress numbers will update.
For CBL-1925
=> Fix two bugs involved in CBL-1925

Jenkinsfile, jenkins/build_server_android.sh, jenkins/jenkins_android.sh
This is the result of the docker container update to JDK 11.  The sdkmanager in the previous location is not compatible with JDK 11, and frustratingly the new sdkmanager will download the old sdkmanager into the old location so we are forced to use the new one.
=> Update for new sdkmanager location

Networking/Poller.cc, Networking/Poller.hh, Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/WebSocketImpl.cc, Replicator/tests/ReplicatorSGTest.cc
Fix for cases where BuiltInWebSocket won't close the connection when the peer closes the socket unexpectedly:
- Peer calls shutdown
- BuiltInWebSocket::readFromSocket is called, reads 0 bytes, calls inherited close()
- WebSocketImpl::close sends a CLOSE message and waits for a reply.
- Five seconds later it times out. closeSocket() calls socket->close(), which invokes the `shutdown` system call and Poller::interrupt.
- Poller::interrupt tries to call the listeners on that FD, but there aren't any, so BuiltInWebSocket never finds out the socket is closed.
I added a new kDisconnect event for Poller, so the BIWS can be notified reliably when the socket closes.
Also, it doesn't make sense to send a CLOSE message in this situation (peer shutdown) since the peer can't possibly reply to it. …
=> Reworked BuiltInWebSocket handling of EOF on read (CBL-2204)

LiteCore/Database/LiveQuerier.cc
This way we eliminate unpredictable changes, in particular a race between setting inside `stop()` and checking inside `_runQuery`.  Also include a check for a closed database, as a precaution, to prevent a crash in the event that this doesn't work for unexpected reasons.
=> CBL-2335: Guard access to LiveQuerier _stopping

Replicator/RevFinder.cc, Replicator/tests/ReplicatorSGTest.cc
As a deleted doc is pushed up, we lose the channel info because the deleted docs have empty bodies. This causes SGW to think all channels are removed from this doc and hence send down the Removal flag when pulled. This commit disregards the Removal flag if it is accompanied by the Deleted flag.
=> Fix unexpected purging after push/pull tomestones, CBL-2345

C/c4Database.cc, C/c4Private.h, C/tests/c4DatabaseTest.cc, LiteCore/Database/BackgroundDB.cc, LiteCore/Database/Database.cc, LiteCore/Database/Database.hh, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, REST/RESTListener.cc, Replicator/DBAccess.cc, Replicator/c4IncomingReplicator.hh, Replicator/c4RemoteReplicator.hh
By default, a database connection is tagged "appOpened" as it is opened. These database connections are opened by the application, and, as such, the application must close all of them as it calls to delete the underlying database. Other tags are reserved for the connections opened by the Core library. The library is responsible to close them.
Also changed kOtherDBCloseTimeoutSecs from 3 seconds to 6 seconds for CBL-2383.
=> Tagging the opened database connections. CBL-2357

.github/workflows/check_deps.yml, .gitmodules, build_cmake/scripts/check_deps.py
First, migrate sqlite3-unicodesn and ios-cmake to couchbasedeps and set up couchbase-master branch on all couchbasedeps submodules to be the default branch from now on.
From now on until further notice all commits must be present in a branch called couchbase-master for couchbasedeps submodules (no need for it to be the HEAD of couchbase-master, just present in the history of couchbase-master).  This action will validate that no one has accidentally committed a pre-merge submodule SHA . If this fails, the remedy steps will be to commit the POST merge submodule SHA before merging the lite-core PR.
=> CBL-2486: Verify couchbasedeps submodule commits

C/c4Observer.cc
CBL-2511: retain the database in C4CollectionObserverImpl.
We need to retain the database that owns the collection in order to keep the collection alive.
=> CBL-2559: retain the database in C4CollectionObserverImpl.

CMakeLists.txt
A few of them don't apply in general in the CMake project
HAVE_GMTIME_R only controls one line in a function that is not used by Couchbase Lite involving column definitions with the "DEFAULT CURRENT_TIME" clause
SQLITE_ENABLE_LOCKING_STYLE appears to only have any effect on multiple processes using the same file, which Couchbase Lite does not do.
=> Bring SQLite defines in line with Xcode project

LiteCore/Query/QueryParser.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryTest.cc
Meta().id will assume "id" as the column name, instead of "$#".
=> CBL-2553: N1QL Meta().<property> column names

Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/WebSockets/BuiltInWebSocket.cc
* A minimum fix for CBL-2570 that receives EWOULDBLOCK during reads. There are a few other read functions in TCPSocket.cc but those are used in blocking mode so they are not effected by the issue.
* This fix is against 5c401b340f9512a6545e725022eb95df00f4b5fe which assumes that EWOULDBLOCK will not happen as we only read when the poller notifies readable. However when syncing the the user's server, the EWOULDBLOCK did happen when reading right after getting readable notification. It seems like it is possible that the socket may not have data to read yet right after the readable is notified; I have also experimented adding a small delay (e.g. 10ms) before read() (after readable is notified), and that also solved the problem.
* This fix basically brought back the code that assumes …
=> CBL-2570 : Assume EWOULDBLOCK is not an error in non-blocking reads

Replicator/Puller.cc, Replicator/Puller.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh
The replicator will close its database after it is stopped, but RevFinder continues trying to use it.  Wire up RevFinder so that it blocks the Replicator from stopping until RevFinder is finished.
=> CBL-2562: Try to put down some long running race conditions

LiteCore/Support/Error.cc, Replicator/Puller.cc, Replicator/Puller.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh
Only in MinSizeRel, and only on Windows.  The remaining parts of 844b7b3622b05939aa1614929ad1897502acacf1 seem to address the problem of crashing due to null replicator dereference.
=> Partially undo the fix for 2562 which seems to cause hanging

C/Cpp_include/c4Replicator.hh, Replicator/Replicator.hh
C4ReplicatorImpl and Replicator both inherited from InstanceCountedIn twice, so they'd show up twice in any leaked-object reports.
Harmless but confusing.
=> Removed two redundant InstanceCounted base classes

LiteCore/Database/TreeDocument.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/Storage/SQLiteKeyStore.cc
The kSynced flag is a shortcut flag on a document that indicates that the latest revision has been pushed to the remote, but that this information has not yet been recorded into the body of the document (i.e. the document has not been saved since).  The pusher uses a method which consolidates this information when deciding which revision to send as the ancestor in a proposeChanges message.  The puller also needs to consolidate this information when deciding whether or not a change is properly set as the remote ancestor when a changes message comes from the other side because otherwise it will sometimes falsely believe it already has things correctly set by scanning the document body, but not considering the kSynced flag.
=> CBL-2579: Puller needs to consider the kSynced flag

LiteCore/tests/LogEncoderTest.cc, Xcode/LiteCore.xcodeproj/xcshareddata/xcdebugger/Breakpoints_v2.xcbkptlist
1. Added `ExpectExceptions` around two recent tests that intentionally cause exceptions to be thrown. This prevents Xcode from hitting a breakpoint during those tests.
2. Added a shared Xcode breakpoint on "Runtime Issues", i.e. issues detected by Undefined Behavior Sanitizer, etc.
=> Xcode: Break on sanitizer issues, but not on expected exceptions

Xcode/build_mbedtls.sh
The Xcode project was building mbedTLS with the Debug configuration, not RelWithDebInfo, even in Release builds.
This is migrated from fix/optimize-mbed. After consulting with Jens, I take part of it with this commit.
=> mbedTLS optimization / size reduction

C/c4Database.cc, C/tests/c4DatabaseTest.cc, LiteCore/Database/DatabaseImpl+Upgrade.cc, LiteCore/Database/DatabaseImpl.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RawRevTree.hh, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/tests/UpgraderTest.cc
Version 3 changes the document schema in the database, adding an
'extra' column that stores the rev-tree, while the 'body' column just
contains the current revision's Fleece body.
Rewriting all the docs in the database to the new schema the first
time it's opened by 3.0 turns out to be too slow for very large
databases.
With this commit we skip the rewrite. Instead, the database reads
documents in either the v2 or v3 format. But docs are always saved in
v3, so over time the database will migrate, and its performance will
improve as less document data is loaded.
CBL-2374
=> CBL-2374: Upgrade docs to 3.0 schema lazily

C/c4Database.cc, C/tests/c4DatabaseTest.cc, LiteCore/Database/DatabaseImpl+Upgrade.cc, LiteCore/Database/DatabaseImpl.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RawRevTree.hh, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/tests/UpgraderTest.cc
Version 3 changes the document schema in the database, adding an
'extra' column that stores the rev-tree, while the 'body' column just
contains the current revision's Fleece body.
Rewriting all the docs in the database to the new schema the first
time it's opened by 3.0 turns out to be too slow for very large
databases.
With this commit we skip the rewrite. Instead, the database reads
documents in either the v2 or v3 format. But docs are always saved in
v3, so over time the database will migrate, and its performance will
improve as less document data is loaded.
Cherry-picked from CBL 2374.
=> CBL-2638: Upgrade docs to 3.0 schema lazily

Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh
Combined with enhancements in the passive puller, and Sync Gateway, a pusher can now recover from a false conflict or unknown ancestor situation without the assistance of an active puller.  When active, the new format for a 409 response to a `proposeChanges` message will be `{"status": 409, "rev": "<current-rev-id>"}`
=> CBL-2583: Enhance proposeChanges message to accept revID in response

LiteCore/Database/TreeDocument.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteKeyStore.cc
The kSynced flag is a shortcut flag on a document that indicates that the latest revision has been pushed to the remote, but that this information has not yet been recorded into the body of the document (i.e. the document has not been saved since).  The pusher uses a method which consolidates this information when deciding which revision to send as the ancestor in a proposeChanges message.  The puller also needs to consolidate this information when deciding whether or not a change is properly set as the remote ancestor when a changes message comes from the other side because otherwise it will sometimes falsely believe it already has things correctly set by scanning the document body, but not considering the kSynced flag.
This fix is ported here from release/lithium, …
=> CBL-2675: Puller needs to consider the kSynced flag

C/Cpp_include/c4Query.hh, C/c4Query.cc, LiteCore/Database/LiveQuerier.cc, LiteCore/Database/LiveQuerier.hh
Otherwise there is a race where liveQuerierUpdated could be called on a no longer valid delegate object
=> CBL-2673: Don't clear _bgQuerier until after fully stopped

Jenkinsfile, jenkins/build_server_android.sh, jenkins/jenkins_android.sh
* Update for new sdkmanager location
This is the result of the docker container update to JDK 11.  The sdkmanager in the previous location is not compatible with JDK 11, and frustratingly the new sdkmanager will download the old sdkmanager into the old location so we are forced to use the new one.
* Update for PR validation as well
* Run Android validation on docker container
=> Update for new sdkmanager location (#1231)

Crypto/PublicKey+Apple.mm, README.md
* SecTrustGetCertificateAtIndex > SecTrustCopyCertificateChain
* SecKeyGeneratePair > SecKeyCreateRandomKey
* make it compatible with Xcode 12+; tested on 12.2, 12.5.1, 13.1
* Update the ReadMe about Xcode version for building
=> CBL-2621: Replace deprecated APIs

LiteCore/Database/LiveQuerier.cc
* Called liveQuerierStopped() regardless of _query being initialized or not so that the LiveQuerier and C4Query will be cleaned up afters stopped.
* Made sure that _stop() will be called only once by checking whether the _stopping has already be set to true in stop().
=> CBL-2678 : Fix LiveQuerier and C4Query leak

LiteCore/Query/SQLiteFleeceEach.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/Query/SQLiteFleeceUtil.hh, LiteCore/RevTrees/RawRevTree.cc
* Fixed the test for whether a slice contains a serialized RevTree.
When I wrote it I'd forgotten that in a replicated doc, the remote
rev mapping follows the rev-tree, and that broke the test.
* When grabbing the rev data out of a serialized rev tree, it may be
at an odd address, which breaks Fleece. I had to reinstitute the old
workaround that copies the data to a new heap block.
* SQLiteFleeceEach may also read a direct doc body and needs the same
logic as QueryFleeceScope. (It can't directly use a QueryFleeceScope
because it doesn't have access to a `sqlite3_context*`.)
* `fl_root` also needs the same transformation of doc bodies.
CBL-2680
CBL-2682
=> Fixed query crashes in upgraded databases (CBL-2680, CBL-2682)

Jenkinsfile
=> CBL-2640: increase Jenkins PR validation timeout to 60 min

LiteCore/Database/LiveQuerier.cc
* Instead, change it back to false if it starts again.  There is no valid scenario for the live query to do anything until that point anyway.  Also tighten up the check of it so that it is entirely based on the value read inside a lock.
* CBL-2586 is cloned from CBL-2508 to get the fix ported to master branch. This PR is basically cherry-picking the fix for CBL-2508.
=> CBL-2586: Don't change LiveQuery _stopping so early (#1302)

LiteCore/Query/SQLiteFleeceEach.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/Query/SQLiteFleeceUtil.hh, LiteCore/RevTrees/RawRevTree.cc
* Fixed the test for whether a slice contains a serialized RevTree.
When I wrote it I'd forgotten that in a replicated doc, the remote
rev mapping follows the rev-tree, and that broke the test.
* When grabbing the rev data out of a serialized rev tree, it may be
at an odd address, which breaks Fleece. I had to reinstitute the old
workaround that copies the data to a new heap block.
* SQLiteFleeceEach may also read a direct doc body and needs the same
logic as QueryFleeceScope. (It can't directly use a QueryFleeceScope
because it doesn't have access to a `sqlite3_context*`.)
* `fl_root` also needs the same transformation of doc bodies.
=> Fixed query crashes in upgraded databases

LiteCore/Database/TreeDocument.cc, LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/Storage/SQLiteKeyStore.cc
CBL-2676: Puller needs to consider the kSynced flag
The kSynced flag is a shortcut flag on a document that indicates that the latest revision has been pushed to the remote, but that this information has not yet been recorded into the body of the document (i.e. the document has not been saved since).  The pusher uses a method which consolidates this information when deciding which revision to send as the ancestor in a proposeChanges message.  The puller also needs to consolidate this information when deciding whether or not a change is properly set as the remote ancestor when a changes message comes from the other side because otherwise it will sometimes falsely believe it already has things correctly set by scanning the document body, but not considering the kSynced flag.
=> CBL-2676: Puller needs to consider the kSynced flag (#1309)

LiteCore/RevTrees/VectorRecord.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Support/Base.hh, LiteCore/tests/LiteCoreTest.hh, LiteCore/tests/VectorRecordTest.cc
It breaks the Tools build by forcing the LiteCore C++ API.
Instead include c4Base.h.
Requires a few changes in the LiteCore C++ Tests build.
=> Don't include c4Base.hh in Base.hh

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/Query/SQLiteFleeceUtil.cc, LiteCore/Query/SQLiteFleeceUtil.hh
Note: cherry-picked from release/lithium#b018a12db01222d451b4f7b95478d4825bc19954
=> CBL-2730 : must initialize outCopied in valueAsDocBody(). (#1348)

LiteCore/Support/StringUtil.cc, LiteCore/Unix/icu_shim.c, LiteCore/Unix/icu_shim.h, LiteCore/tests/SQLiteFunctionsTest.cc
Also, remove the comments indicating that the collator is not available on all platforms.  It has been for a while.
=> Don't compile icu_shim if LITECORE_USES_ICU is not defined

C/c4Document.cc, C/c4Error.cc, C/include/c4Error.h, C/include/c4Log.h, Crypto/PublicKey.cc, LiteCore/Database/LiveQuerier.cc, LiteCore/Database/SequenceTracker.cc, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, LiteCore/Query/QueryParser.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Support/Error.hh, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/Support/StringUtil.hh, Networking/Poller.cc, Replicator/ChangesFeed.cc, Replicator/DBAccess.cc, Replicator/Inserter.cc, Replicator/Pusher+Revs.cc, Replicator/Pusher.cc, Xcode/xcconfigs/XcodeWarnings.xcconfig, cmake/platform_apple.cmake, cmake/platform_linux.cmake
- In Xcode, enabled -Wformat -Wformat-nonliteral -Wformat-security
- Fixed a couple of places that were accidentally passing non-literal strings to format args.
- Declared more functions as being __printflike to fix warnings.
- Updated Fleece, where I made similar changes.
>Note: When the 2nd parameter of `__printflike` is 0, like `__printflike(n,0)`, it means that the format string's args come from a `va_list` parameter instead of "`...`". The reason to declare this is that it suppresses a non-literal format string warning in the _implementation_ of the function, where the format string and `va_list` are passed to a function like `vsprintf`. (I haven't seen this documented anywhere; I just found this usage of `__printflike` in C library headers, and adopting it fixed the warnings/errors …
=> Improved format-args security (-Wformat-literals, etc)

C/tests/cmake/platform_linux.cmake, LiteCore/Support/Error.cc, LiteCore/tests/cmake/platform_linux.cmake, build_cmake/scripts/strip.sh
The export symbol hiding in LiteCore prevents getting most function names, but instead an offset that can be used with addr2line can be printed.  However, this relies on correcting the stripping script in order to extract all needed symbols before the static libraries are stripped.  This is also corrected in this commit.  Additionally, in order to get usable function names out of the tests add -export_dynamic to their linker arguments.
=> CBL-2611: Take steps to get a reasonable backtrace on Linux

Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh
Cherry-picked from lithium/CBL-2583: Enhance proposeChanges message to accept revID in response
Combined with enhancements in the passive puller, and Sync Gateway, a pusher can now recover from a false conflict or unknown ancestor situation without the assistance of an active puller.  When active, the new format for a 409 response to a `proposeChanges` message will be `{"status": 409, "rev": "<current-rev-id>"}`
=> CBL-2637: Enhance proposeChanges message to accept revID in response

Crypto/PublicKey+Apple.mm
* Reference objects returned from SecTrustCopyCertificateChain, is not able to SecItemDelete, so we are getting it again from Keychain to delete.
* For non-chain certs, we are deleting the already returned certificate itself.
=> CBL-2701: SecItemDelete failures

jenkins/build_server_android.sh, jenkins/build_server_unix.sh, jenkins/build_server_win.ps1
CBD-4587, ensure naming conventions used for artifacts on latestbuild 
are consistent with what are on Nexus.  Fixed windows powershell script.
-Ming Ho
=> CBD-4587, ensure naming conventions used for artifacts on latestbuild are consistent with what are on Nexus

LiteCore/Query/QueryParser.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryTest.cc
Meta().id will assume "id" as the column name, instead of "$#".
Cherry-picked from 7567b78a7872f
=> CBL-2779: N1QL Meta().<property> column names (#1297)

Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/WebSockets/BuiltInWebSocket.cc
* The problem was as the replicator’s connection kept getting closed when connecting to SG with TLS. From the provided log file, the error that caused the connection to get closed is the POSIX 35 (EWOULDBLOCK) error (on MacOS platform). The EWOULDBLOCK errors in the log were found during both READ and WRITE to the socket stream. There were more error during READ than WRITE.
* The user who reported the problem used CBL-C 3.0.0 Beta 2 on MacOS, which doesn't contain the EWOULDBLOCK fix for READ. After providing the user with the RC2 binary, the problems during READ were gone, however, the problem during WRITE were remained.
* In Non-Block mode, the EWOULDBLOCK should not be considered as an error and should be ignored. This PR made the TCPSocket::write(vector<slice> &ioByteRanges) ignored …
=> CBL-2808 : Ignore EWOULDBLOCK when write in non-block mode

Networking/TCPSocket.cc
* Flipped the return value of TCPSocket::checkReadWriteStreamError based on the code review in #1385 from @snej.
* Updated the other parts of the code, and made them check the called result the same way.
=> CBL-2808: Flip the return value of TCPSocket::checkReadWriteStreamError

LiteCore/Support/Codec.cc, LiteCore/Support/FilePath.cc, LiteCore/Support/GCDMailbox.cc, Xcode/xcconfigs/Project.xcconfig
Two checks for iOS < 10 (our minimum currently is 10)
One check for method unavailable in Windows 7 (our minimum currently is any 10.x supported by Microsoft)
=> CBL-2824: Remove defunct backwards compatibility branches

Networking/WebSockets/WebSocketImpl.cc, Networking/WebSockets/WebSocketImpl.hh
From the standpoint of the lifecycle, a WebSocket can have 4 states: Opening, Opened, Closing, and Closed. These states can only progress monotonically: it can only transition to the following states in that order.
=> CBL-2658 : manage WebSocket lifecycle

LiteCore/Support/StringUtil.hh
I veriefied that with old compilers all works fine,
except msvc 15, because of it is not availble in goldbot:
gcc 7.1 is ok: https://godbolt.org/z/h364dc9M8
clang 5.0 is ok: https://godbolt.org/z/vzd8qeedY
clang 5.0 + libc++ is ok: https://godbolt.org/z/YjbbcxebG
msvc 19.4 is ok: https://godbolt.org/z/Kobh61Tb4
comment #1387
build of tests still broken, because of catch dependency,
but at least without tests all works fine
=> fix build of StringUtil.hh with gcc 11.2.0

LiteCore/Query/Query.cc, LiteCore/Query/Query.hh, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh
From the report of Mac's Address Sanitizer, we ran into a situation whereby, concurrently,
A. as the holder of the last reference of a Query object, LiveQuerierDelegate, is deleted, the Query object goes to the deletion process;
B. as DataFile is deleted, the close method is called on the same Query object.
For good reason, DataFile keeps plain pointers of Query objects, which are registered/unregistered as they are constructed/destructed. We fix the problem by protecting _queries in DataFile with mutex. We also need to make sure that the first thing in the destruction process of the Query object is to unregister it.
=> CBL-2764 : fix a bug of "heap-use-after-free".

scripts/fetch_litecore.py
Fix the 'java' variant to alias "linux", "macosx", "windows-win64", replacing the deprecated "centos6" with "linux"
=> java now uses linux; centos6 is deprecated

LiteCore/Support/TestsCommon.cc, Networking/BLIP/BLIPConnection.cc
This bug is not easy to show. It occurs intermittently in Jenkins' macosx build. The purpose of this commit is to have detailed logs when the test fails.
=> CBL-2670 : raise the log level to debug for BLIPLog

REST/Request.cc
Safari refuses to make a WebSocket client connection (i.e. with a JS WebSocket object) to LiteCore -- it logs "the server sent an illegal response" and aborts the connection. No other client I've tried has such an issue.
I finally figured out that what triggers this is that the response starts "HTTP/1.0". Changing it to "HTTP/1.1" fixes the problem.
I am not sure why I used "HTTP/1.0" in the first place ... maybe because the listener doesn't support keep-alive. But it was basically implemented to [a modest subset of] HTTP 1.1.
=> Change HTTP response for compatibility w/ Safari

Networking/BLIP/BLIPConnection.cc
This bug is not easy to show. It occurs intermittently in Jenkins' macosx build. The purpose of this commit is to have detailed logs when the test fails.
=> CBL-2671 : raise the log level to debug for BLIPMessages (#1401)

jenkins/build_server_android.sh, jenkins/build_server_unix.sh, jenkins/build_server_win.ps1
jenkins' ssh publisher can't publish symlinks.  We will just create another copy of the artifacts in couchbase-lite-core/<version>/<bld>.  ${EDITION}_${VERSION}-${BLD_NUM} is added to artifact names.
-Ming Ho
=> CBD-4587, push artifacts to couchbase-lite-core/<version>/<bld> on latestbuild

Networking/BLIP/LoopbackProvider.hh
LoopbackWebSocket implements messsaging within the same application by threaded queues. For Mac, in particular, we use GCD's dispatch_after in order to simulate network latency. Since dispatch_after takes absolute time in the future, as opposed to a delta delay, the order may be displaced if two future times are numerically equal. To guarantee the ordering, we take advantage of the ordering guarantee of dispatch_async with the serial queue: we queue the messages with dispatch_async, and actually send the message with dispatch_after.
=> CBL-2670 : ensure message order for LoopbackWebSocket.

scripts/fetch_litecore_base.py, scripts/fetch_litecore_requirements.txt, scripts/fetch_litecore_version.py
Originally I was going to add it to extend the original fetch_litecore script, but things got too out of hand with the conflicting ways of specifying "I want an enterprise build" so I decided to abstract the majority of the logic into a base script that the other two use.  Also added a requirements file for pip so that the standard pattern can be followed:
```
python3 -m venv venv
source venv/bin/activate # venv/Scripts/activate on Windows
pip install -r fetch_litecore_requirements.txt
```
=> Add a new litecore download script to download by version

C/tests/CMakeLists.txt, CMakeLists.txt, LiteCore/tests/CMakeLists.txt, Networking/BLIP/CMakeLists.txt, Networking/BLIP/cmake/platform_android.cmake, Networking/BLIP/cmake/platform_apple.cmake, Networking/BLIP/cmake/platform_linux.cmake, Networking/BLIP/cmake/platform_win.cmake, cmake/platform_apple.cmake, cmake/platform_linux.cmake, cmake/platform_unix.cmake, jenkins/build_server_android.sh, jenkins/jenkins_android.sh
This links in all object files directly instead of first piping them through a static library, which can lead to better optimization
=> CBL-2902: Convert BLIP from static to object library

Replicator/Pusher+Revs.cc, Replicator/tests/ReplicatorLoopbackTest.cc
* When delta sync is enabled and an attachment is updated on a doc, the revpos was left out as being unchanged which is not correct. The reason that it was considered as unchanged because the logic to generate the attachment metadata of the ancester is using the new revision revpos.
* This commit fixed the issue by using the generation of the ancestor’s revID as the revpos when generating the attachment metadata of the anscenter’s attachment.
* Note : The logic to assign revpos to attachments are not exactly correct as we always update the attachments’ revpos with the current revision’s generation. Per discussion in CBL-2839, we decided not to change or fix this logic. This logic has been implemented since 2.0.
=> CBL-2942 : Fix revpos missing when delta sync is used

C/c4Query.cc
According to code review, move retain/release on the query object to the place that uses the query object.
=> CBL-2942 : Move retain/release on query object

Replicator/Pusher+Revs.cc, Replicator/tests/ReplicatorLoopbackTest.cc
* Ported from the fix in the Lithium branch : https://github.com/couchbase/couchbase-lite-core/commit/44e663311d4853b8593cfb247408dd80acb75666
* When delta sync is enabled and an attachment is updated on a doc, the revpos was left out as being unchanged which is not correct. The reason that it was considered as unchanged because the logic to generate the attachment metadata of the ancester is using the new revision revpos.
* This commit fixed the issue by using the generation of the ancestor’s revID as the revpos when generating the attachment metadata of the anscenter’s attachment.
* Note : The logic to assign revpos to attachments are not exactly correct as we always update the attachments’ revpos with the current revision’s generation. Per discussion in CBL-2839, we decided not to …
=> CBL-2948 : Fix revpos missing when delta sync is used

C/c4Query.cc
* This commit ported the fix from the Lithium branch.
* When enableObserver() is called twice, there is a race b/w resetting _bgQuery in C4Query::liveQuerierStopped() called by an actor thread and calling _bgQuerier.stop() in C4Query::enableObserver(). As a result, _bgQuerier.stop() would could cause a crash as _bgQuerier could be null.
* Added a mutex lock in liveQuerierStopped(), and ensured that the C4Query object lives until the end of the callback call.
* Reference Commits: 
https://github.com/couchbase/couchbase-lite-core/commit/9a4c04b7e974dd7752e2e2fb974fd13832316e29
https://github.com/couchbase/couchbase-lite-core/commit/5dc7231e77510dcdfdc20e391ba0fe2dcbb492aa
=> CBL-2944 : LiveQuery could crash when removing the listener

CMakeLists.txt, cmake/platform_win.cmake, jenkins/build_server_win.ps1
The structure of the existing files will remain the same and in addition an include directory will be present
=> Modify Windows build script to package include directory

Replicator/ChangesFeed.cc, Replicator/DBAccess.cc, Replicator/Pusher+Revs.cc, Replicator/Pusher.cc
I build my project with `-Werror=format`, so would be nice
if couchbase-lite-core do not generate compile errors in this mode.
=> fix warning about wrong data format for *printf like functions

LiteCore/Database/SequenceTracker.cc
fixes #1413 , to prevent local change wrongly marked as external,
because of there was external change in this document before.
Not sure about `committedSequence`. Do I need to reset this variable too? 
Because of `committedSequence` is setted in the same way as `external`:
```
if (!inTransaction()) {
entry->committedSequence = sequence;
entry->external = true; // it must have come from addExternalTransaction()
}
```
=> SequenceTracker: reset external every time

Networking/WebSockets/WebSocketImpl.cc
requestClose() will triger onClose() asynchronously which will reset _responseTimer. Move requestClose/closeSocket after startResponseTimer.
=> CBL-2980 : fixing racing of _responseTimer.

LiteCore/Android/getifaddrs.h, jenkins/build_server_android.sh, jenkins/jenkins_android.sh
In the process it was determined that we need to move to a stock CMake and Ninja, so fetch those from cbdeps
=> Update Android NDK to 23b

C/tests/c4ObserverTest.cc, LiteCore/Database/SequenceTracker.cc, LiteCore/Database/SequenceTracker.hh
SequenceTracker::_documentChanged was incorrectly ignoring a change
to a document with an existing-but-idle Entry when there were no db
change notifiers.
In practice this meant that if you created a doc-change notifier for
a doc that hadn't been modified yet in this db instance, and then
updated the document, the change wouldn't be recorded in the
SequenceTracker so other db instances wouldn't find out about it.
The offending lines were last edited in 2016(!), so I am not sure
exactly why they were there. I think they date back to a time when
there was only a single SequenceTracker shared by all DB instances on
a file, in which case that behavior would be a valid optimization.
It should be safe to backport this fix to any earlier version of
CBL, back to 2.0.
CBL-3013
=> Fix SequenceTracker bug with docs observed before a db change [CBL 3013]

C/tests/c4ObserverTest.cc, LiteCore/Database/SequenceTracker.cc, LiteCore/Database/SequenceTracker.hh
SequenceTracker::_documentChanged was incorrectly ignoring a change
to a document with an existing-but-idle Entry when there were no db
change notifiers.
In practice this meant that if you created a doc-change notifier for
a doc that hadn't been modified yet in this db instance, and then
updated the document, the change wouldn't be recorded in the
SequenceTracker so other db instances wouldn't find out about it.
The offending lines were last edited in 2016(!), so I am not sure
exactly why they were there. I think they date back to a time when
there was only a single SequenceTracker shared by all DB instances on
a file, in which case that behavior would be a valid optimization.
It should be safe to backport this fix to any earlier version of
CBL, back to 2.0.
CBL-3037
=> Fix SequenceTracker bug with docs observed before a db change

Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4Replicator.hh
This commit is ported from f457d9bc74af276516d868b61a48b81b5d717e5c based on the logic, because the source has been reorganized significantly.
=> CBL-3050 : Account for a race between pendingDocs and terminate

LiteCore/Support/Error.cc, LiteCore/Support/access_lock.hh, Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/Replicator.cc
After we ported CBL-2407 from 2.8.7 to Lithium, we had to apply some patch up to pass unit tests in Jenkins. The patch-up turns out to be crutial not only for Lithium, but also for Hydrogen as discovered by Platforms' tests.
=> CBL-3056 : LiteCore crashes in pendingDocumentIDs

C/include/c4ReplicatorTypes.h, Networking/NetworkInterfaces.cc, Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/WebSocketImpl.hh, Replicator/c4Socket.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorSGTest.cc
* Added kC4SocketOptionNetworkInterface option.
* Added the network interface support in BuiltInWebSocket which will set the network interface to the ClientSocket. Eventaully the network interface will be set to the sockpp’s Connector before the connection is established.
* In the TCPSocket class which is a based class of the ClientSocket, implement the logic to select a network interface based on the name or IP Address.
* Updated NetworkInterfaces's _getInterfaces() to also get the loopback interface.
=> Add Network Interface support in BuiltInWebSocket

Networking/TCPSocket.cc, Networking/TCPSocket.hh, Networking/WebSockets/BuiltInWebSocket.cc
* Ported the fix to ignore EWOULDBLOCK when write in non-block mode.
* Ported commits: https://github.com/couchbase/couchbase-lite-core/commit/c7ff2208e24ddf6715404c6f81b9a116749d739f and https://github.com/couchbase/couchbase-lite-core/commit/66a3cb4b5af19e4375fe93c0c5e54e7b6dff7686.
* Note : See info about the problem and the fix in the ported commits.
=> CBL-2868 : Ignore EWOULDBLOCK when write in non-block mode (Port)

C/include/c4ReplicatorTypes.h, Replicator/ChangesFeed.cc, Replicator/Checkpointer.cc, Replicator/IncomingRev.cc, Replicator/ReplicatedRev.hh, Replicator/c4ReplicatorImpl.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorSGTest.cc
Two methods are yet to be defined:
(1) C4Replicator::pendingDocIDs()
(2) C4Replicator::isDocumentPending(slice docID)
I wonder whether we should have concept of DocPath = <scope>.<collection>.<id> so that (1) may return list of pending doc paths, and the argument of (2) may be DocPath.
=> Extend C4 replicator APIs to include Collections & Scopes.

C/Cpp_include/c4Database.hh, C/c4CAPI.cc, C/include/c4Collection.h, LiteCore/Database/DatabaseImpl.cc, LiteCore/Database/DatabaseImpl.hh
:new: API added (`c4db_hasScope`) for use in determining whether or not a given scope exists
=> CBL-3150: Implement c4db_hasScope function

C/Cpp_include/c4Listener.hh, C/include/c4DatabaseTypes.h, C/include/c4Listener.h, REST/Listener.cc, REST/Listener.hh, REST/RESTListener+Handlers.cc, REST/RESTListener.cc, REST/RESTListener.hh, REST/REST_CAPI.cc, REST/c4Listener.cc
:new: API added c4listener_shareCollection (and c++ equivalent)
:new: API added c4listener_unshareCollection (and c++ equivalent)
Note that this API is additive to c4listener_shareDB, and not a replacement.  See the interface document for more details.
=> CBL-3148: Add c4listener_shareCollection API

C/include/c4ReplicatorTypes.h, Replicator/IncomingRev.cc, Replicator/PropertyEncryption.hh, Replicator/PropertyEncryption_stub.cc, Replicator/Pusher+Revs.cc, Replicator/tests/PropertyEncryptionTests.cc, Replicator/tests/ReplicatorLoopbackTest.cc
🆕 C4ReplicatorCollection.pushFilter property
🆕 C4ReplicatorCollection.pullFilter property
⚠️ Breaking change adds collection spec to property encryption / decryption callback
⚠️ These are only here for the sake of API completion.  They will need to be implemented after some base collection based replicator functionality is done.
=> CBL-3147: Add collection specific replicator filters

LiteCore/Support/WeakHolder.hh, Networking/BLIP/BLIPConnection.cc, Networking/BLIP/LoopbackProvider.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/WebSocketImpl.cc, Networking/WebSockets/WebSocketInterface.cc, Networking/WebSockets/WebSocketInterface.hh, Replicator/tests/ReplicatorAPITest.cc, Xcode/LiteCore.xcodeproj/project.pbxproj
Following is a chain of strong ownership:
Replicator -> Connection -> BLIPIO -> WebSocket
Currently, the reverse relationship from WebSocket to BLIPIO is established by plain pointer, for good reasons. However, this creates a problem if the websocket outlives BLIPIO for a fleeting moment of time. In this commit, we use WeakHolder for the delegate.
Cherry-picked from 7d8a12b7713aed
=> CBL-3224 : use WeakHolder for websocket::Delegate. (#1471)

C/c4CAPI.cc, C/include/c4Collection.h
:warning: C4Error added to c4db_scopeNames, c4db_collectionNames, and c4db_getCollection
These have the potential to throw errors, which need to be caught at the C boundary, and also be available for the caller to analyze.
=> Add in error information for three methods

Networking/BLIP/BLIPConnection.cc, Networking/BLIP/BLIPConnection.hh, Replicator/Replicator.cc, Replicator/Replicator.hh
The ConnectionDelegate is a plain pointer to its owner, Replicator. It may be deleted as it is used by the BLIPConnection. We use WeakHolder to solve the problem.
=> CBL-3092 : BLIPConnection crashes on the delegate.

LiteCore/Storage/SQLiteDataFile.cc
Note to function with EE, the EE commit must be at least 008d44b9
Cherry picked from 75c2025d16878bba88fce02b651cb7bc8a628525
=> CBL-3222: Enable F_BARRIERFSYNC on macOS / iOS

C/Cpp_include/c4Collection.hh, C/Cpp_include/c4Database.hh, C/Cpp_include/c4Observer.hh, C/c4CAPI.cc, C/c4Observer.cc, C/include/c4Base.h, C/include/c4Collection.h, C/include/c4DocumentTypes.h, C/include/c4Observer.h, C/tests/c4ObserverTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, C/tests/c4ThreadingTest.cc, LiteCore/Database/SequenceTracker.hh, LiteCore/tests/SequenceTrackerTest.cc, Replicator/ChangesFeed.cc
⚠️ Breaking change adds collection spec to callbacks registered via c4docobs_create (and c4docobs_createWithCollection)
⚠️ c4dbobs_getChanges signature removes external, and moves it to a new return type that contains the original return type as numChanges, along with external and collection
Added collection based revision creation methods for C4Tests, adjusted signature of other tests based on the above changes
=> CBL-3149: Make all observers collection aware

C/Cpp_include/c4Database.hh, C/c4CAPI.cc, C/c4Database.cc, C/include/c4Collection.h, C/tests/c4CollectionTest.cc, C/tests/c4ObserverTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, LiteCore/Database/DatabaseImpl.cc, LiteCore/Database/DatabaseImpl.hh
:warning: C4Error parameter added to c4db_getDefaultCollection
Without these close checks, use after close of a DB simply hard crashes.  Now a test will ensure that it returns caller visible error information, and allows a distinction between such things as "default collection was deleted" and "default collection was requested from a closed database"
=> Add error info to getDefaultCollection and add more closed checks

C/c4Observer.cc, C/tests/c4ObserverTest.cc
This brings it in line with collection observer, and prevents an issue whereby calling c4docobs_free after closing the database in question causes an invalid memory access and crash.
=> CBL-3193: Document Observer should retain the database it observes

Replicator/ChangesFeed.cc, Replicator/ChangesFeed.hh, Replicator/Checkpointer.cc, Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Inserter.cc, Replicator/Inserter.hh, Replicator/Puller.cc, Replicator/Puller.hh, Replicator/Pusher.cc, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/RevFinder.hh, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/c4Replicator.cc, Replicator/c4ReplicatorImpl.hh, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.hh
- Changed Options::push and Option::pull to functions, Options::pushOf(unsigned collectionIndex) and Options::pullOf(unsigned collectionIndex)
- Changed Worker::pasive() to Worker::passive(unsigned collectionIndex)
This PR is one of a series of PRs that will gradually approach to replicating of multiple collections. For each PR in the series, I will try to have all tests pass. In the end, all current tests become special cases whereby the collection list consisting but one collection.
=> CBL-3221, CBL-3261 : use collection-aware repl::Options in C4Replicator

C/include/c4Socket.h
It was accurate before the introduction of the socketFactory member in replication parameters, but is no longer required and can be considered optional.
=> CBL-2874: Correct an outdated documentation comment

LiteCore/Database/DatabaseImpl.cc, LiteCore/Database/DatabaseImpl.hh
This allows a temporary blob store to be created for the purposes of reencrypting the blobs
=> Set the create flag when rekeying

Replicator/c4Replicator_CAPI.cc
This is to remove the ambiguity between "no pending documents" "document is not pending" and an error condition
=> CBL-3057: Set error information to zero on some c4repl methods

C/tests/c4CollectionTest.cc, LiteCore/Database/DatabaseImpl.cc
If searching the cache fails, enumerate all the key store names and search for a scope that way.
=> CBL-3298: Make c4db_hasScope multi handle aware

C/tests/c4CollectionTest.cc, LiteCore/Database/Housekeeper.cc, LiteCore/Storage/SQLiteKeyStore.cc
The fix is simple, but reveals another bug where the delete statement doesn't quote the table name and thus fails in most cases since non default collections contains one or more periods.
=> CBL-3306: Fix bug where expiration only works on default collection

C/include/c4ReplicatorTypes.h
:warning: C4ReplicatorParameters::collectionCount changed from unsigned to size_t (size change on 64-bit platforms)
=> CBL-3333: Use size_t for types representing array size

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/tests/QueryTest.cc
The documentation says that it is supposed to consider only non-null values
=> CBL-3087: Correct bug in array_count that counts null values

Replicator/Checkpoint.cc, Replicator/Checkpoint.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/ReplicatorOptions.hh
* Implemented `getCollections()` which follows the same logic from `getRemoteCheckpoint()`, and implemented handleGetCollections().
* As getCollections() will be called only when the replicator is started, `getCollections()` doesn’t include the `refresh` parameter like `getRemoteCheckpoint()` does.
* When there is a NULL checkpoint returned from the getCollections() request, the `getCollections()` will return the error as `LiteCoreDomain / kC4ErrorNotFound`. 
* Added the Checkpoint’s `readDict()` function which is used by `getCollections()` to read each checkpoint dictionary. Also, the original `readJSON()` now calls `readDict()`.
* Changed ReplicatorOptions’s `collectionPathToSpec()` to take `slice` instead of `alloc_slice` parameter so that there is no needs to create `alloc_slice` from …
=> CBL-3278 : Implement BLIP getCollections() and handleGetCollections()

Replicator/IncomingRev+Blobs.cc
* Updated getAttachment to include collection index if it’s not using legacy protocol.
* LiteCore’s pull replicator doesn’t do proofAttachment (I couldn’t find the code that does that).
* For handleGetAttachment() and handleProofAttachment(), SG might send collection index but LiteCore doesn’t use the collection index as blob store is per database. Hence, no changes in handleGetAttachment() and handleProofAttachment().
CBL-3282 and CBL-3283
=> CBL-3282 CBL-3283 : Update BLIP getAttachment to include collection index

C/tests/c4CollectionTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh, Xcode/LiteCore.xcodeproj/project.pbxproj
* Added ReplicatorCollectionTest which inherits from ReplicatorLoopbackTest.
* Included basic replication tests with default collection, single collection, and multiple collection.
* Added gC4ExpectExceptions to the tests that could have exception thrown internally by LiteCore to avoid exception breakpoint in XCode.
* NOTE: The tests are disabled by #ifdef as the implementation in LiteCore is not done yet.
=> CBL-3409 : Add basic collection tests for replicator

C/include/c4ReplicatorTypes.h, Replicator/ChangesFeed.cc, Replicator/ChangesFeed.hh, Replicator/IncomingRev.cc, Replicator/Pusher.cc, Replicator/ReplicatedRev.hh, Replicator/Replicator.cc, Replicator/ReplicatorTypes.cc, Replicator/ReplicatorTypes.hh, Replicator/RevFinder.cc, Replicator/tests/ReplicatorAPITest.cc
:warning: API Change -> Added collectionContext to C4DocumentEnded
This change requires a lot of changes to other classes that interact with this struct.  The majority of the changes are to pass in the collection context where needed to ReplicatedRev (which is dynamically cast to C4DocumentEnded).  However, ChangesFeed needed to get a hold of the collection index to use, in order to know which context to add.
=> CBL-3419: Add collectionContext to C4DocumentEnded

Replicator/IncomingRev+Blobs.cc, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/Puller.cc, Replicator/Pusher+Attachments.cc, Replicator/Pusher+Revs.cc, Replicator/Pusher.cc, Replicator/Replicator.cc, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
CBL-3441 : integrate getCollections
CBL-3285, CBL-3280, CBL-3281, CBL-3286, CBL-3287, CBL-3284 : miscellaneous BLIP messages
Notes: with this PR, Replicators start to work with named collections in the simplest fashion: single shot Push or Pull (not mixed), without filters or callbacks.
=> Replication of named collections

LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/DataFileTest.cc
SQLite is case insensitive, so the algorithm is a simple one, add a backslash before any capital letter in a collection name.  The reverse is also simple, since backslash is not an allowed character for a collection, the backslashes can simply be removed.
=> CBL-3195: Mangle table names for case sensitivity

C/tests/c4Test.cc, C/tests/c4Test.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorCollectionTest.cc
* Add a test for  CBL-3492, which has a fix in https://github.com/couchbase/couchbase-lite-core-EE/pull/24.
* Moved getCollection() and addCollDocs() from ReplicatorCollectionTest to c4Test, and renamed addCollDocs() to addDocs().
=> CBL-3492 : Add C API test for syncing a named collection

C/include/c4ReplicatorTypes.h, REST/RESTListener+Replicate.cc, Replicator/ChangesFeed.cc, Replicator/Checkpointer.cc, Replicator/Checkpointer.hh, Replicator/IncomingRev.cc, Replicator/Puller.cc, Replicator/ReplicatorOptions.hh, Replicator/c4Replicator.cc, Replicator/c4ReplicatorHelpers.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh, Xcode/LiteCore.xcodeproj/project.pbxproj
Following options in C4ReplicatorParameters are moved to collection specific area:
- pushFilter and validationFunc are moved to C4ReplicationCollection as pushFilter and pullFilter.
- fleece properties of keys kC4ReplicatorOptionDocIDs and kC4ReplicatorOptionChannels are moved from C4ReplicatorParameters::optionsDictFleece to C4ReplicationCollection::optionsDictFleece.
Added C4ReplParamsDefaultCollection as subclass of C4ReplicatorParameters to help migrate C4ReplicatorParameters to the new collection-aware one.
=> CBL-3424 : collection specific callbacks, options

C/tests/c4Test.cc, Replicator/tests/ReplicatorCollectionTest.cc
* Fixed wrong push mode in runPushPullReplication().
* Fixed using wrong db in addDocWithAttachments.
* Fixed memleak in purgeAllDocs().
* Fixed Invalid sequence numbers in PUSH and PULL cases.
* Fixed Attachment and Resolve Conflict tests
* Broke reset checkpoint with push-and-pull test into push test and pull test separately.
**Note:**
* CBL-3500 : Only reset checkpoint with push test is disabled.
* CBL-3501 : Need incremental continuous sync tests which will full tests continuous replicators and their doc observers or changes feed.
=> Fix various issues in ReplicatorCollectionTest

Replicator/Inserter.cc, Replicator/Inserter.hh, Replicator/tests/ReplicatorCollectionTest.cc
* Updated Inserter::insertRevisionNow to make auto purge collection aware.
* Lazily cached the collection pointer inside the Inserter instead of trying to get it everytime from the insertion DB.
* Added ExpectingExceptions to the tests to avoid XCode exception breaking point.
* Note : AutoPurge requires integration testing with SG
=> CBL-3487 : Make autoPurge collection aware

jenkins/build_server_win.ps1
Also stop Win32 testing all together since this platform will be removed
=> CBL-3497: Add ARM64 as a Windows build option

Replicator/Worker.hh
The bug is caused by a mistake when migrating to collection-aware.
=> CBL-3526 : Continuous Pull Replicator went to stopped instead of idle

C/Cpp_include/c4Database.hh, Crypto/SecureDigest.cc, Crypto/SecureDigest.hh, Replicator/Checkpointer.cc
Since these are all new checkpoints they can change arbitrarily, so make all new checkpoints SHA-256 as well
=> CBL-501: Incorporate directional information in checkpoint ID

Xcode/build_setup.sh
Specified architectures based on $ARCH set by xcode.
Most of the time $ARCH will be "arm64 x86_64" so $MAC_ARCH is "x86_64;arm64".
NOTE: This is for fixing PR-Validation Failure as missing arm64 symbols when building CBL-C for the iOS Simulator:
http://mobile.jenkins.couchbase.com/blue/organizations/jenkins/_cbl_github_pipeline%2Fcouchbase-lite-C/detail/PR-331/1/pipeline/11
=> Specify build archs for iOS simulator build

Replicator/ChangesFeed.cc, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/Replicator.cc, Replicator/ReplicatorOptions.hh, Replicator/RevFinder.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorLoopbackTest.cc
For example, if the active side has more collections in the list than the passive one there needs to be a check that we are not running off the end of the passive side collection list.  Also clean up the code a bit to try to make it approachable for anyone seeing it for the first time.
Add in some mismatched collection test scenarios.
=> CBL-3512: Fix some bugs regarding mismatched collections

C/Cpp_include/c4Observer.hh, C/c4.exp, C/c4CAPI.cc, C/c4Observer.cc, C/c4_ee.exp, C/include/c4Observer.h, C/scripts/c4.txt, C/tests/c4CppUtils.hh, C/tests/c4ObserverTest.cc, C/tests/c4ThreadingTest.cc
⚠️ c4dbobs_create and c4docobs_create REMOVED
⚠️ c4dbobs_createOnCollection and c4docobs_createWithCollection signature change (C4Error added)
=> CBL-3599: Handle deleted collections gracefully when creating observers

C/c4Observer.cc, C/tests/c4ObserverTest.cc, LiteCore/Database/SequenceTracker.cc, LiteCore/Database/SequenceTracker.hh, LiteCore/tests/SequenceTrackerTest.cc
This is a 2 part fix in which
1. The observers now retain their collections, since there is no communication about a collection deletion to its observer.  This meant that deleting the collection left a dangling pointer there.
2. The sequence tracker inside of the observer notifiers is a pointer now so that it can be set to null in the case of collection invalidation.  Otherwise, the notifier destructor attempts to use the now invalid tracker inside the invalid collection and causes an exception and/or crash.
=> CBL-3602: Freeing observers after deleting collection was crashing

Replicator/Replicator.cc
The replicator class does not use collection index since it is a hub for the other per collection workers.  Instead, use the index variable from the loop when finding unresolved conflicts.
=> CBL-3625: Incorrect use of collectionIndex() in _findExistingConflicts

LiteCore/Database/CollectionImpl.hh
loggingIdentifier uses the database, which is null on a closed collection
=> CBL-3603 CBL-3604 CBL-3605 CBL-3606: Crash when closing an already closed collection

LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/QueryTest.hh
Note that user-created scope or collection cannot be led by underscore.
Also fixed a bug when collection names include upper case letters.
=> CBL-3538 : allow "_default.collection_name" as valid collection path.

C/Cpp_include/c4Collection.hh, C/c4CAPI.cc, C/tests/c4DatabaseTest.cc, LiteCore/Database/Housekeeper.cc, LiteCore/Database/Housekeeper.hh
Part of this involved making sure that the input collection was valid, and so extended that protection to (almost) the entire C API involving collections
:note: There is a weird issue on Linux with calling enqueue from the Housekeeper constructor.  If there is an enqueue call there then `_housekeeper = new Housekeeper(this)` in CollectionImpl will end up somehow with a corrupted object (invalid ref count even though there is literally no place in there which supposedly touches the ref count).  This causes a crash in `_careful_retain`.  The only choice was to move the logic later, and retain the collection as a Housekeeper member until that time.
=> CBL-3626: Eliminate hang when calling setExpiration in a transaction

C/Cpp_include/c4Certificate.hh, C/c4CAPI.cc, C/c4Certificate.cc, C/include/c4Certificate.h, Crypto/Certificate.hh, Crypto/CertificateTest.cc, Crypto/PublicKey+Apple.mm, Crypto/PublicKey+Windows.cc
Added functions to check if a certificate exists in the persistent key-store.
May still need testing in Windows as I cannot currently do that myself, and the solution required two different functions be implemented, one for Mac and one for Windows.
I've modified some tests in `Crypto/tests/CertificateTest.cc` to use `!Cert::exists()` rather than `Cert::load() == nullptr`, and all tests are passing in MacOS.
=> CBL-932: add function to check if certificate exists

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParser.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/LiteCoreTest.hh, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryTest.cc
By N1QL grammar, collection names and scope names are IDENTIFIERs, which can be quoted, just like the property names in a property path. That is, we may say, "SELECT ssn FROM `human.resource`.payroll", where "human.resouce" represents the scope name in the grammar, and "payroll" represents the collection name. Currently, however, the parser collapses them into one collection path, "human.resource.payroll". The original scope/collection names are not recoverable. Usually, this is not a problem, because no matter where you put the divide, the part with dot in it won't qualifiy as a scope or collection name in the later phase of the parser. However, the loss of the original intent of the N1QL expression can cause a problem. If unqualified -- not led by a scope name -- a collection name may …
=> CBL-3009 : quoting collection names.

Replicator/c4ReplicatorHelpers.hh, Replicator/tests/ReplicatorAPITest.cc
Add tests for pending document IDs for existing and non-existing collections.
Modify helper struct in c4ReplicatorHelpers.hh to be more generic, now can create it for any collection - not just default.
Had to modify some usages of the above helper struct as a variable name changed.
=> Add tests for pending document IDs with collections

Replicator/Replicator.cc, Replicator/Replicator.hh
With 3.1, the first message that the client sends to the server is "getCollections". This allows the server to align the list of collections with order of the client. For 3.0, there is not a clear first message.
=> CBL-3442: handle legacy 3.0 client

C/tests/c4Test.cc, C/tests/c4Test.hh, Replicator/ReplicatorOptions.hh, Replicator/c4ReplicatorHelpers.hh, Replicator/tests/DBAccessTestWrapper.cc, Replicator/tests/DBAccessTestWrapper.hh, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
Changed ReplicatorLoopbackTest to use a named collection rather than the default collection.
Had to change usages of functions that use default collection to their named collection variants.
Some functions also needed new overloads that allow them to be used with named collections.
Because of [this change](https://github.com/couchbase/couchbase-lite-core/blob/master/Replicator/Checkpointer.cc#L239-L250) to how checkpoint IDs are generated for named collections, the expected ID in checkpoint validation tests had to be changed.
=> CBL-3531: Change ReplicatorLoopbackTest to use named collections

LiteCore/Support/WeakHolder.hh, Networking/BLIP/BLIPConnection.cc
The cause of this bug is in WeakHolder -- it currently works only if the callback it invokes is synchronous. We fix it by holding an extra strong reference inside WeakHolder.
=> CBL-3624: double free of BLIPIO

LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh
Currently, `RevTree._insertedData` is copied *as is* when copying a `RevTree`.
Why is this a problem?
When a document is repeatedly updated, `Rev`s start to be purged eventually. Also, `Rev` bodies that aren't needed anymore are removed.
`RevTree._insertedData` is only ever added to and copied, keeping more and more data unnecessarily alive with each update. This data occupies memory, and the work required to copy `RevTree._insertedData` starts to dominate save operations.
This is currently making the [fast path](https://github.com/blaugold/couchbase-lite-core/blob/b5cb97c26a8d392b95afc33e161f666e30e554fe/C/c4Document.cc#L209-L224) of `C4Document::update` worse than the slow-path after a few updates.
This change keeps track of which data in a `Rev` is owned by `RevTree._insertedData` and …
=> Prevent unnecessary growth of `RevTree._insertedData`

CMakeLists.txt, cmake/generate_edition.cmake, cmake/repo_version.h.in
This avoids hardcoding git path, among other things, and can take advantage of the cross platform nature of cmake
=> CBL-3707: Generate version from CMake instead of script

C/c4CAPI.cc, C/tests/c4DatabaseTest.cc
CAPI functions using default collection can pass nullptr to other functions if default collection has been deleted, adding call to returnIfCollectionInvalid in these functions stops this from causing any crashes.
Also add tests which call all these functions, after deleting default collection, to reproduce the issue and ensure no crashes occur.
=> CBL-3706: Add calls to returnIfCollectionInvalid to CAPI functions.

C/tests/c4Test.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
Made ReplicatorLoopbackTest::_conflictHandler collection-aware.
The first commit is from my CBL-3747 solution, couldn't repro this issue without it.
Therefore this PR also solves CBL-3747.
=> CBL-3748: Continuous Push/Pull test causing assertion failure

Replicator/tests/ReplicatorCollectionSGTest.cc
Modify an error parameter so that C4Error is initialized properly.
=> CBL-3793: CollectionSGTest "Resolve Conflict SG" C4Error uninitialized

LiteCore/Query/SQLiteQuery.cc
* Reported in https://github.com/couchbase/couchbase-lite-C/issues/373.
* The mem leak is caused by not releasing the result dict when parsing the N1QL syntax without FROM.
* Fixed the issue by putting the release in the DEFER block to ensure the release.
=> CBL-3817 : Fix mem leak when creating SQL++ Query without FROM

LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh
* Port fix from the master branch (https://github.com/couchbase/couchbase-lite-core/commit/7b47459416ae572fa5b884bd8c690195acd82986) for 3.0.6 MR.
* The following message is copied from the original PR (https://github.com/couchbase/couchbase-lite-core/pull/1572)
> Currently, `RevTree._insertedData` is copied *as is* when copying a `RevTree`.
> 
> Why is this a problem?
> 
> When a document is repeatedly updated, `Rev`s start to be purged eventually. Also, `Rev` bodies that aren't needed anymore are removed.
> `RevTree._insertedData` is only ever added to and copied, keeping more and more data unnecessarily alive with each update. This data occupies memory, and the work required to copy `RevTree._insertedData` starts to dominate save operations.
> 
> This is currently making the [fast …
=> CBL-3831 : Prevent unnecessary growth of `RevTree._insertedData` (Port)

LiteCore/Support/WeakHolder.hh, Networking/BLIP/BLIPConnection.cc, Replicator/Replicator.cc, Replicator/Replicator.hh
The cause of this bug is in WeakHolder -- it currently works only if the callback it invokes is synchronous. We fix it by holding an extra strong reference inside WeakHolder.
=> CBL-3704: porting 3624, double free of BLIPIO (#1575)

C/tests/c4DatabaseTest.cc, LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/KeyStore.hh
Wrote test to reproduce issue with some help from Blake.
Fixed issue (there was an assertion where there shouldn't be, so a function was not doing what it said it should).
Ran all LiteCore C and Cpp tests, all passing.
=> CBL-3824: Re-opening a database with an Index causes failure

Replicator/c4ReplicatorImpl.hh, Replicator/tests/ReplicatorAPITest.cc
It is a bit confusing to understand the original intent, but the signed 64-bit representation of the value is clamped between 0 and UINT_MAX so if a very high ( > int64 max ) value is passed, the signed representation becomes negative and therefore falsely clamps to zero instead of UINT_MAX
=> CBL-3872: Setting a very high maxRetry turns into zero

Replicator/Replicator.cc, Replicator/ReplicatorOptions.hh, Replicator/Worker.cc, Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.cc
Changed Options::CollectionOptions::collectionPath to collectionSpec.
This has resulted in fewer conversions between path and spec, as most usages are of collectionSpec rather than collectionPath.
There was another suggestion in the ticket to make the `collectionOpts` vector private, but after attempting this I think it is unfeasible, or at least out of scope, as there are many usages in tests that directly access and modify the vector in a complex way.
=> CBL-3494: Change Options to use collectionSpec instead of collectionPath

C/tests/CMakeLists.txt, C/tests/c4PerfTest.cc, CMakeLists.txt, Networking/WebSockets/BuiltInWebSocket.hh, Replicator/tests/SG.hh, Xcode/xcconfigs/C4Tests.xcconfig
Note: Not automated yet and so it is tagged PerfManual instead of Perf.  It also requires one API that is not exposed in production to be exposed so that web socket functionality is available.
=> CBL-3033: Add replicator push and pull performance test

Replicator/c4ReplicatorImpl.hh, Replicator/tests/ReplicatorAPITest.cc
I've changed `c4ReplicatorImpl::onStateChanged` so that errors are only logged when `status.level` <= kC4Offline.
=> CBL-3010: LiteCore delivers unrecoverable error in BUSY state

C/include/c4ReplicatorTypes.h, Networking/HTTP/HTTPLogic.cc, Networking/HTTP/HTTPLogic.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/BuiltInWebSocket.hh, Replicator/tests/ReplicatorSGTest.cc
* Updated BuiltInWebSocket and HTTPLogic to do preemptive auth by default with an option for doing challenge based auth.
* This change is required by CBL-C to do basic auth preemptively to avoid the issue that users can get authenticated as a GUEST user when they don't specify credentials.
=> CBL-4022 : Update BuiltInWebSocket to do preemptive auth by default

Networking/HTTP/CookieStore.cc, Replicator/tests/CookieStoreTest.cc
Modified cookie date parsing to accept any number of formats.
Added GCLB cookie date format and ANSI C `asctime()` format.
Added cookie tests for GCLB and ANSI C date formats.
=> CBL-3949: Support GCLB Cookies

Replicator/tests/ReplicatorCollectionSGTest.cc
docIDs was being initialised with only docIDs[0]
=> CBL-4070: Fix "Pull multiply-updated SG" bug

Replicator/ReplicatorOptions.hh, Replicator/c4Replicator.cc, Replicator/c4ReplicatorImpl.hh, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorCollectionSGTest.cc
- testing nonexistent collections.
- testing bad configurations. (Also made C4Replicator's error checking more consistent)
- test that does Push, Pull, and Push/Pull, with respective collections.
- test Auto Purge w/ and w/o Filter with regard to different collections.
- test pushing to Default collection when it is not in the SG config.
=> CBL-4075: Add more multi-collection tests.

LiteCore/Database/DatabaseImpl.cc, LiteCore/Database/TreeDocument.cc, Replicator/Pusher.cc, Replicator/ReplicatorTuning.hh, Replicator/RevFinder.cc, Replicator/tests/ReplicatorCollectionSGTest.cc
With this change, we will now keep ~100~ 50 revs in the history of a doc, rather than 20. This shouldn't make a huge impact on storage requirements, because we only keep bodies for the current rev, and the last rev we synced with SG.
~With this current implementation, if the client has somehow made > 100 revisions since they last synced, SG will receive a rev list with gap. I can change this so we give SG the random revIDs we generate (I've tested the random revIDs, and they're fine). But I'm not sure if we want to do that, or just allow the warning to happen for > 100 revisions because if a customer is making > 100 revisions between syncs frequently, that may be a sign of another problem.~
With this implementation, if the client has made > 50 revisions since they last synced, the gap in …
=> CBL-2694: Prevent rev list gaps

LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/Support/StringUtil.cc, LiteCore/Support/StringUtil.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/ReplicatorTypes.hh, Replicator/Worker.cc, Replicator/Worker.hh
Make log functions inline instead of macro.
Add log overrides for Worker that insert collection info.
Add new log functions for Replicator that take collection index as a parameter.
Add format() override that takes format string as a std::string.
I've run the tests and reviewed the logs, all log types that were in the ticket now have collection info. I've also performance tested using unix `time` command, there seems to be no performance impact of changing the log functions from macro to virtual inline, and using overrides of the virtual functions.
=> CBL-4096: Replicator logs collection info

LiteCore/Query/SQLiteQuery.cc
We hit a problem that a boolean parameter assigned to TRUE picked a document in the db of which the corresponding property is FALSE. Currently we pass the boolean parameter to SQLite with double 1.0/0.0, and boolean properties in the document are integer. It does not have problem most of the time -- and it should not have problem -- to compare "1.0 = 0", but in a particular Jenkins build machine, it yields TRUE. I verified that the query worked after changing it to int.
=> CBL-3871: QueryParams fails with boolean parameter.

jenkins/CMakeLists.txt
However, only Android is using a lower version for this branch, so make an exception for it
=> Only Linux desktop needs CMake 3.19+

jenkins/build_server_unix.sh
To avoid issues with consuming the LiteCore.xcframework in .NET
=> Preserve symlinks in the build packages

Xcode/xcconfigs/Project.xcconfig
* For iOS platform that builds LiteCore into the platform binary, the version number set here will be the LiteCore version number when calling c4_getVersion().
* There is also a unit test in iOS that checks whether LiteCore version is the same as iOS version. So without this change, that unit test is failing.
=> Bump the default version in xcconfig to 3.2.0

Crypto/PublicKey+Apple.mm
* Instead of creating the SecTrust with just a leaf cert, create it with the cert chain received from the server.
* Update sockpp submodule to get the [fix](https://github.com/couchbasedeps/sockpp/pull/12) that passes the cert chains to the root-cert-locator instead of just the leaf cert.
=> CBL-4237 : Create SecTrust with certificate chain

Crypto/PublicKey+Apple.mm
* Port the [fix](https://github.com/couchbase/couchbase-lite-core/commit/91f5b72a4cde239b3f759b39748f355b62b7278b) from release/3.1 branch.
* Instead of creating the SecTrust with just a leaf cert, create it with the cert chain received from the server.
* Update sockpp submodule to get the parallel fix that passes the cert chains instead of just the leaf cert.
=> CBL-4246 : Port Create SecTrust with certificate chain Fix

cmake/generate_edition.cmake
**Problems :**
* `git branch —show-current` option is not available on Centos7 machine which has git v.1.8.3.1. The `--show-current` option is available from git v2.2.2.
* When building LiteCore on Jenkins, the HEAD is always detached so the branch name doesn't exist. As a result, the `GitBranch` in the generated `repo_version.h` will be either "" or "< unknown branch >" on linux platform due to `--show-current` option is not available. However, when looking at `c4_getVersion()` function in `c4Base.cc`, the expected value for the detached HEAD is "HEAD" otherwise the "" or "unknown branch" will be shown in the version info as the following examples:
```
"3.1.0 (:09f2cd67+)"  // For all other platforms
"3.1.0 (<unknown branch>:09f2cd67+)" // For linux - CBL-C.
```
**Fix :**
* Use …
=> CBL-4236 : Use git rev-parse to get current branch name

cmake/generate_edition.cmake
Ported the fix (5ee8ac4139ae38705607172b3599d553a485b167) from release/3.1 branch.
**Problems :**
* `git branch —show-current` option is not available on Centos7 machine which has git v.1.8.3.1. The `--show-current` option is available from git v2.2.2.
* When building LiteCore on Jenkins, the HEAD is always detached so the branch name doesn't exist. As a result, the `GitBranch` in the generated `repo_version.h` will be either "" or "< unknown branch >" on linux platform due to `--show-current` option is not available. However, when looking at `c4_getVersion()` function in `c4Base.cc`, the expected value for the detached HEAD is "HEAD" otherwise the "" or "unknown branch" will be shown in the version info as the following examples:
```
"3.1.0 (:09f2cd67+)"  // For all other platforms …
```
=> CBL-4256 : Use git rev-parse to get current branch (Port)

REST/RESTListener.cc, REST/RESTListener.hh
The error occurs When the database name contains dots and URL parser takes the suffix after the dot as the collection, which is not valid in this context. Since the P2P protocol only uses the database, we simply take the whole string in the path as the name of the database which may contain dots.
=> CBL-4254: P2P tests giving invalid collection error

.git-blame-ignore-revs, README.md
A follow-up to CBL-4174, created a file which contains the commit hash. This can be used to ignore the commit in your local git with: 
```shell
git config blame.ignoreRevsFile .git-blame-ignore-revs
```
I have added these instructions to the README also. (Not sure if there's a more suitable place for them).
=> CBL-4255: Add git blame ignore file

REST/RESTListener.cc, REST/RESTListener.hh
The error occurs when the database name contains dots and URL parser takes the suffix after the dot as the collection, which is not valid in this context. Since the P2P protocol only uses the database, we simply take the whole string in the path as the name of the database which may contain dots.
Ported from release/3.1
=> CBL-4254: P2P tests giving invalid collection error (#1715)

LiteCore/Support/Logging.hh, Replicator/Replicator.hh, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/tests/ReplicatorCollectionTest.cc
The issue was injecting the pre-formatted collection string (i.e. `{Coll#1}`) into the format string. I've fixed that by using C++ variadic templates to inject an extra argument to the logging functions (you can't do that with C variadic args). Now the function `formatWithCollection()` injects the collection format specifier `{Coll#%i}` into the format string instead.
@borrrden uncovered another issue. Due to the way that LogEncoder caches strings so it knows which ones don't need repeating in the log file, the temporary string that `formatWithCollection()` was creating was breaking that cache (as the cache compares pointers rather than strings, for efficiency). I've added a cache for these format strings to `Worker`, and now the LogEncoder's cache is working as expected.
=> CBL-4247: Replicator binary logs with collections cannot be decoded

Replicator/DBAccess.cc
This only happens on Windows, seemingly, and the only theory I have is that there is an optimization issue that causes some stale reads of a variable.  The details of the issue is that when reading the Fleece shared keys out of the "remote" db in a db to db pushpull replication, the number of keys in the copy of the shared keys object is 0 instead of what it should be.  This causes a faulty check for "unchanged" shared keys (memory address equal, and count > initial count) which in turn encodes incorrect keys onto the document.
This change seems to fix it, though it is unclear why.  The only theory I have is that reading the "count" variable first is forcing a re-evaluation which then uses the correct value when copying.
=> CBL-4288: Data getting corrupted during PushPull collection replication

LiteCore/Storage/SQLiteKeyStore.cc
Compared with 2.8, we added a process of housekeeper to keep track of expired documents. To do it, we need to find out the closest exipration time, by SQL query, SELECT MIN(expiration) from kv_default". It turned out it's quite expensive as most docs do not have expiration field (= SQLite NULL). By passing this fact to the query, we got return nearly instantly.
=> CBL-4325: Opening the upgraded database from 2.8 to 3.0.2 is slow

C/Cpp_include/c4Document.hh, C/c4.exp, C/c4CAPI.cc, C/c4_ee.exp, C/include/c4Document.h, C/scripts/c4.txt, LiteCore/Database/CollectionImpl.hh, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RawRevTree.hh, LiteCore/RevTrees/RevTree.cc, LiteCore/RevTrees/RevTree.hh, Replicator/DBAccess.cc, Replicator/Pusher+Revs.cc, Replicator/ReplicatedRev.hh, Replicator/tests/ReplicatorCollectionSGTest.cc
We will remember if a doc is rejected in push, and provide a new API, c4doc_isRevRejected() to query it. This function is designed to aid DocumentEndedCallback in resolving conflicts with the current revision that was rejected.
=> CBL-445: After doc rejected in push, doesn't pull newer revisions

C/tests/c4Test.hh, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/tests/ReplicatorCollectionSGTest.hh, Replicator/tests/ReplicatorLoopbackTest.hh, Replicator/tests/data/start_server.sh
~~Attempted fix ReplicatorLoopbackTest flaky failure. Made DB names in tests random (based on time prefix), not sure if this will actually fix anything.~~
~~Fix collection log format cache flaky failure:~~
~~- There was a flaky failure in `formatWithCollection()` that appeared very occasionally when running certain tests, seemed related to string allocation. After this change, I haven't seen the same failure again.~~
~~I have run all CppTest with these changes, all passing.~~
See recent commits/comment
=> CBL-4368: ReplicatorLoopbackTest flaky failure

LiteCore/Storage/SQLiteKeyStore.cc
Compared with 2.8, we added a process of startHousekeeping to keep track of expired documents. To do it, we need to find out the closest exipration time, by SQL query, SELECT MIN(expiration) from kv_default". It turned out it's quite expensive as most docs do not have expiration field (= SQLite NULL). By passing this fact to the query, we got return nearly instantly.
Ported from release/lithium, CBL 4325
=> CBL-4375: Opening the upgraded database from 2.8 to 3.1 is slow

C/tests/c4DatabaseTest.cc, C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Storage/BothKeyStore.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/QueryParserTest.cc
With 3.1, as we open a database of old version, we will move all deleted docs to a separate database table. For huge database, say a database of gigabytes, it may take a long time. We are proposing here to skip the migration of the deleted docs in the default collections as the database is opened. This change violated the post-condition after the database is opened that all the normal keystore does not contain deleted docs. We rollback commit f375a7fbbce062b7f3058a (that added the dual-keystore feature) with regard to the default collections and adjust the affected test cases.
*warning* the violation of the above post condition broke the test, "Database Upgrade From 2.7 to Version Vectors", c.f. CBL 4382. I disabled it in this PR.
=> CBL-4377: Not moving deleted docs when open database prior 3.1

Networking/HTTP/HTTPLogic.cc
When using proxy, the request target in the start line of the HTTP message is the full URL instead of just the URL path and the URL scheme should be http / https instead of ws / wss.
=> CBL-4398 : Fix URL scheme in HTTP message when using proxy

REST/tests/CertHelper.hh
Potentially a fix for CBL-2985, but can't be certain.
=> CBL-4379: CertHelper leaves persistent certs in the keychain

Crypto/CertificateTest.cc, LiteCore/tests/LiteCoreTest.hh
Avoid the flaky failure of "Cert already exists" by adding randomness to the cert parameters.
=> CBL-4407: "Persistent cert chain" test flaky failure

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg
PR is merged on `snej/peg` which makes sure tool doesn't generate code with '__'
Updated n1ql.leg to remove '__' and make compatible with tool changes.
Re-generated n1ql.cc using updated tool and n1ql.leg.
I have run the N1QL Parser tests to verify, and all is good.
There is one notable change in the way to use n1ql.leg, which is the scenarios where you would use `_`, you should instead use `y_`.
=> CBL-4351: Generated file n1ql.cc violates C++ reserved identifiers

Networking/HTTP/HTTPLogic.cc
* Backported from https://github.com/couchbase/couchbase-lite-core/commit/dd8e5162d96db0c0e5db07b81c630c9a4147eaaa in release/3.1 branch.
* When using proxy, the request target in the start line of the HTTP message is the full URL instead of just the URL path and the URL scheme should be http / https instead of ws / wss.
=> CBL-4388 : Fix URL scheme in HTTP message when using proxy

REST/tests/CertHelper.hh
Make sure CertHelper.hh can compile in C4Tests
=> CBL-4436: C4Tests build error outside of Xcode

LiteCore/Storage/SQLiteKeyStore.cc
Compared with 2.8, we added a process of startHousekeeping to keep track of expired documents. To do it, we need to find out the closest exipration time, by SQL query, SELECT MIN(expiration) from kv_default". It turned out it's quite expensive as most docs do not have expiration field (= SQLite NULL). By passing this fact to the query, we got return nearly instantly.
Ported from release/lithium, CBL 4375
=> CBL-4326: Opening the upgraded database from 2.8 to 3.1 is slow (#1736)

REST/tests/RESTListenerTest.cc, Replicator/tests/SGTestUser.hh, Replicator/tests/data/sg_setup.sh
Add sync functions to sg_setup script.
Remove assertions from SGTestUser because some tests caused it to fail. 
Change test tags of a test that shouldn't be grouped with the other 'ReplicatorCollectionTest's.
=> CBL-4462: sync function missing from sg_setup script

C/include/c4ReplicatorTypes.h, Networking/HTTP/HTTPLogic.cc, Networking/HTTP/HTTPLogic.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/BuiltInWebSocket.hh, Replicator/tests/ReplicatorWalrusTest.cc
* Updated BuiltInWebSocket and HTTPLogic to do preemptive auth by default with an option for doing challenge based auth.
* This change is required by CBL-C to do basic auth preemptively to avoid the issue that users can get authenticated as a GUEST user when they don't specify credentials.
=> CBL-4024 : Update BuiltInWebSocket to do preemptive auth by default

C/c4CAPI.cc, C/c4Private.h, C/tests/c4AllDocsPerformanceTest.cc, C/tests/c4CollectionTest.cc, C/tests/c4DatabaseEncryptionTest.cc, C/tests/c4DatabaseInternalTest.cc, C/tests/c4DatabaseTest.cc, C/tests/c4DocumentTest.cc, C/tests/c4ObserverTest.cc, C/tests/c4PerfTest.cc, C/tests/c4PredictiveQueryTest+CoreML.mm, C/tests/c4QueryTest.cc, C/tests/c4QueryTest.hh, C/tests/c4Test.cc, LiteCore/Database/Upgrader.cc, LiteCore/tests/UpgraderTest.cc, LiteCore/tests/c4DocumentTest_Internal.cc, REST/tests/SyncListenerTest.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorSGTest.cc
Replaced usages of deprecated API with collection API.
Added some additional API to replace deprecated API used only by tests, there are only used by tests and not exposed publicly.
Ran all C4Tests and CppTests, all passing.
=> CBL-4199: Remove deprecated pre-collection API usages

C/include/c4Certificate.h, C/include/c4Error.h, C/include/c4ReplicatorTypes.h, C/include/c4SocketTypes.h
.NET uses a script to parse the headers and generate its binding functions programtically.  Stuff like having random things on the same line, or odd formatting, makes that a lot harder.  These changes fix some of those locations.
=> Fix some weird formatting in public headers

Crypto/PublicKey+Apple.mm
On failure of check SecTrustEvaluate, Warning level will be too much noisy, so set it to Verbose level
=> CBL-4482: Change SecTrustEvaluate log level from Error to Verbose

Crypto/PublicKey+Apple.mm, README.md
* Ported 539b8084786b09d6d99f3799a7738ad14aaadf22 and 52d835eb14539813b699f483d3a9afc01a25c0c0 from master / 3.1 branch.
* Plus, Removed base SDK check as it's not necessary and corrected issuer and serial number data type.
=> CBL-4531 : Update PublicKey+Apple to use non deprecated keychain APIs

Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/BuiltInWebSocket.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/c4RemoteReplicator.hh, Replicator/c4Socket+Internal.hh, Replicator/c4Socket.cc, Xcode/xcconfigs/REST.xcconfig
<strike>
This change opens a dedicated `C4Database` for the `BuiltinWebSocket` so that it can safely use it in the thread that is launched to establish a connection.
</strike>
This change shares the thread safe `DBAccess` of `Replicator` with `BuiltinWebSocket`.
Previously, the same `C4Database` that was used by an app was also used by the `BuiltinWebSocket`. This left the possibility of unsafe concurrent access from two threads, which could leave the database in an inconsistent state, rendering it unusable.
=> CBL-4536: Share `DBAccess` of `Replicator` with `BuiltinWebSocket`

build_cmake/scripts/broadcast_hash_update_requirements.txt, build_cmake/scripts/broadcast_stage_requirements.txt
2.x requires OpenSSL 1.1 which is not readily available on the machine running this job
=> Pin urllib3 to 1.x for broadcast script

REST/tests/SyncListenerTest.cc, jenkins/couchbase-lite-core-black-duck-manifest.yaml
As we updated master branch from 2.28.0 to 2.28.1, we fixed two parameters in SyncListenerTest.cc, c.f. commit be581d10c. We also fixed it in this commit, or the test won't pass.
=> CBL-4085: Update mbedTLS to 2.28.2+

Crypto/CertificateTest.cc, Crypto/PublicKey+Apple.mm, REST/tests/RESTListenerTest.cc, REST/tests/SyncListenerTest.cc
gC4ExpectExceptions is for the test code.
=> CBL-4532: Remove gC4ExpectExceptions usage from PublicKey+Apple

C/tests/CoreMLPredictiveModel.hh, C/tests/CoreMLPredictiveModel.mm, C/tests/c4PredictiveQueryTest+CoreML.mm, Crypto/PublicKey+Apple.mm
https://issues.couchbase.com/browse/CBL-4519
- removed API_AVAILABLE where version is less than the minimum deployment target
=> CBL-4519: Remove API_AVAILABLE annotation for macOS 10.12+ and iOS 10.0+

LiteCore/Support/Instrumentation.cc
https://mobile.jenkins.couchbase.com/job/couchbase-lite-core-apple-devices/3293/console
```
/Users/couchbase/jenkins/workspace/couchbase-lite-core-apple-devices/couchbase-lite-core/LiteCore/Support/Instrumentation.cc:39:42: error: must handle potential future platforms with '*'
17:03:41         if ( __builtin_available(iOS 12.0) )
17:03:41                                          ^
17:03:41                                          , *
17:03:41 /Users/couchbase/jenkins/workspace/couchbase-lite-core-apple-devices/couchbase-lite-core/LiteCore/Support/Instrumentation.cc:48:42: error: must handle potential future platforms with '*'
17:03:41         if ( __builtin_available(iOS 12.0) )
17:03:41                                          ^
17:03:41                                          , * …
```
=> Fix Apple build job in release

C/tests/c4QueryTest.cc, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParser.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryTest.cc
Extend SQL++ to allow,
SELECT store.customers.name FROM store.customers
SELECT store.customers.name, store2.customers.name FROM store.customers JOIN store2.customers ON store.customers.name = store2.customers.name
in addition to currently legit statements:
SELECT name FROM store.customers
SELECT customers.name FROM store.customers
With this commit, the database alias can be backquoted.
=> CBL-4253: SQL++, Allow to refer to a property with full collection name

C/include/c4Replicator.h
Added the following
```
\note This function may perform action in the calling thread that requires the transaction from the database
that was passed to the replicator instance, \p repl.
```
I merely note the fact that is critical to the user I assume that general prerequisite knowledge in using the library that they cannot open a transaction inside a transaction.
=> CBL-4600: Doc update c4repl_start

LiteCore/RevTrees/RawRevTree.cc
Added sanity check at the time we encode the rev tree to binary. I am not lifting the limit of the number revs currently in place. With this check, the "error::CorruptRevisionData" should indicate real corruption.
=> CBL-3836: Corrupt Revision Data error when saving documents

C/c4CAPI.cc, C/include/c4Listener.h, C/include/c4Query.h, LiteCore/Database/VectorDocument.hh
I hit a couple of UBSan `_Nonnull binding to null pointer` warnings while running the unit tests with Xcode 14.3. They all stem from API functions that can return NULL but whose return types are not marked `C4NULLABLE`. I've fixed these and other nearby ones I found.
=> CBL-4624: Mark return types nullable to avoid Clang UBSan warnings

LiteCore/Storage/Record.hh, LiteCore/Support/Batcher.hh
Final std::move fixes. After this is merged, master can be built with XC14.3
=> CBL-4471: Xcode 14.3 error - unqualified std::move

LiteCore/Support/LogDecoder.cc, LiteCore/Support/LogDecoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
1. There is no change in the binary loggers.
2. In the header of the decoded log file, we converted the timestamp into the UTC time, instead of the local time, to make it independent of where the binary is decoded.
3. Fixed mistaken applicatino of the time zone offset when we decode the timestamp into the local time for each line of the log.
4. Informally, we insert the timestamp to the name of log file. Meanwhile, as noted by above (2), the header of the log file includes the timestamp. We added test to ensure they are consistent.
=> CBL-4638: Decoded timestamps appear incorrect

C/c4CAPI.cc, C/include/c4Query.h, C/tests/c4DatabaseTest.cc, C/tests/c4PerfTest.cc, C/tests/c4PredictiveQueryTest+CoreML.mm, C/tests/c4QueryTest.cc, C/tests/c4QueryTest.hh
⚠️ API has changed for platforms.
Behaviour does not change, as the parameter is not used internally.
All platforms are only using default parameter, so is an easy change for the platforms.
=> CBL-4331: Remove C4QueryOptions parameter from c4query_run

Replicator/tests/ReplicatorAPITest.hh
I think I've set the proxy options appropriately, but I don't believe we have any proxy tests? So it might be good to add some alongside this PR, if possible.
=> CBL-4719: ReplicatorAPITest::options() Set proxy settings from _sg.proxy

LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
CBL-4610: Missing some log files
For CBL-4621, I added logDirectory,fileLogLevel,fileMaxSize,fileMaxCount, corresponding to path, level, maxSize, maxCount, of LogFileOptions. For CBL-4610, I added serialNo. It's a serial number for each log level. This will help us check whether a log file is missing.
=> CBL-4621: Include LogFileConfiguration details in file logs

modules/docs/pages/replication-protocol.adoc
This is of course subject to change; what I'm documenting is what's implemented so far in LiteCore's replicator, as a stake in the ground from which we can iterate.
That is: I'm not pushing this PR to define what the protocol will be, just to document what's implemented right now.
=> Updated replicator protocol docs to discuss version vectors

LiteCore/Storage/BothKeyStore.cc, LiteCore/Storage/KeyStore.hh
Use a different algorithm to enumerate a BothKeyStore when the sortOption is kUnsorted: just enumerate the live docs first, then the deleted ones. This removes the need to order the underlying enumerations, which in turn allows SQLite to use indexes when `onlyConflicts` is set.
=> Optimize unsorted enumeration of BothKeyStore

C/tests/c4DatabaseTest.cc
The underlying cause has been fixed in #711f886899b23b. We added a test case.
=> CBL-4506: Replicator starts up slow for big database

C/tests/c4QueryTest.cc, LiteCore/Query/SQLiteQuery.cc
Fixed a bug in QueryEnumerator as it tries to get the fullTextTerms.
=> CBL-4750: c4queryenum_next crashes with FTS

C/include/c4DocumentTypes.h, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/Inserter.hh
As we decide whether an attachment is referenced by a document, we first check whether the document flag, kHasAttachment, is set. This flag may be wrong when we pull a new revision by the delta body, particularly if the delta does not include blob's references but the delta source does. In this case, we must check it after the delta is applied. We fixed the bug by adding a parameter to C4DocDeltaApplier so that the callback can update the revision flag after the delta is applied.
=> CBL-4812: Attachments/Blobs got deleted after compaction&re-sync

C/c4CAPI.cc
When `c4db_getCollection` is given a nonexistent collection spec, it returns NULL but doesn't write an error to `*outError`. The caller sees a garbage C4Error value.
This happens because the implementation's call to `db->getCollection()` returns nullptr without throwing an exception. So the implementation needs to set a kC4ErrorNotFound when this happens.
=> Fix: c4db_getCollection not setting error when not found

C/tests/c4DatabaseTest.cc, LiteCore/Database/DatabaseImpl+Upgrade.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/RevTrees/VectorRecord.cc, LiteCore/Storage/BothKeyStore.cc, LiteCore/Storage/BothKeyStore.hh, LiteCore/Storage/KeyStore.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/DataFileTest.cc, LiteCore/tests/LiteCoreTest.cc
Current, the signature KeyStore::set only permits insertion of new records, and hence must pick a new sequence (updateSequence). This is right for the top leve store, namely BothKeyStore. However, to move a record from sub-store to the other one, we delete it from one and intert it to the other one while keeping the sequence. The sub-store, or SQLiteKeyStore, also inherits from KeyStore. This is why we change the signature and make updateSequence and insert seaparate and ensure the integrity at appropriate places.
=> CBL-4382: Test "Database Upgrade From 2.7 to Version Vectors" Fails

Networking/HTTP/HTTPLogic.cc, Networking/WebSockets/WebSocketImpl.cc, Networking/WebSockets/WebSocketImpl.hh, Networking/WebSockets/WebSocketProtocol.hh, Replicator/Replicator.cc
Cherry-picked CBL-4789 (from `release/3.1`).
Took a lot of manual conflict resolution because formatting changes + the enhancements I previously made to `WebSocketProtocol.hh`.
=> CBL-4802: Properly handle continuation frames from websockets

CMakeLists.txt, Xcode/build_mbedtls.sh
The Clang in Xcode 15 flags a bunch of new warnings in mbedTLS's crypto.h header:
`warning: empty paragraph passed to '\retval' command [-Wdocumentation]`
Normally mbedTLS builds with `-Werror`, so this breaks the build.
This commit sets an mbedTLS CMake option that turns off -Werror.
=> Xcode 15 build fix: work around warnings in mbedTLS

LiteCore/RevTrees/VersionVector.cc
* GNU GCC Warns about "maybe using unitialized value" i when calling this decompress(int64_t i) function from readBinary(slice data) with the unchecked dereferenced value (* operator). 
* This warning is benign as the code in decompress() already checked if the optional 'g' contains the value or not. However, this causes an error when the code is built with the GNU GCC as found when compiling CBL-C armhf with LiteCore, so need suppress it.
=> CBL-4956 : Suppress benign GCC maybe-uninitialized error

C/tests/c4DatabaseTest.cc, LiteCore/Database/DatabaseImpl+Upgrade.cc
As described in the comment I've added within the code, the issue is because `kDeleted` docs get moved to `_del` keystore when they are upgraded to VV. So when the `BothKeyStore` reaches the end of the live keystore and starts trying to iterate over the dead keystore, it will attempt to iterate again over the records which have already been upgraded.
=> CBL-4840: Test "Database Upgrade From 2.7 to Version Vectors" Fails

C/c4CAPI.cc, LiteCore/Database/Housekeeper.cc, Replicator/IncomingRev.cc, Replicator/RevFinder.cc
Identifing 5 reasons:
1. API purge, c4coll_purgeDoc
2. API purgeExpired, c4coll_purgeExpiredDocs
3. HouseKeeper expiring documents
4. SG removing, revMsg["_removed"] == true
5. SG revoking, due to the parameters of the changes message.
=> CBL-4995: Log the reasons of purging documents.

C/include/c4DocumentTypes.h, C/tests/c4DatabaseTest.cc, C/tests/c4Test.cc, CMakeLists.txt, LiteCore/Database/DatabaseImpl+Upgrade.cc, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/RevTrees/VectorRecord.cc, LiteCore/RevTrees/VectorRecord.hh, LiteCore/RevTrees/Version.cc, LiteCore/RevTrees/Version.hh, LiteCore/RevTrees/VersionVector.cc, LiteCore/RevTrees/VersionVector.hh, LiteCore/Storage/Record.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/tests/CMakeLists.txt, LiteCore/tests/VectorRecordTest.cc, Replicator/DBAccess.cc, Replicator/Pusher+Revs.cc, Replicator/Pusher.cc, Replicator/tests/ReplicatorLoopbackTest.hh, Replicator/tests/ReplicatorVVUpgradeTest.cc, Xcode/LiteCore.xcodeproj/project.pbxproj
Eliminates the cost of upgrading an existing db to version vectors. 
- Instead of converting all docs to version-vector format the first time the db is opened, it leaves them alone.
- A C4Document is opened using its existing versioning type, by default. But the new document flag kDocGetUpgraded causes its in-memory representation to be upgraded to use version vectors.
- A C4Document is upgraded on disk when it's saved (regardless of what flags it was loaded with.)
- The replicator loads docs using kDocGetUpgraded since it uses version vectors.
Most of the work here is to make the VectorRecord class -- which is always used with a VV-upgraded db -- able to load a rev-tree based doc, and by default keep its revisions identified by rev-tree IDs.
=> Zero-cost version-vector database upgrade

C/c4CAPI.cc, LiteCore/Database/Housekeeper.cc, Replicator/IncomingRev.cc, Replicator/RevFinder.cc
Identifing 5 reasons:
1. API purge, c4coll_purgeDoc
2. API purgeExpired, c4coll_purgeExpiredDocs
3. HouseKeeper expiring documents
4. SG removing, revMsg["_removed"] == true
5. SG revoking, due to the parameters of the changes message.
=> CBL-4993: Log the reasons of purging documents.

C/include/c4DocumentTypes.h, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, Replicator/DBAccess.cc, Replicator/DBAccess.hh, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/Inserter.hh
As we decide whether an attachment is referenced by a document, we first check whether the document flag, kHasAttachment, is set. This flag may be wrong when we pull a new revision by the delta body, particularly if the delta does not include blob's references but the delta source does. In this case, we must check it after the delta is applied. We fixed the bug by adding a parameter to C4DocDeltaApplier so that the callback can update the revision flag after the delta is applied.
=> CBL-4838: Attachments/Blobs got deleted after compaction&re-sync

LiteCore/Database/TreeDocument.cc, Replicator/Inserter.cc, Replicator/Replicator.cc, Replicator/tests/ReplicatorSGTest.cc
As the puller sets the latest revision on remote, we should set the flag, KeepBody, on the new revision. This will incidentally clear the KeepBody flag on its ancestors.
Also, fixed a bug of failure to assign the remote DB ID for the passive replicator.
=> CBL-5073: Update replicator to keep body only on the remote revision

LiteCore/tests/DocumentKeysTest.cc, Replicator/DBAccess.cc
Update to the enhancement in Fleece with regard to the SharedKeys. For PersistentSharedKeys, the key (Dict::Key) can be cached only if its not in a trasaction. For the general SharedKeys, the default allows the key to be cashed (or shared). However, if it's possible that the underlying document may change after the key is used, client code can disable the caching. We want to be able to cache SharedKeys from the query results, but not for the tempSharedKeys in DBAccess.
=> CBL-4547: Allow DictKeys to cache shared keys from query results

LiteCore/Database/TreeDocument.cc, Replicator/Inserter.cc, Replicator/Replicator.cc, Replicator/tests/ReplicatorSGTest.cc
As the puller sets the latest revision on remote, we should set the flag, KeepBody, on the new revision. This will incidentally clear the KeepBody flag on its ancestors. Also, fixed a bug of failure to assign the remote DB ID for the passive replicator.
=> CBL-5125: Update replicator to keep body only on the remote revision

C/include/c4IndexTypes.h, LiteCore/Database/CollectionImpl.hh, LiteCore/Query/IndexSpec.cc, LiteCore/Query/IndexSpec.hh, LiteCore/Query/SQLiteKeyStore+VectorIndex.cc, LiteCore/tests/PredictiveVectorQueryTest.cc, LiteCore/tests/VectorQueryTest.cc, LiteCore/tests/VectorQueryTest.hh, Xcode/LiteCore.xcodeproj/project.pbxproj
- Now supports Inverted Multi-Index clustering, which improves training speed a lot and can improve search quality
- Now supports PQ encoding, which shrinks the on-disk size, at the cost of search quality
- Overhauled the index spec struct; see c4IndexTypes.h.
- The vectorsearch extension changed the syntax of its config (the args to CREATE VIRTUAL TABLE) so this updates the generation of that string.
=> Added clustering and PQ to vector index options [API change]

Crypto/PublicKey+Apple.mm, Crypto/PublicKey+Windows.cc, LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteDateTimeHelpers.hh, LiteCore/Query/SQLiteFleeceUtil.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/QueryTest.hh
Borrowed some work from Jim's branch `feature/date_part_functions`. Didn't rebase because it messed with a lot of things.
All functions in the Epic https://issues.couchbase.com/browse/CBL-59 are now available in N1QL. Tests are added in this PR for those functions, and if you inspect the tests you can compare them against the PRD which is linked in the Epic.
Per our conversation with PM, I've changed the `tz` functions to use an offset (in minutes) rather than a Timezone string.
=> CBL-59: N1QL date/time functions

LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/tests/PredictiveQueryTest.cc, LiteCore/tests/QueryTest.cc, LiteCore/tests/VectorQueryTest.cc
SQLiteKeyStore::allKeyStoreNames() had a very longstanding bug, probably mine, wherein it returned the names of tables that are used as indexes -- that includes FTS, array indexes, predictive indexes, and now vector.
There was a band-aid fix for this (CBL-3824) in DatabaseImpl.cc (keyStoreNameToCollectionSpec) which only filtered out FTS indexes; others would get opened as KeyStores when the DB was reopened
and cause errors.
I put in the proper fix (tables with ":" in their names are not KeyStores), removed the band-aid, and added assertions in tests to make sure that no type of index gets misinterpreted as a KeyStore.
Fixes CBL-5369
=> CBL-5369: allKeyStoreNames() should ignore indexes

LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Storage/SQLiteDataFile.hh
The IndexSpec returned by SQLiteDataFile::getIndex() always had the default QueryLanguage JSON. This meant that, if the index was created with a N1QL expression, trying to access the expression would throw an exception because the spec tried to parse it as JSON.
I discovered this because it caused errors in the cblite tool's "info indexes" command.
(Note that the `indexes` table doesn't save the QueryLanguage, so I have to recover it heuristically by checking whether the expression begins with `[` or `{`.)
=> Fixed: SQLiteDataFile::getIndex() didn't set the QueryLanguage

LiteCore/Support/Any.hh, Replicator/tests/ReplicatorAPITest.cc
Fixes about a dozen cases of
- "Logical expression is always true"
- "Logical expression is always false"
- "Both sides of operator are equivalent"
=> Fixed some Clang static analyzer warnings

Xcode/xcconfigs/Project.xcconfig
We are bumping the iOS target version to 12.0 in Beryllium.
=> CBL-5379 : Update iOS Deployment Target to 12.0

C/tests/c4DatabaseTest.cc, LiteCore/Database/Housekeeper.cc, LiteCore/Database/Housekeeper.hh
Reason: Housekeeper::_bgdb is assigned in the actor's thread. With rapid calls of setDocumentExpiration, _doExpiration fired by the timer runs in the Timer's thread, and may not see the assignment of _bgdb.
Fix: make the callback async and run in the actor's thread to be synchronized with Housekeeper::_scheduleExpiration.
=> CBL-5259: Crash in setting Housekeeper::_doExpiration()

Replicator/Puller.cc, Replicator/Pusher.cc, Replicator/ReplicatorOptions.hh, Replicator/ReplicatorTuning.hh
Add an option to Replicator config dict to configure the changes batch size. This will enable performance testing to find the best value.
Quote from ticket:
> It would be useful to expose that even as an unsupported/hidden replicator config option so we're able to tune the batch size with the perf testing team to determine a new default value.
=> CBL-5355: Performance test changes batch sizes and reevaluate default

LiteCore/Support/Channel.hh
The hang would occur in the following scenario:
- first push sees empty queue and notify the thread pool
- second puth acquires the mutex before the woken thread. It sees non-empty queue and ends with no notify.
- the woken thread calls waitUntil which enqueues a task to another mailbox.
Fix it by always notify in Channel::push with checking for empty queue.
=> CBL-5428: The mailbox's thread-pool may hang

LiteCore/Support/LogDecoder.cc, LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc, Networking/BLIP/BLIPConnection.hh, Replicator/IncomingRev.cc, Replicator/Inserter.cc, Replicator/Puller.cc, Replicator/Pusher.cc, Replicator/Replicator.cc, Replicator/RevFinder.cc
- Logging::setParentObjectRef(parentObjRef)
- For objects derived from Worker, set parent object according to the parent relationship of Worker.
- Applied parent object for a non-Worker (Connection) to Replicator.
- Includes day in the timestamp.
- Removed brackes of domain tag in the log, namely [Sync] to Sync.
- Disabled several tests that check the logs. They will be reinstated at the end of logging enhancement effort.
=> CBL-5390: Add parentObj to class Logging

.gitignore, LiteCore/Query/SQLiteDateTimeHelpers.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc
For now this is pointing to Fleece CBL-5377 branch, so I can sanity check all of Core's CI is passing first.
Will point back to Fleece main once the matching Fleece PR is merged.
=> CBL-5377: MILLIS_TO_STRING returning UTC instead of local timezone

LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryTest.cc
Functions which now have an optional format parameter:
- STR_TO_UTC
- STR_TO_TZ
- DATE_ADD_STR
No function's output follows the format of the input. All output will be ISO8601, unless the format parameter is provided.
=> CBL-5436: DateTime optional format parameter

LiteCore/Query/SQLiteFleeceFunctions.cc, LiteCore/tests/VectorQueryTest.cc
A vector in a document or in a query parameter may now also be a base64-encoded float[] array. Server is adding support for this too.
=> Recognize vectors encoded as base64 strings

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg
Description from ticket:
A query like `SELECT * FROM _ WHERE (((((type == "6")))))` should be the same as `SELECT * FROM _ WHERE (type == "6")`. But the N1QL parser creates a new expression for every parentheses. Because the parser acts recursively, this can cause exponential slowdown. We should strip the redundant parentheses at the top-level, to avoid creating unnecessary expressions.
We must be careful not to remove all parentheses.
=> CBL-5521: N1QL Parser has exponential slowdown for redundant parentheses

LiteCore/Query/SQLiteN1QLFunctions.cc, LiteCore/tests/QueryTest.cc
Fix ROUND_EVEN.
Add test for ROUND_EVEN edge case.
=> CBL-4661: ROUND_EVEN SQL++ function returning incorrect results

C/Cpp_include/c4Query.hh, C/c4CAPI.cc, C/c4Query.cc, C/c4QueryImpl.hh, C/tests/c4QueryTest.cc
Make C4QueryObserver ref-counted. We notify the observers outside mutex to avoid callbacks recurring back to the locked mutex. This makes observers liable being destroyed as whilst callback. We bump the ref-counts before leaving the mutex.
This change causes reference cycle when the observer is enabled. Client must disable (setEnabled(false)) to break the cycle and free it when done with it.
=> Disney CBSE 16662: FOTIFY: thread_mutex crash issue

LiteCore/Support/LogEncoder.cc, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
Also we changed "[Domain]" to "Domain".
Reinstated several test cases.
=> CBL-5425: Binary Encoder to encode the (Logging) object path

LiteCore/RevTrees/RevTree.cc
This PR will probably have to sit here until Jianmin is around again, but wanted to just get it up.
I encountered this bug while trying to repro a customer issue before.
It's very difficult to reason about the logic around these flags, and revs bodies being dropped etc. But I can't find any code which ensures the remote rev body is kept. I'm pretty sure there are cases where the body can be dropped.
It needs to be kept to make sure delta sync is working.
I think this is a good way to ensure it will be kept.
=> CBL-5450: Remote rev KeepBody flag could be cleared accidentally

LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Support/Extension.cc
The extension library won't auto extract onto the Android device unless it is prefixed with "lib" but the extension loading process needs to accommodate that.
=> Part of CBL 5579 in order to facilitate VS on .NET Android

CMakeLists.txt, Xcode/xcconfigs/Project.xcconfig
Defining `_LIBCPP_REMOVE_TRANSITIVE_INCLUDES` stops libc++'s headers from including other libc++ headers except as defined in the language standard. This is a good idea because it will catch situations where a header isn't explicitly included, which will cause build errors with other standard libs like GCC's and MSVC's.
=> Define _LIBCPP_REMOVE_TRANSITIVE_INCLUDES

LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Support/Extension.cc
Without these flags in the extended version of the API, the directory containing CouchbaseLiteVectorSearch.dll will not be searched for libomp.
=> Fix dlopen on Windows

LiteCore/Support/LogDecoder.cc, LiteCore/Support/LogEncoder.cc, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
CBL-5426: Binary Decoder to account for the new Logging object path
Also, the decoder generates outputs matching the format of plain text logs.
=> CBL-5592: Binary Encoder to encode the (Logging) object path

Networking/WebSockets/WebSocketImpl.hh, Replicator/ChangesFeed.cc, Replicator/ChangesFeed.hh, Replicator/DBAccess.hh, Replicator/IncomingRev.hh, Replicator/Inserter.hh, Replicator/Puller.hh, Replicator/Pusher.hh, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/RevFinder.hh, Replicator/Worker.cc, Replicator/Worker.hh, Replicator/c4IncomingReplicator.hh, Replicator/c4RemoteReplicator.hh, Replicator/c4ReplicatorImpl.hh, Replicator/c4Socket+Internal.hh
- Overriding LoggingClassName to avoid mangled names that c++ method of class name.
- Changed "{Coll#0}" to "Coll=0"
- Avoided "{Coll#-1}
- Lower case "repl" is changed to "PsvRepl"
- Concrete C4 Replicators, such as Remote, Incoming, Local, Replicators, are given distinct names, contrasting to lumbed name, C4Replicator.
- Calling Logging::setParentObj on Replicator at ealier time so that the full Object path showing when logs logged in the constructor.
=> Cbl 5427: Miscellaneous enhancements on Logging.

LiteCore/Support/Channel.hh
The hang would occur in the following scenario:
- first push sees empty queue and notify the thread pool
- second puth acquires the mutex before the woken thread. It sees non-empty queue and ends with no notify.
- the woken thread calls waitUntil which enqueues a task to another mailbox.
Fix it by always notify in Channel::push with checking for empty queue.
=> CBL-5431: The mailbox's thread-pool may hang

C/c4Base.cc
In this case, an uncaught exception from obj-C reached the c++ terminate handler. This is expected result. The issue is that our message describes it by "COUCHBASE LITE CORE FATAL ERROR." We remove the confusion by removing "COUCHBASE LITE CORE" in error message.
=> CBL-5454: LiteCore caught unrelated exception from UI

LiteCore/Support/LogDecoder.cc, LiteCore/Support/LogDecoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
- Use UTC time both in file logs (cherry picked from (9a09543593 and 17d342b962)
- Include Date in the timestamp.
=> CBL-5569: Text Log Files do not have date included in the log timestamp

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/N1QLParserTest.cc
This is now already in 3.1 and master branch. I copied this from the master branch PR.
=> CBL-5589: Beryllium - N1QL Parser has exponential slowdown for redundant parentheses

C/tests/c4DatabaseTest.cc, LiteCore/Database/Housekeeper.cc, LiteCore/Database/Housekeeper.hh
Reason: Housekeeper::_bgdb is assigned in the actor's thread. With rapid calls of setDocumentExpiration, _doExpiration fired by the timer runs in the Timer's thread, and may not see the assignment of _bgdb.
Fix: make the callback async and run in the actor's thread to be synchronized with Housekeeper::_scheduleExpiration.
=> CBL-5082: Crash in setting Housekeeper::_doExpiration()

C/Cpp_include/c4Query.hh, C/c4CAPI.cc, C/c4Query.cc, C/c4QueryImpl.hh, C/tests/c4QueryTest.cc
Currently, we notify the observers outside mutex to avoid callbacks recurring back to the locked mutex. This makes observers liable of being destroyed after entering the callback. We solve the problem by making C4QueryObserver ref-counted. We increment the ref-count within the mutex and decrement it after callback is done.
This change causes reference cycle when the observer is enabled. We break the cycle in c4queryobs_free by calling setEnabled(false).
C4 clients: c4queryobs_free(obs) will break the cycle.
The C++ client must call SetEnabled(false) to break the reference cycle to avoid memory leaks.
=> CBL-5631: pthread_mutex_lock called on a destroyed mutex

LiteCore/Support/Error.cc, LiteCore/Support/Extension.cc
We don't want to see the backtrace for error "UnsupportedOperation." Meanwhile, I made the error message little bit more specific, from
Unable to open extension to check version
to
Unable to open extension at path/CouchbaseLiteVectorSearch to check version
=> CBL-5599: LiteCore logging extraneous backtraces

Networking/BLIP/BLIPConnection.cc, Networking/BLIP/CMakeLists.txt, Replicator/tests/ReplicatorLoopbackTest.hh
As BLIPIO receives HTTPResponse, it passes it upstream to Connection. When doing it, it calls gotHTTResponse on _connection without checking it against null. This is okay if it's called before it is closed, for we reset it to null when onClose is called. To guard agaisnt this situation, we check it before calling it. To avoid racing with regard to _connection, we dispatch the method to the queue.
=> CBL-5642: Null dereference crash in gotHTTPResponse

Networking/BLIP/BLIPConnection.cc, Networking/BLIP/CMakeLists.txt, Replicator/tests/ReplicatorLoopbackTest.hh
As BLIPIO receives HTTPResponse, it passes it upstream to Connection. When doing it, it calls gotHTTResponse on _connection without checking it against null. This is okay if it's called before it is closed, for we reset it to null when onClose is called. To guard against this situation, we check it before calling it. To avoid racing with regard to _connection, we dispatch the method to the queue.
=> CBL-5646: Null dereference crash in gotHTTPResponse

Replicator/IncomingRev.cc, Replicator/Puller.cc, Replicator/ReplicatorTuning.hh
Unsure on:
1. How to reliably test this in LiteCore. It relies on a document being modified directly between the "changes" and "rev" message.
2. Do we need to implement the other side of this for push replications? ie sending a replacementRev.
=> CBL-5634: NoRev enhancement with Replacement Rev in pull replication

LiteCore/Query/QueryParser.cc, LiteCore/tests/N1QLParserTest.cc
In the WHAT clause, we requlre properties to be qualified by database aliases if there are multiple data sources. However, in the ORDER BY clause, it is not necessary to require it because the result alias may uniquely identifies the property.
=> CBL-5515: Result alias can't be used the ORDER BY clause.

C/Cpp_include/c4Query.hh, C/c4CAPI.cc, C/c4Query.cc, C/c4QueryImpl.hh, C/tests/c4QueryTest.cc
Currently, we notify the observers outside mutex to avoid callbacks recurring back to the locked mutex. This makes observers liable of being destroyed after entering the callback. We solve the problem by making C4QueryObserver ref-counted. We increment the ref-count within the mutex and decrement it after callback is done.
This change causes reference cycle when the observer is enabled. We break the cycle in c4queryobs_free by calling setEnabled(false).
C4 clients: c4queryobs_free(obs) will break the cycle.
The C++ client must call SetEnabled(false) to break the reference cycle to avoid memory leaks.
=> CBL-5540: pthread_mutex_lock called on a destroyed mutex

LiteCore/Storage/DataFile.hh, LiteCore/Support/Codec.cc, LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/Support/StringUtil.cc, LiteCore/Support/StringUtil.hh, Networking/WebSockets/WebSocketImpl.cc, Replicator/Puller.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/Worker.cc, Replicator/Worker.hh
Also
- Reverted f6b93e28765c81cf6905b5d271c046715d04cf83 to reinstate checking of format string and -Wformat-nonliteral.
- Logging Coll=<collection index> using the same mechanism.
- Corrected several places where collection ID is repeated in the log.
=> CBL-5429: Logging "correlation-ID" for all logs logged by Replicator.

LiteCore/Query/SQLiteDataFile+Indexes.cc
* Cherry-pick the fix from https://github.com/couchbase/couchbase-lite-core/pull/2040.
* The column was added to the table definition in commit 5c3c854, but I forgot to add code to add the column to existing tables.
=> CBL-5776: Add 'lastSeq' column to existing 'indexes' table

LiteCore/tests/DataFileTest.cc, LiteCore/tests/VectorQueryTest.cc
Delete the database created by the fixture with DataFile::deleteDataFile() instead of deleteDatabase(dbPath). The former will close and delete and whereas the latter will wait until it is closed.
=> CBL-5778: Test "DataFile Encryption" failed in master branch

LiteCore/Query/SQLiteKeyStore+Indexes.cc, LiteCore/tests/VectorQueryTest.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, cmake/platform_base.cmake
- reference SQLiteCpp to branch 2.0.0-couchbase.
- Fix an uninitialized error. Raised a threshold for the warning that failed test of createVectorIndex. (The same threashold is used in release/3.2)
-  Fix Xcode project files: carray.c to carray.cc, carray_bind.c to carray_bind.cc
- Fix Cmake sources for the above files.
- Disable GH check on BlackDuck. !NO_BD_GITHUB
=> CBL-5779: SQLiteCpp submodule is behind 2.0.0-couchbase

LiteCore/Query/SQLiteDataFile+Indexes.cc
The column was added to the table definition in commit 5c3c854, but I forgot to add code to add the column to existing tables.
=> CBL-5777 : Add 'lastSeq' column to existing 'indexes' table

LiteCore/Support/Logging.cc
The deadlock is caused by a logging of Error in setParentObjectRef. This error is logically a case of assertion failure. The problem is this function requires the mutex that WarnError also requires and and, therefore, got locked because of non-recursive mutex.
It turned out the error was caused by mismatch of library, but we don't want it be locked when the error occurs. I scoped the mutex and moved the WarnError out of the mutex scope.
=> CBL-5784: Deadlock when setParentObjectRef is called

build_cmake/scripts/check_bd_versions.py, build_cmake/scripts/check_bd_versions_requirements.txt, jenkins/couchbase-lite-core-black-duck-manifest.yaml
release/3.1 is suddenly pointing to an orphaned commit, breaking all Helium builds.
With this PR I'm pointing it back to the correct commit on `2.0.0-couchbase`.
@jianminzhao I think this might be related to your recent breaking and subsequent fixing of the SQLiteCpp pointing to the wrong branch? Could you confirm.
=> Fix SQLiteCpp pointing to an orphaned commit

Networking/WebSockets/WebSocketImpl.cc
Simply a missed case (SOCKET_OPENED status) in the switch statement. The functions which follow (either `callCloseSocket()` or `callRequestClose()`) both expect the state to be OPENING or OPENED, so this has no side-effect.
=> CBL-5791: Socket not called to close after WebSocket PING Timeout

LiteCore/tests/QueryTest.hh, LiteCore/tests/VectorQueryTest.cc
CBL-5705: Support vector in BASE64 in vector_match() query
Added tests to have vector embeddings being base64-encoded strings.
1. all documents in the database have vector embeddings with float arrays.
2. all documents in the database have vector embeddings with base64 strings.
3. half of the documents have vector embeddings with float arrays and half with base64 strings.
=> CBL-5480: Support embedding vectors in BASE64 format

LiteCore/Query/LazyIndex.cc, LiteCore/Query/LazyIndex.hh, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Query/SQLiteKeyStore+VectorIndex.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/LazyVectorQueryTest.cc, LiteCore/tests/VectorQueryTest.cc
LazyIndexUpdater now knows the correct vector dimensions and immediately rejects vectors with the wrong size.
To enable this, I extended SQLiteDataStore::getIndex to recover vector-index options by parsing the CREATE TABLE statement from the db schema. It's not complete -- it doesn't fill in the parameters of the encoding -- but it gets the most important stuff including the vector dimensions.
Fixes CBL-5814
=> LazyIndex: reject wrong-dimensional vectors [CBL-5814]

C/c4Private.h, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Query/SQLiteKeyStore+VectorIndex.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/VectorQueryTest.cc, LiteCore/tests/VectorQueryTest.hh
The function `c4db_getIndexRows`, AKA `C4Database::getIndexRows()`, AKA `SQLiteDataFile::inspectIndex()`, now supports vector indexes. This means tests can now use it to
- Compare the vectors in the index against expected values
- More safely detect an untrained index, because all `bucket` columns will be -1.
**IMPORTANT:** This PR depends on https://github.com/couchbaselabs/mobile-vector-search/pull/56 . Until that one is merged, and LiteCore loads a vectorsearch lib that contains it, the `getIndexRows` call will fail at runtime with an error from vectorsearch.
The updated doc-comment:
```C
/** Returns the contents of the index as a Fleece-encoded array of arrays.
Each array item is an index row; its items are its column values.
Currently supports only value and vector indexes.
- In a …
```
=> Allow inspecting contents of vector index with c4db_getIndexRows()

C/tests/c4Test.cc, Replicator/ReplicatorOptions.hh, Replicator/tests/ReplicatorCollectionTest.cc
For the active replicator, we set a flag to mark it as collection-unaware if the only collection that is in the configuration is the default collction. This is so that we can connect to 3.0 SG that is not aware of the collection.
Unnecessarily, we applied the above logic to the passive replicator as well, because we will determine collection awareness of the passive replicator from the first request it receives. It poses no problem if the active replicator is also derived from Replicator. For replicating client not derived from Replicator, this causes problem if the client has only one default collection and connet to the passive replicator derived from Replicator. In this case, the collection awareness does not match and violates internal assertion.
We fixed it by applying the avove rule …
=> CBL-5798: Passive replicator incorrectly errors on collection ID in the BLIP message

LiteCore/Support/Channel.hh
The hang would occur in the following scenario:
- first push sees empty queue and notify the thread pool
- second puth acquires the mutex before the woken thread. It sees non-empty queue and ends with no notify.
- the woken thread calls waitUntil which enqueues a task to another mailbox.
Fix it by always notify in Channel::push without checking for empty queue.
=> CBL-5633: The mailbox's thread-pool may hang.

Networking/BLIP/BLIPConnection.cc, Networking/BLIP/CMakeLists.txt
As BLIPIO receives HTTPResponse, it passes it upstream to Connection. When doing it, it calls gotHTTResponse on _connection without checking it against null. This is okay if it's called before it is closed, for we reset it to null when onClose is called. To guard against this situation, we check it before calling it. To avoid racing with regard to _connection, we dispatch the method to the queue.
=> CBL-5685: Null dereference crash in gotHTTPResponse

C/tests/c4DatabaseTest.cc, LiteCore/Database/Housekeeper.cc, LiteCore/Database/Housekeeper.hh
Reason: Housekeeper::_bgdb is assigned in the actor's thread. With rapid calls of setDocumentExpiration, _doExpiration fired by the timer runs in the Timer's thread, and may not see the assignment of _bgdb.
Fix: make the callback async and run in the actor's thread to be synchronized with Housekeeper::_scheduleExpiration.
=> CBL-5639: Crash in setting Housekeeper::_doExpiration()

LiteCore/tests/LazyVectorAPITest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/VectorQueryTest.cc
Added 2 tests to contrast with non-hybrid, or pure, vectorsearches.
1. Default max_results applies only to the pure vectorsearch.
2. Giving explicit max_results to vector_match turns it to a pure vectorsearch and causes failure to find the result.
=> CBL-5805: Add tests following the latest vectorsearch and hybrid queries

C/tests/CoreMLPredictiveModel.mm, LiteCore/Support/Logging.cc, Xcode/LiteCore.xcodeproj/project.pbxproj, Xcode/LiteCore.xcodeproj/xcshareddata/xcdebugger/Breakpoints_v2.xcbkptlist, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/All.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore C Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore C++ Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore XCTests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore dylib.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore framework.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C Tests Optimized.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-EE C++ Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-iOS Tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-iOS perf tests.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/LiteCore-iOS-Carthage.xcscheme, Xcode/LiteCore.xcodeproj/xcshareddata/xcschemes/Run Clang-Format.xcscheme
- Logging.cc: `kLevelNames` shadows a static variable; renamed it.
- CoreMLPredictiveModel.mm: A new enum value caused unhandled-value errors in some `switch` statements. Added `default` cases.
- LastUpgradeCheck = 1600
- BuildIndependentTargetsInParallel = YES
- Removed duplicate source files in some targets (probably caused by incorrect git merges of the xcodeproj file)
=> Xcode 16 compatibility

LiteCore/Support/Logging.cc
The deadlock is caused by a logging of Error in setParentObjectRef. This error is logically a case of assertion failure. The problem is this function requires the mutex that WarnError also requires and and, therefore, got locked because of non-recursive mutex.
It turned out the error was caused by mismatch of library, but we don't want it be locked when the error occurs. I scoped the mutex and moved the WarnError out of the mutex scope.
=> CBL-5785: Deadlock when setParentObjectRef is called

Networking/WebSockets/WebSocketImpl.cc
* Fix WebSocket doesn't close after timeout.
=> CBL-5830: Socket not called to close after WebSocket PING Timeout

C/include/c4Index.h
This explains why CBL-5842 is actually correct behavior.
=> Added explanatory note to c4index_beginUpdate doc-comment [CBL-5842]

C/Cpp_include/c4Index.hh, C/c4CAPI.cc, C/include/c4Index.h, LiteCore/tests/VectorQueryTest.cc
`getName` and `getCollection` exist in the C++ API, but not the C API.
This PR rectifies that.
=> CBL-5793: Add missing c4 APIs for c4Index.

LiteCore/Query/LazyIndex.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLite_Internal.hh
Using SQLite::Statement::bindNoCopy() with a non-temporary Statement leaves dangling pointers in its bindings. This isn't usually a problem because the bindings get updated before the next time the statement is run ... but if the statement is still around when the db closes, the code that logs open statements will try to deref the bindings and may crash.
Since there were numerous places this needed to be fixed, I improved the `UsingStatement` helper class to clear bindings.
The change to LazyIndex.cc is to remove redundant `reset` calls; `UsingStatement` already does that.
I also added more doc-comments to SQLite_Internal.hh while I was at it.
=> Clear SQL statement bindings after use

LiteCore/Query/QueryParser+VectorSearch.cc, LiteCore/Query/QueryParserTables.hh, LiteCore/tests/LazyVectorQueryTest.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/PredictiveVectorQueryTest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/VectorQueryTest.cc
vector_match() no longer takes an optional 3rd parameter.
The limit should now be passed as the overall LIMIT of the SELECT.
Also switched to using MATCH instead of LIKE in the generated SQL, because I found MATCH is slightly more efficient.
Also, with the latest vectorsearch extension, there were a couple of test failures caused by unexpected "Untrained index..." warnings. Fixed them.
=> Removed limit param from vector_match()

LiteCore/Database/CollectionImpl.hh, LiteCore/tests/LazyVectorAPITest.cc
Also fixed a bug in CollectionImpl::createIndex, a missing "break" in switch statement.
=> CBL-5924: Cannot set C4VectorIndexOptions.numProbes = 0

LiteCore/Query/LazyIndex.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLite_Internal.hh
Using SQLite::Statement::bindNoCopy() with a non-temporary Statement leaves dangling pointers in its bindings. This isn't usually a problem because the bindings get updated before the next time the statement is run ... but if the statement is still around when the db closes, the code that logs open statements will try to deref the bindings and may crash.
Since there were numerous places this needed to be fixed, I improved the `UsingStatement` helper class to clear bindings.
=> CBL-5931: Clear SQL statement bindings after use

Replicator/ReplicatorOptions.hh, Replicator/Worker.cc
Made a white list based on the current constants of keys of repl::Options except for kC4ReplicatorAuthPassword. We only log properties in the white list.
Platform added options won't be logged because of the white-list.
=> CBL-5933: Replicator log contains auth info

LiteCore/Query/LazyIndex.cc, LiteCore/Query/LazyIndex.hh, LiteCore/tests/LazyVectorAPITest.cc
I added in the `modified` property to the IndexUpdater's `Item`, this allows us to check that all vectors have been modified in some way without checking `vector != nullptr`, because any vector set to null would break that condition.
=> CBL-5936: IndexUpdater's finish() returns an error when there are any null vector set

Replicator/tests/ReplicatorCollectionTest.cc
The reason the test occasionally fails because we assumeed that successive revisions all get replicated to the destinations, whereas replicator may skip obsolete revision, say rev-2, when rev-3 exists when the pusher turns to find the revisions to push. In our test case, we create successive revisions in intervals of 500 milliseconds. Most time, 500 ms is enough to set apart when the pusher picks the revisions. On Jenkins machine, the log shows that it found obsolete revisions when the test failed.
We modified the test success criteria: we only check that the latest revisions are replicated to the destination. This is the designed behavior.
=> CBL-5813: Flaky test, "Multiple Collections Incremental Revisions"

C/include/c4IndexTypes.h, C/tests/c4IndexUpdaterTest.cc, LiteCore/Database/CollectionImpl.hh, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser+VectorSearch.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Query/SQLiteKeyStore+Indexes.cc, LiteCore/Query/SQLiteKeyStore+VectorIndex.cc, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/tests/LazyVectorQueryTest.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/PredictiveVectorQueryTest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryParserTest.hh, LiteCore/tests/VectorQueryTest.cc, vendor/vector_search/VectorIndexSpec.cc, vendor/vector_search/VectorIndexSpec.hh
As per recent meetings & email threads, for Server SQL++ compatibility.
- There is no more `VECTOR_MATCH` function.
- `VECTOR_DISTANCE` renamed to `APPROX_VECTOR_DIST`.
- Parameters are (_vector expression_, _target vector_, [_metric_], [_nprobes_]); last two optional.
- _metric_, if given, is a case-insensitive string that must match the index's metric. Current supported values are `"EUCLIDEAN_SQUARED"`, `"L2_SQUARED"`, `"COSINE"`.
- _nprobes_, if given, overrides the value specified when the index was created.
- A non-hybrid vector query must have a `LIMIT` clause. There is no more default limit.
- A hybrid query is one with a `WHERE` clause (and a `APPROX_VECTOR_DIST` call, of course.)
- Two new metrics in the API: `kC4VectorMetricEuclidean1` and `kC4VectorMetricDot`. 
- I renamed …
=> Last-minute changes to vector search SQL++ syntax

C/tests/c4IndexUpdaterTest.cc, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParser+Private.hh, LiteCore/Query/QueryParser+VectorSearch.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/QueryParserTables.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/LazyVectorQueryTest.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/PredictiveVectorQueryTest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/VectorQueryTest.cc
- If the WHERE clause consists only of APPROX_VECTOR_DIST() being less than (or equal to) something, it's not a hybrid query.
- A WHERE clause containing APPROX_VECTOR_DIST() inside an OR clause is illegal.
- A change I made to support this (marking the FROM clause in the `_context` stack) resulted in some redundant parens being removed from generated WHERE clauses. I updated the QueryParserTests to reflect this.
=> Fixed hybrid vector search checks [CBL-5985]

C/c4Base.cc, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
Most log domains are generated from inside the library with literal string names. The are held by the language. For domains created via c4log_getDomain, we will hold the name in class LogDomain.
Also fixed a bug in test "LogEncoder levels/domains."
=> CBL-5979: LiteCore should hold the names of its log domains

LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/VectorQueryTest.cc
1. Use APPROX_VECTOR_DIST without a vector index for the specified vector expression.
2. Use APPROX_VECTOR_DIST with a vector index with unmatched distance metric.
3. Use APPROX_VECTOR_DIST on a non-hybrid query without LIMIT:
- Use APPROX_VECTOR_DIST in ORDER BY
- Use APPROX_VECTOR_DIST in WHERE
- Use APPROX_VECTOR_DIST in SELECT
4. Use APPROX_VECTOR_DIST with accurate = true
6. Use APPROX_VECTOR_DIST in a hybrid query with OR expression in WHERE clause.
7. Use APPROX_VECTOR_DIST in a non-hybrid query with OR expression in WHERE clause.
8. Use invalid num probes in the query such as 0, or negative number.
* Also fixed an error message in SQLiteDataFile.cc
=> CBL-5964: Test APPROX_VECTOR_DIST error cases

C/c4Base.cc, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
Most log domains are generated from inside the library with literal string names. The are held by the language. For domains created via c4log_getDomain, we will hold the name in class LogDomain.
Also fixed a bug in test "LogEncoder levels/domains."
=> CBL-5726: LiteCore should hold the names of its log domains

LiteCore/Support/Codec.cc
Cherry-picked 665a506 from CBL-5605.
=> CBL-5612: TLS and ZIP logs are excessive

C/c4Base.cc, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
Most log domains are generated from inside the library with literal string names. They are held by the language. For domains created via c4log_getDomain, we will hold the name in class LogDomain.
Also fixed a bug in test "LogEncoder levels/domains."
=> CBL-5978: LiteCore should hold the names of its log domains

Networking/BLIP/BLIPConnection.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/tests/ReplicatorCollectionSGTest.cc
This is an attempt at adding the logging of correlation ID, with as minimal changes as possible.
See #2105 for an example of the opposite.
=> CBL-5997: Logging correlation ID

C/include/c4DatabaseTypes.h, LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/c4BaseTest.cc
Added a flag to C4DatabaseFlags, kC4DB_DiskSyncFull. This flag is passed to DataFile::Options, which is used as we request a connection to the SQLite database.
=> CBL-6009: Provide an option to enable full sync in the database

C/tests/c4Test.cc, LiteCore/tests/LiteCoreTest.cc, Replicator/tests/ReplicatorAPITest.cc
After the replicator is stopped, it may still take some time to wind down objects Our test currently allows 2 seconds for it. This turns out not enough in situation when there are following errors,
Sync ERROR Obj=/Repl#21/revfinder#26/ Got LiteCore error: LiteCore NotOpen, "database not open"
This error is artificial. It is because we close the database as soon as the replicator goes to stopped, as opposed to when the replicator is deleted. The error follows the exception to the top frame and takes substantial time when there are many of them.
I increased 2 seconds allowance to 20 seconds. We won't always wait for 20 seconds, because the waiter polls the condition every 50ms. A situation of actual memory leak will wait for whole 20 seconds before failure.
=> CBL-6099: Test "Rapid Restarts" failing frequently on Linux

Replicator/tests/ReplicatorCollectionTest.cc
The reason the test occasionally fails because we assumeed that successive revisions all get replicated to the destinations, whereas replicator may skip obsolete revision, say rev-2, when rev-3 exists when the pusher turns to find the revisions to push. In our test case, we create successive revisions in intervals of 500 milliseconds. Most time, 500 ms is enough to set apart when the pusher picks the revisions. On Jenkins machine, the log shows that it found obsolete revisions when the test failed.
We modified the test success criteria: we only check that the latest revisions are replicated to the destination. This is the designed behavior.
=> CBL-6104: Flaky test, "Multiple Collections Incremental Revisions"

C/include/c4DatabaseTypes.h, LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/c4BaseTest.cc
Added a flag to C4DatabaseFlags, kC4DB_DiskSyncFull. This flag is passed to DataFile::Options, which is used as we request a connection to the SQLite database.
=> CBL-6120: Provide an option to enable full sync in the database

Networking/WebSockets/WebSocketImpl.cc, Replicator/c4Replicator_CAPI.cc, Replicator/c4Socket+Internal.hh, Replicator/c4Socket.cc
This reverts commit 0bac7335d5d3eaf1d4e63e4635129119eec7140a. The mission of the instrumentation has already accomplished.
=> CBL-6055: Remove c4SocketTrace as instrumentation for debugging

C/c4.exp, C/c4_ee.exp
These changes (produced by the script) should have been checked in when c4.txt and c4_ee.txt were last changed, but they weren't. Now every time I build the C tests the script regenerates these files and they show up as changed.
=> Check in updated c4.exp, c4_ee.exp

Replicator/tests/CookieStoreTest.cc
The `ExpectingExceptions` object on the stack magically tells Xcode's breakpoint on `throw` not to trigger.
=> Xcode: Don't break at an expected exception in CookieStoreTest

Replicator/tests/CookieStoreTest.cc
somehow the last commit to master (fb788161) wasn’t clang-formatted, so now any PR fails the CI formatting test.
I imagine this might have happened due to Github’s rebasing when it merged?
=> clang-format (fix broken rebased commit)

Networking/HTTP/HTTPLogic.cc
* Fixed crash when converting from address (Address) to C4Address by using the cast operator instead of casting the pointer which is not valid anymore due to the change in private variables.
* When creating an address object, used path not the full url for the path.
=> CBL-6193 : Fix address conversion for request when using proxy

LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
- LogEncoder should not have an upward dependency on LogDomain. Instead, the object path should be passed to it.
- In fact there's no need to include Logging.hh at all. As far as LogEncoder is concerned, a LogLevel is just a small integer.
- Made LogDomain::dylog static. It just required adjusting the parameter index in the `__printflike()` attribute since there is no more `this` parameter.
- Cleaned up the very weird treatment of the prefix string in dylog. It doesn't need to go through printf-style formatting at all, it just has to be copied to the output buffer. This means we don't need to suppress the compiler warning about a nonliteral format string.
=> LogEncoder cleanup

C/Cpp_include/c4Database.hh
We treat a scope ID of `nullslice` equivalently to `_default`. (See `isDefaultScope()` in DatabaseImpl.cc.)
However, C4CollectionSpec's hash and operator== didn't know about this; they just compared/hashed the scope literally. So an unordered_map<C4CollectionSpec> would consider those different values.
This meant that if you called get/createCollection once with {"_default","_default"} and again with {"_default",nullslice}, then DatabaseImpl::getOrCreateCollection would create two different C4Collection objects on the same KeyStore.
This in turn meant an observer registered on one collection instance wouldn't be notified of changes made with the other instance. Ouch.
=> Fixed C4CollectionSpec hash and equality

LiteCore/Support/Timer.cc, LiteCore/Support/Timer.hh, Replicator/tests/ReplicatorLoopbackTest.cc
Fixes a longstanding limitation that IIRC we knew about and just avoided. I couldn't avoid it in the code I'm working on, so I finally fixed it.
Manager::unschedule(), if the timer's being deleted, now checks to see if it's being called on the Manager's thread. If so, it no longer waits for the timer's `_triggered` flag to clear (which caused a deadlock.)
Instead it checks if the timer is the same as the new `_triggeredTimer` variable; if so, it clears the variable.
When control returns to the run() method, if `_triggeredTimer` has been cleared it won't clear the `_triggered` flag or check the `_autoDelete` flag.
=> Allow a Timer to destruct itself during its callback

C/tests/c4QueryTest.cc, C/tests/c4QueryTest.hh, C/tests/data/students.json, C/tests/data/students2.json, LiteCore/Query/QueryParser.cc
Added tests for multiple indexes, multi-leveled index, index with N1QL expression.
=> CBL-6156: Support Inner Unnest Query in JSON

LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh
_documentKeys is initialized lazily without protection. We fix it by call_once.
=> CBL-6169: DataFile::documentKeys() is not thread-safe

cmake/platform_linux_desktop.cmake
so that we don't have to ship libstdc++ with Core
=> CBL-6235: Statically link to libstdc++

C/include/c4DatabaseTypes.h, LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/c4BaseTest.cc, Networking/HTTP/HTTPLogic.cc
Merge from [tag 3.2.0](https://github.com/couchbase/couchbase-lite-core/commits/3.2.0/) into master
=> Merge 3.2.0 into master.

C/include/c4DocumentTypes.h, C/tests/c4DatabaseTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/RevTreeRecord.cc, LiteCore/RevTrees/SourceID.hh, LiteCore/RevTrees/VectorRecord.cc, LiteCore/RevTrees/VectorRecord.hh, LiteCore/RevTrees/Version.cc, LiteCore/RevTrees/VersionVector.cc, LiteCore/RevTrees/VersionVector.hh, LiteCore/RevTrees/VersionVectorWithLegacy.hh, LiteCore/Storage/DataFile.hh, LiteCore/Storage/Record.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/VectorRecordTest.cc, LiteCore/tests/VersionVectorTest.cc, Replicator/DBAccess.cc, Replicator/Pusher+Revs.cc, Replicator/Pusher.cc, Replicator/ReplicatorTypes.cc, Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorVVUpgradeTest.cc, Xcode/LiteCore.xcodeproj/project.pbxproj
The transition from tree-based revids to version vectors is tricky for replication, and the prior approach (adding a fake 'legacy' version when creating the vector) didn't turn out to work.
Instead, now:
1. when a doc is upgraded in memory to a VectorRecord it keeps its tree-based/legacy revids. 
2. When the doc is saved, it creates a version vector for the local Revision but also remembers the prior legacy revid. 
3. Remote Revisions keep their tree-based IDs until they're replaced by newer VV revisions (pulled or pushed).
As a result, revision histories now consist of a VV and/or legacy revids. The version vector, if present, always comes first. The legacy IDs at the end are what allow the recipient of a revision (an active or passive puller) to match up an incoming version vector with …
=> Make sync work across VV upgrades

C/tests/c4DatabaseTest.cc, LiteCore/RevTrees/VectorRecord.cc, LiteCore/RevTrees/VectorRecord.hh
VectorRecord didn't properly manage the `body` column of a doc from a 2.x db that doesn't have the `extra` column. In such a db the body is the encoded rev tree, not just the current rev. VectorRecord was returning that entire slice from its currentRevisionData method ... and since that wasn't valid Fleece data, getting the root Dict would fail.
I added a new member `_bodyDocRange`, a slice that's just the current rev within the _bodyDoc. Normally it's the same as `_bodyDoc.data()`, but in a 2.x doc it encompasses just the current rev body.
Our db upgrade tests didn't catch this because they called `c4doc_getProperties` but not `c4doc_getRevisionBody`. I remedied that (which reproduced the bug.)
Fixes CBL-6239
=> CBL-6239: Fixed c4doc_getRevisionBody in a 2.x db w/version vectors

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/N1QL_Parser/n1ql_parser_internal.hh, LiteCore/Query/QueryParser.cc, LiteCore/tests/N1QLParserTest.cc
Introduced a mew keyword, UNNEST.
Also, moved definition of reserved words from n1ql_parser_internal.h to n1ql.leg, to keep the list from out-of-sync from the LEG grammar, because the definitions in leg file will be compiled by LEG. We found, in n1ql_parser_internal.h, that MISSING is duplicaed, NATURAL and USING are not used, and EXISTS and SOME are missing in the list of kReservedWords
=> CBL-5170: Support Inner Unnest Query in SQL++

C/tests/c4QueryTest.cc, LiteCore/tests/QueryTest.cc
The tests come from the API Specification.
Note that "group-by" does not work with unnest without index.
=> CBL-6207: Test multi-level unnest w/o index.

Replicator/tests/data/docker/docker-compose.yml
SG 3.1.10 was pulled so right now replication tests in master branch are broken. Need to update to 3.1.11
=> CBL-5616: Update SG docker version (again)

LiteCore/Query/SQLiteKeyStore+PredictiveIndexes.cc, LiteCore/Query/Translator/ExprNodes.cc, LiteCore/Query/Translator/IndexedNodes.cc, LiteCore/Query/Translator/IndexedNodes.hh, LiteCore/Query/Translator/Node.cc, LiteCore/Query/Translator/Node.hh, LiteCore/Query/Translator/NodesToSQL.cc, LiteCore/Query/Translator/QueryTranslator.cc, LiteCore/Query/Translator/QueryTranslator.hh, LiteCore/Query/Translator/TranslatorTables.hh, LiteCore/tests/PredictiveQueryTest.cc, LiteCore/tests/QueryTranslatorTest.cc
When implementing the QueryTranslator, I screwed up and forgot to implement index-based predictive queries. Early on in development I commented out groups of tests I hadn't gotten working yet, and somehow I forgot to take out the `#ifdef`s for the predictive-index tests, which is why I didn't notice the problem.
This PR remedies that. Unfortunately it required more code change than I'd like, because predictive indexes work differently than vector or FTS, in that the query works with or without an index. That means when parsing a `PREDICTION()` call the parser has to know whether an index exists, which involves calling out to the QueryTranslator's delegate. That's where the `ParseDelegate` comes from.
Smaller changes:
- Factored out some common code into IndexedNode so the new code can use …
=> QueryTranslator: Implemented predictive index support

LiteCore/Database/SequenceTracker.cc, LiteCore/Database/SequenceTracker.hh
The code that calls observers attempted to protect itself from the list being mutated while it was iterating, but apparently it didn't work well enough.
I changed the code so it now iterates the list collecting the observer pointers, and then calls them afterwards. While I was debugging this I noticed SequenceTracker doesn't have a logging identifier, so I added it.
=> Fixed UB when a CollectionChangeObserver deletes itself in its callback

C/include/c4IndexTypes.h, C/tests/CoreMLPredictiveModel.mm, C/tests/c4QueryTest.cc, C/tests/c4Test.cc, C/tests/c4Test.hh, C/tests/data/students.json, C/tests/data/students2.json, LiteCore/Database/CollectionImpl.hh, LiteCore/Query/IndexSpec.cc, LiteCore/Query/IndexSpec.hh, LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Query/SQLiteKeyStore+ArrayIndexes.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/Support/Logging.cc, LiteCore/tests/N1QLParserTest.cc, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryTest.cc
- C4IndexOptions: added a new field, unnestPath
- N1QL Grammar: changed "UNNEST propertyPath" to "UNNEST expr".
- Although UNNEST can be followed by a general expression, such as "[num[0], num[1]]", but the parser will throw error if the expression is not a propertyPath.
- UNNEST tables are created when createIndex is called with proper propertyPath.
- With multiple levels of UNNEST, the name of unnest table can grow very long. We use SHA1 hash to put a cap on the size of the name.
Others:
- Fixed some warning errors produced by Xcode 16
- Removed two small test json files I put in last commit and extended importJSONFile to allow JSON string inlined in test.
=> CBL-6208: IndexSpec of ArrayIndex with multi-level

LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh
Cherry-pick 02a5393 from CBL-6169 (#2132).
_documentKeys is initialized lazily without protection. We fix it by call_once.
=> CBL-6238: DataFile::documentKeys() is not thread-safe.

LiteCore/Support/Logging.cc
CLion's test runner seems to treat stderr and std::cerr differently!
- Output to stderr is written while the test is running.
- Output to cerr is suppressed while the test is running, then dumped at the end. 
LogDomain::defaultCallback() happens to write the timestamp and domain to cerr, but the message itself to stderr. This means the timestamp/domain are missing in the logs, then show up in a big jumble at the end.
I fixed defaultCallback to write everything to cerr. This shouldn't make a difference to anything but CLion.
=> Make test logs readable in CLion

LiteCore/Storage/SQLiteDataFile.hh
The incorrect value caused every new database to immediately go through the "Adding indexes.lastSeq column" upgrade, a pointless no-op.
=> Fixed incorrect SchemaVersion::Current

LiteCore/Storage/DataFile.cc, LiteCore/Storage/DataFile.hh
This reverts commit 99181ceff7b08e92076ca4db0d0a1550112e1c06.
=> Revert "CBL-6238: DataFile::documentKeys() is not thread-safe. (#2147)"

Replicator/Replicator.hh
So far I've been able to do some manual testing with Sync Gateway.
With this change, with Sync Gateway in the main branch, replication succeeds.
With Sync Gateway 3.1.11, replication fails with a `500 Internal Server Error`.
~~We can't merge this PR until we can get a docker image for Sync Gateway's current main branch, because none of the Sync Gateway Replication tests will pass.~~
EDIT: This statement was not quite accurate, we just need a branch of Sync Gateway with VV + 4.0 protocol enabled. Then some method to manually build Sync Gateway for our docker build process.
=> CBL-6148: Update Replication Protocol for 4.0

C/include/c4IndexTypes.h, Crypto/SecureDigest.hh, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/Query/SQLiteDataFile+Indexes.cc, LiteCore/Query/SQLiteKeyStore+ArrayIndexes.cc, LiteCore/Query/SQLiteKeyStore+Indexes.cc, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/QueryParserTest.cc, LiteCore/tests/QueryTest.cc
- Triggers on the unnest tables: automatically update the unnest tables when the main kv-tables are modified with CRUD operations.
- Deletion of the Array Index also deletes the auxiliary unnest tables that beome used. It becomes involved in the face of multi-level arrays. Considering two indexes on unnestPaths that overlap, such as, a[].b[].c and a[].b[].d. When Index on c is deleted, we cannot delete b or a until index on d is deleted.
- Unit test on deletion of the Array Index.
- Yet to add tests on the triggers of insertion, update, and deletion.
A minor fix of C4IndexOptions::unnestPath by making it NULLABLE.
=> CBL-6082: IndexSpec of ArrayIndex with multi-level

LiteCore/Query/N1QL_Parser/n1ql.cc, LiteCore/Query/N1QL_Parser/n1ql.leg, LiteCore/tests/N1QLParserTest.cc
The previous implementation caused problems with matching certain expressions, because it stripped the parentheses at the top level. Now we strip parentheses at the bottom level, similar to before, but without recursing through the entire stack for every level of parentheses.
=> CBL-6245: Query parser regression related to brackets

CMakeLists.txt, jenkins/build_server_unix.sh
Downstream jobs still use them
=> Add an option to make fat macOS debug builds

Networking/BLIP/Message.cc
Not sure if this is the right approach or not. But as the BLIPMessages is only used for debugging, I think this is a good protection incase the BLIPMessages log is enabled.
=> CBL-6293: BLIP message log may contain document's content

C/tests/c4QueryTest.cc, LiteCore/Query/QueryParser.cc, LiteCore/Query/QueryParser.hh, LiteCore/tests/QueryTest.cc
The cause is found to be the following. The virtual table generated by fl_each includes columns of "body" and "data". The former stores a pointer to preparsed value and the latter stores the original fleece data. When Group-By is called for, SQLite may regenerate rows and renders the body column stale. In order to keep the performance benefit of the body column, we use the data column only when the query uses the GROUP-BY clause.
=> CBL-6255: fl_each with group-by not working

Networking/WebSockets/WebSocketImpl.cc, Replicator/c4Replicator_CAPI.cc, Replicator/c4Socket+Internal.hh, Replicator/c4Socket.cc
The mission of the instrumentation has already accomplished. Remove the code that is not doing anything.
=> CBL-6158: Remove c4SocketTrace as instrumentation for debugging

Networking/BLIP/Message.cc
=> CBL-6292: BLIP message log may contain document's content

C/include/c4IndexTypes.h, LiteCore/Database/CollectionImpl.hh, LiteCore/Query/IndexSpec.hh
Extended C4IndexOptions to include unnestPath for the ArrayIndex.
Note: c4index_getOptions currently won't get back the unnestPath passed to c4createIndex.
=> CBL-6359: C4 APIs for the ArrayIndex

Networking/BLIP/BLIPConnection.cc, Replicator/Checkpoint.cc, Replicator/IncomingRev+Blobs.cc, Replicator/Replicator.cc, Replicator/Replicator.hh, Replicator/Worker.cc, Replicator/c4ReplicatorImpl.hh
- repl config is now logged only once, at the time replicator is started
- error response from blob update specified is a blob req error
- certificates errors are all on the same line now - see https://github.com/couchbasedeps/mbedtls/pull/3 (once is it merged, I will update this PR)
- add URL endpoint to Repl log
=> CBL-6155: Improve LiteCore Log

LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/BothKeyStore.hh, LiteCore/Storage/KeyStore.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/Storage/SQLiteDataFile.hh, LiteCore/Storage/SQLiteKeyStore.cc, LiteCore/Storage/SQLiteKeyStore.hh, LiteCore/tests/c4BaseTest.cc
Fixed by surrounding the column check with the same file lock used when adding the column.
One can verify that the test `Create collection concurrently` fails if you revert the lock change.
=> CBL-6131: Race creating the `expiration` column in a collection table

LiteCore/Storage/BothKeyStore.cc, LiteCore/Storage/KeyStore.hh
Cherry-pick 711f886:
Optimize unsorted enumeration of BothKeyStore (#1858)
Use a different algorithm to enumerate a BothKeyStore when the sortOption is kUnsorted: just enumerate the live docs first, then the deleted ones. This removes the need to order the underlying enumerations, which in turn allows SQLite to use indexes when `onlyConflicts` is set.
This should fix CBL-4506
=> CBL-6282: Replicator starts up slow for big database

C/tests/c4QueryTest.hh, LiteCore/Query/Translator/IndexedNodes.hh, LiteCore/RevTrees/RevTreeRecord.hh, LiteCore/RevTrees/VectorRecord.cc, Replicator/Pusher+Attachments.cc
Because of an outstanding issue with the concomitant PR(#2155) that has to go with the updated Catch2 is having issue with Windows, we update it to the commit just behind the commit that updated Catch2 to v3 (two commits behind the tip, one for Catch2 and one for Doxygen).
=> CBL-6404: Update fleece submodule to the master branch of fleece.

LiteCore/Query/Translator/ExprNodes.cc, LiteCore/Query/Translator/ExprNodes.hh, LiteCore/Query/Translator/SelectNodes.cc, LiteCore/tests/QueryTest.cc
In V3.2, when WHAT clause of the JSON query is absent of empty, we will assign meta properties, _id and _sequence, to the what clause, and use then property names verbatim in the corresponding column names (keep the underscore in the names). In this commit, we mean to keep this behavior with new query translator. The column names are used in the query result of the platform API as the dictionary keys.
=> CBL-6332: Implicit key change in query results

C/tests/c4IndexUpdaterTest.cc, LiteCore/tests/VectorQueryTest.cc
- "IndexUpdater Set Float Array": ORDER_BY is more strict than 3.2. It now requires an explicit array.
- "IndexUpdater not update when released without finish": ORDER_BY is more strict than 3.2. It now requires an explicit array.
- "APPROX_VECTOR_DISTANCE Errors (Misc)": error messages have changed.
- "APPROX_VECTOR_DISTANCE Errors (Bad Metric)": error messages have changed.
=> CBL-6422: Some tests of VectorSearch are failing in 4.0

C/include/c4Document.h, Replicator/Replicator.cc, Replicator/tests/ReplParams.cc, Replicator/tests/ReplParams.hh, Replicator/tests/ReplicatorAPITest.hh, Replicator/tests/ReplicatorCollectionSGTest.cc, Replicator/tests/ReplicatorCollectionSGTest.hh, Replicator/tests/ReplicatorSG30Test.cc, Replicator/tests/SG.cc, Replicator/tests/SG.hh, Replicator/tests/data/docker/sg/Dockerfile, Replicator/tests/data/docker/sg/config/collections/bootstrap.json
Re-enabled and fixed all tests other than "Pull invalid deltas with filter from SG", ~which is blocked by a CBG issue~ [EDIT: It isn't], and will be re-enabled with CBL-5621
=> CBL-6289: Re-enable Actions Replication tests

Xcode/xcconfigs/Project.xcconfig
- there is a test in iOS that is checking for the same version in between platform and LiteCore and has been constantly failing, especially in Jenkins.. which makes any PR red. 
- the update to 3.2.1 on release was missed as I changed the platform project version at the last minute so I saw the test failing long after LiteCore RC was given... so we can do 3.2.2 straight away
We should be doing this at the same time with updating the manifest, after every release, from now on, as LiteCore moved away from dev in XCode. Master is still on 3.2.0 also and should be upped to 4.0
=> Bump XCode project version

LiteCore/Query/QueryParser+VectorSearch.cc
The removal of restriction of "LIMIT > 0" matches that in 4.0 line.
=> CBL-6667: Remove LIMIT restriction in vector search

C/Cpp_include/c4Database.hh, C/Cpp_include/c4DocEnumerator.hh, C/c4.exp, C/c4CAPI.cc, C/c4Database.cc, C/c4DocEnumerator.cc, C/c4Private.h, C/c4_ee.exp, C/include/c4Collection.h, C/include/c4Database.h, C/include/c4DocEnumerator.h, C/include/c4Document.h, C/include/c4Index.h, C/scripts/c4.txt, C/tests/c4DatabaseInternalTest.cc, C/tests/c4DatabaseTest.cc, C/tests/c4DocumentTest.cc, C/tests/c4QueryTest.cc, C/tests/c4Test.hh, C/tests/c4ThreadingTest.cc, LiteCore/Database/VectorDocument.cc, LiteCore/Storage/KeyStore.hh, Replicator/tests/ReplicatorSGTest.cc
semi-deprecated c4db and c4doc APIs which existed only to delegate to c4coll APIs have been removed.
=> CBL-5872: Remove semi-deprecated APIs

C/Cpp_include/c4Database.hh, C/c4Database.cc, C/include/c4DatabaseTypes.h, LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc
- Adds a flag `C4DB_NoHousekeeping` that suppresses database "housekeeping" tasks, and
- makes C4Database::openAgain() set this flag in the database it opens.
Housekeeping tasks like expiring documents and SQLite vacuuming only need to be done by one database connection (C4Database), but we do them in all connections. This means CBL wastes some time and also opens twice as many SQLite connections as it needs to (that _backgroundDB that DatabaseImpl opens.)
It also enables a nasty deadlock condition when the replicator closes its database(s) -- the close call happens on an actor thread, and ends up calling Housekeeper::stop, which sends an Actor message to the Housekeeper and blocks until it's processed. But if all actor threads are doing this, there are no threads left to actually run the …
=> Disable "housekeeping" tasks for db opened with openAgain()

Replicator/ChangesFeed.cc, Replicator/Replicator.cc
Regression from the DatabasePool work: The ChangesFeed now creates its C4DatabaseObserver on the pool's writeable db. Unfortunately this means that during a bidirectional sync it gets notified of the changes the Inserter is making before they're committed, because the Inserter uses the same writeable db instance. That in turn means when the ChangesFeed tries to read the changed documents it often won't see them because it's reading them using a different (readonly) db, which can't see those changes until they're committed.
It gets even worse in Edge Server, because _all_ its writes go through that same db instance. So a continuous pusher would get notified of changes from the REST API too early and often fail to push them.
The fix is to create the C4DatabaseObserver from one of the …
=> ChangesFeed: Don't observe the writeable db [CBL-6763]

C/c4CAPI.cc, LiteCore/Database/CollectionImpl.hh
Bug-fix for the previous fix (#2223). I accidentally left out the most important line of the fix while cleaning up the code for the PR.
This commit makes it so a collection does not create a Housekeeper if the database's kC4DB_NoHousekeeping flag is set.
(cherry-picked from 3.1.9-vf2)
=> Actually disable Housekeeper when kC4DB_NoHousekeeping is set

.gitmodules, CMakeLists.txt, LiteCore/Query/IndexSpec.hh, build_cmake/scripts/run-clang-format.sh, tool_support/ArgumentTokenizer.cc, tool_support/ArgumentTokenizer.hh, tool_support/CMakeLists.txt, tool_support/LiteCoreTool.cc, tool_support/LiteCoreTool.hh, tool_support/README.md, tool_support/Tool.cc, tool_support/Tool.hh
In order to keep submodule dependencies sane, we're moving the code shared between couchbase-mobile-tools and Edge Server into LiteCore. 
That code is the base classes for CLI tools (`Tool` and `LiteCoreTool`) and some code it uses for reading command lines and parsing them into arguments.
These come from the `edge_server` branch of the tools repo (which is going away.) The Tool and LiteCoreTool classes have a bunch of changes from the master branch there -- accumulated over time on the `dev` branch and then later the `edge_server` branch.
=> Moved tool_support dir here from the mobile-tools repo

LiteCore/Support/DatabasePool.cc, build_cmake/scripts/check_deps.py, cmake/platform_win.cmake, jenkins/couchbase-lite-core-black-duck-manifest.yaml
When LITECORE_BUILD_SHARED is off, don't do anything to LiteCore target since it doesn't exist
=> Fix Windows build of tools (cbl-log, cblite, etc)

C/Cpp_include/c4Database.hh, LiteCore/Database/DatabaseImpl.hh
Edge Server needs to reset UUIDs without copying the database.
The `DatabaseImpl::resetUUIDs()` method does that, but it's awkward to call from Edge Server because including DatabaseImpl.hh requires adding like a dozen more header search paths to the target. Plus it's nicer not to grope into the internals.
=> API: Expose C4Database::resetUUIDs() method [CBL-6648]

jenkins/build_server_android.sh, jenkins/build_server_win.ps1
To not use the now nonexistent root level CMakeLists.txt, but instead use the one from this repo.
=> Adjust build scripts for Windows and Android

LiteCore/Support/LogEncoder.cc, LiteCore/Support/LogEncoder.hh, LiteCore/Support/Logging.cc, LiteCore/Support/Logging.hh, LiteCore/tests/LogEncoderTest.cc
To avoid a deadlock on Android, we prevent the `Logging` class's destructor from requiring the `sLogMutex`. Instead, the functions that use `sObjectMap` will use their own mutex.
This is straightforward except for the way Logging passes a reference to `sObjectMap` to the LogEncoder, totally breaking encapsulation. Sigh. I fixed this the way I did on the log-observer branch, by having the LogEncoder take the object path directly and giving the logger a way to tell whether it needs to compute the path.
=> Logging: Use a separate mutex to protect sObjectMap [CBL-6787]

LiteCore/Database/LiveQuerier.cc, LiteCore/Database/SequenceTracker.cc, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/DataFile.cc, LiteCore/Support/Logging.cc, Networking/BLIP/BLIPConnection.cc, Replicator/Worker.cc, Replicator/c4ReplicatorImpl.hh
1. Use timed_mutex to work around deadlocks
2. Commented out logging calls in Logging destructor overrides
=> Further logging-deadlock workarounds

Networking/TCPSocket.cc
* Updated sockpp submodule to fix client cert verification for certificate chains.
* Regarding the fix in sockpp, ensure errors are cleared for non-leaf certificates when verifying client certificates using an auth callback. The result that is matter is the verification result of the leaf cert on the last callback.
* Applied an additional fix in LiteCore as `TLS P2P Sync non self-signed cert` test failed after updating the sockpp. Here is the detail:
- When `onlySelfSignedAllowed()` is used, the server cert will be verified in the auth callback that the server cert is a self-signed or not (See 637f54f992fa9e2852e1871602f780422e7b1115 for more detail.)
- With the fix in sockpp that clears the error on non-leaf cert, the returned error from the auth callback() if is non-self-signed cert is …
=> CBL-6820: Update sockpp to fix client cert verification for certificate chains

modules/docs/pages/replication-protocol.adoc
First commit fixes sublists being eaten, caught by `asciidoctor` and by eye.
- Put a visual separation between properties and body definition. Fixes a case where missing `+` was present.
Substantive part of the changes was adding `deltaSrc` property to the definition.
=> Add deltaSrc to replication protocol

Replicator/Replicator.cc
SQLite disk full gives POSIX error 28, as per: https://www.couchbase.com/forums/t/handling-sqlite-error-13/40343/6
=> CBL-6886: Replicator should stop on SQLite disk full error.

C/include/c4ReplicatorTypes.h, Crypto/PublicKey.hh, Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/WebSocketImpl.hh, Replicator/c4RemoteReplicator.hh, Replicator/c4Socket+Internal.hh, Replicator/c4Socket.cc
- Override ExternalPrivateKey::isPrivateKeyDataAvailable to return false.
- Add a new bool option, kC4ReplicatorAuthClientCertKeyIsExternal, to C4ReplicatorParameters.
- Decode the new parameter in BuiltInWebScoket.
=> CBL-6902: External Keys to work with client cert

C/c4Base.cc, C/c4Certificate.cc, C/c4Database.cc, C/c4Log.cc, C/c4Query.cc, C/include/c4Compat.h, LiteCore/Support/TestsCommon.cc
From now on use CBL_CORE_API_IMPL on implementations of exported symbols.
Includes https://github.com/couchbase/fleece/pull/261
=> Fixed CBL_CORE_API to avoid GCC attribute warnings

jenkins/build_server_unix.sh
This seems to be a cherry pick mistake of some kind.  The project dir no longer exist in master since the top level CMakeLists.txt was removed.
=> Fix unbound variable usage

REST/c4Listener.cc
The C4Listener modifications to support Edge Server inadvertently changed the behavior of `C4Listener::shareDB` such that it now takes over the C4Database instance. That means it'll be using it on its background threads, and will close it when the listener is closed. That's bad. This PR returns it to the previous/documented behavior.
=> Fix for C4Listener::shareDB taking over the db instance

REST/c4Listener.cc
- The previous commit accidentally passed `db` not `dbCopy` to `registerDatabase()`, so it had no effect. Oops.
- It isn't necessary to close `dbCopy` explicitly on failure; the destructor will close it.
Thanks to @jianminzhao for pointing out the mistake.
=> Correct fix for C4Listener::shareDB taking over the db instance

C/include/c4Replicator.h, Replicator/c4Replicator_CAPI.cc
Change the return type to C4SliceResult to make sure the memory is not freed in the unlikely case that it's still in use when Replicator disconnects.
=> CBL-6839: c4repl_getResponseHeaders() can cause use-after-free bugs

Replicator/ChangesFeed.cc, Replicator/ChangesFeed.hh, Replicator/DBAccess.hh, Replicator/EchoCanceler.hh, Replicator/Inserter.cc, Replicator/tests/ReplicatorCollectionTest.cc
This fixes a performance issue in bidirectional continuous sync. After the puller saves revs received from the peer, the ChangesFeed observes those revs being added to the db and tells the pusher to send them to the peer, which then rejects them with a 304.
The fix is to briefly track the revisions being added to the local db, then ignore them when they're reported by the C4DatabaseObserver.
I'm fixing this now because this situation will happen in all P2P replications, and since peers will be running multiple replications we want to get rid of any obvious wastes of CPU  and I/O like this one.
=> Keep pulled revs from being echoed back to the peer by the Pusher

Replicator/Pusher+Revs.cc, Replicator/Pusher.cc, Replicator/tests/ReplicatorLoopbackTest.hh
This PR contains three fixes for Pusher bugs that have the same effect: not marking local sequences as completed, thus leaving gaps in the checkpointer's SequenceSet.
I saw a failure of "Continuous Super-Fast Push" from a Windows build,
where the ending checkpoint was incorrect. Near the end of that test
it logged the active replicator checkpoint as:
`{"local":42,"localCompleted":[0,43,48,154]}`
which is clearly wrong as it shows some sequences unable to be sent.
> FYI: The `localCompleted` property in a checkpoint is an encoding of a non-contiguous SequenceSet. Each pair of ints in the array gives a starting sequence and the number of completed sequences starting from it. So in the example above sequences in the ranges 0-42 and 48-201 are complete, but 43-47 are not complete.
The test …
=> Fix Pusher bugs that omit sequences from checkpoint 

LiteCore/Database/LiveQuerier.cc, LiteCore/Database/SequenceTracker.cc, LiteCore/Query/SQLiteQuery.cc, LiteCore/Storage/DataFile.cc, Networking/BLIP/BLIPConnection.cc, Replicator/Worker.cc
We restored the changes of bbd241d96d as regard to "Commented out logging calls in Logging destructor overrides" since the logging code has been enhanced significantly and no longer vulnerable to the issue of calling in the destructor.
=> CBL-6960: Consider to restore the logs in destructors

C/Cpp_include/c4PeerDiscovery.hh
([Actual fix is in EE repo](https://github.com/couchbase/couchbase-lite-core-EE/pull/51).) 
Sometimes BonjourProvider would pass on the `moreComing` flag when adding/removing a peer, but its next event it got with moreComing=false didn't trigger any calls to PeerDiscovery, leaving the latter hanging.
Added `noMorePeersComing()` method for this situation.
=> Fixed BonjourProvider not notifying some peer changes

LiteCore/Query/Translator/IndexedNodes.cc, LiteCore/Query/Translator/Node.hh, LiteCore/Query/Translator/QueryTranslator.cc, LiteCore/Query/Translator/SelectNodes.cc, LiteCore/Query/Translator/SelectNodes.hh, LiteCore/tests/PredictiveQueryTest.cc
The main issue is that we need to know the kv table on which the PredictiveNode is created, and the pass that SourceNodes are assigned table names is run after the pass all nodes are created.
Several technical changes.
- SourceNode::collection() is empty string only if it's not given in the query expression. (Currently it will be turned to empty string if explicitly given "_default."
- We assign the table name to the main data source in the pass of node creation, so that it can be used when PredictiveNode is populated. It can be later altered if flag _usesDeleted is set.
- The result of keystore.compileQuery() should be the same, except that empty data source in the FROM clause will be substituted for with collection corresponding to the invoking key store.
=> CBL-6285: Explain for predictive query no longer names an index

C/include/c4CertificateTypes.h, C/tests/c4CertificateTest.cc, Replicator/ChangesFeed.cc
In LiteCore, the corresponding constant is kC4Cert_Locality.
The component, "locality", of the subject name of the certificate works when it's used to create the certificate. When query the component of a certificate, it's shown as "L". The pleasant fact is that the abbreviated name, "L", also works to create the certificate.
We change it to "L" from "locality".
Also fixed an uninitialized error complained by Xcode analyzer.
=> CBL-6971: Cannot access the kCBLCertAttrKeyLocality value from the cert attributes

Replicator/c4Replicator.cc, Replicator/tests/ReplicatorAPITest.cc, Replicator/tests/ReplicatorCollectionSGTest.cc
We won't check the validity of the database name in the URL. The format of the name should be managed as the name is created.
=> CBL-6952: Revise Database name validation in C4Address.fromURL()

Replicator/IncomingRev.cc, Replicator/IncomingRev.hh
The original problem was essentially that the IncomingRev was settings its own status to Stopped and resetting its parent while another function of the IncomingRev (`handleRev`) was executing on the Puller's thread.
The solution is to make sure IncomingRev doesn't report Stopped when the Puller is running `handleRev`, and to avoid status updates on the IncomingRev's thread, and instead update status on the Puller's thread.
Basically the whole lifecycle of the IncomingRev (`handleRev` to begin, `reset` to end) is run on the Puller's thread.
The IncomingRev only uses `Stopped` or `Busy` status. `Busy` status should always be set once the Puller has called `handleRev`, `Stopped` status should always be set once the Puller has called `reset`. 
We now use an atomic boolean to track this so the …
=> CBL-7064: Pull filter can cause assertion failure during replication

C/Cpp_include/c4PeerDiscovery.hh, LiteCore/Support/ObserverList.cc, LiteCore/Support/ObserverList.hh
- CBL-7101, CBL-7102: Ensure proper shutdown of C4PeerSync / MeshManager by making it safe to release it before the stop method has completed.
- CBL-7134: Ensure Observers are removed from ObserverLists before they destruct.
(most of the changes are in https://github.com/couchbase/couchbase-lite-core-EE/pull/58 .)
=> C4PeerSync shutdown fixes

Replicator/Replicator.cc
I used LiteCore 3.3.0-80 to reproduce the native crash when the following tests are reinstated,
- ReplicatorPendingDocIdTest
- ReplicatorLocal2LocalTest
The issue is specific to LoopbackWebSocket. We need to guard against the case when Replictor::_onConnect comes after it is stopped.
=> CBL-7013: Native crash when using LiteCore 3.3.0-80

C/Cpp_include/Observer.hh, C/Cpp_include/c4PeerDiscovery.hh, LiteCore/Support/ObserverList.hh
- Split out Observer.hh from ObserverList.hh, and put it in CInclude/. This new header has no special dependencies.
- Moved fields of C4PeerDiscovery into an Impl class whose declaration is non-public
- c4PeerDiscovery.hh now includes Observer.hh, not ObserverList.hh.
Implementation changes are in https://github.com/couchbase/couchbase-lite-core-EE/pull/61
=> c4PeerDiscovery.hh no longer uses nonpublic headers

Crypto/PublicKey+Apple.mm
**Problem**
In version 3.3.0, we enhanced the TLSIdentity API to support creating identities signed by an issuer. These identities include a certificate chain (leaf + root), all saved into the Keychain. However, when deleting the identity using the persistent label, only the leaf certificate was removed — the root or intermediate certs remained.
The root cause is that the deletion logic in Cert::deleteCert(const std::string &persistentID) relies on checking whether a certificate is an issuer for other certs. Basically, this check skips deleting certificates with multiple children. However, it doesn’t account for self-signed root certs, which are their own issuers, resulting in the root cert not being deleted.
**Fixes**
* Updated the deletion logic to correctly handle and delete …
=> CBL-7156 : Fix iOS cert chain deletion to handle self-signed roots ad ensure safe removal

Crypto/CertificateTest.cc, LiteCore/tests/CMakeLists.txt, Xcode/LiteCore.xcodeproj/project.pbxproj
The code is in the EE repo. This commit adds a new file to LiteCore/test/CMakeList.txt.
Also added ExpectingException to a number of tests in Crypto/CertificateTest.
=> CBL-7174: Multipeer Test: Document IDs Filter

C/Cpp_include/c4PeerDiscovery.hh, C/include/c4PeerSyncTypes.h, Networking/WebSockets/WebSocketImpl.cc
[Most of this PR is in EE](https://github.com/couchbase/couchbase-lite-core-EE/pull/69). The significant thing here is a WebSocket fix:
If the WS heartbeat interval is set to 10 sec or lower, the socket
wouldn't detect missing PONGs and so wouldn't close.
The reason is that every time it sends a PING it resets the 10-sec
PONG timeout, so the PONG timeout is never triggered.
Fixed by ensuring that the PONG timeout is at least one second
shorter than the PING interval.
=> P2P: Better handling of peer connection errors [CBL-7170]

Replicator/IncomingRev.cc, Replicator/IncomingRev.hh
The scenario of the issue: at the end of IncomingRev::handleRev, we branch either continuing on the caller(puller)'s thread, or dispatching to the IncomingRev's thread.
- The bug occurs in the latter situation when IncomingRev::afterEvent is called.
- And when it is called after IncomingRev::finish is called on the Inserter's thread, which can cause the object to be recycled by the puller after being informed by Puller::revWasHandled.
We fix the bug by ensuring IncomingRev::afterEvent is called before Puller::revWasHandled.
=> CBL-7189: Pull filter can cause assertion failure during replication

Networking/WebSockets/BuiltInWebSocket.cc, Networking/WebSockets/BuiltInWebSocket.hh
Turns out my previous PR for CBL-7170 only sets the heartbeat/PING interval for client WebSockets, because those WS parameters aren't passed BuiltinWebSocket's server-side constructor. This means it still takes 5 minutes to discover a peer's vanished if the other peer was the one making the connection. This PR and [its EE counterpart](https://github.com/couchbase/couchbase-lite-core-EE/pull/71) fix that.
This commit makes it possible to configure the heartbeat (PING) interval of a server-side BuiltinWebSocket.
(For API consistency this makes it possible to configure all of the WS parameters, but the heartbeat is the only one relevant to a server, I think.)
=> Allow setting heartbeat of server BuiltinWebSocket [CBL-7170]

Replicator/tests/SG.cc, Xcode/LiteCore.xcodeproj/project.pbxproj
Added RESTClietTest.cpp to "CppTests EE" of XCode target. It is in this target of CMake.
=> CBL-7346: Add User-Agent to headers in SG::createRequest

Replicator/IncomingRev.cc, Replicator/IncomingRev.hh, Replicator/Puller.cc
When errors occur (while waiting attachments), the IncomiingRev would be sent to queue _returningRevs multiple times. This can cause BAD ACCESS exception as the second time it is handled in _revsFinished.
=> CBL-7347: Crash in puller _revsFinished

C/include/c4DatabaseTypes.h, LiteCore/Database/DatabaseImpl.cc, LiteCore/Storage/DataFile.hh, LiteCore/Storage/SQLiteDataFile.cc, LiteCore/tests/c4BaseTest.cc
* Set the mmap_size to zero to disable the mmap.
* Remove an option to disable the mmap from the API.
=> CBL-6569 : Disable SQLite’s mmap by default

Replicator/Replicator.cc, Replicator/Replicator.hh
...after the connection has closed.
Solution is to copy the response to the Replicator when it arrives, instead of assuming the WebSocket is still around at the time of the call.
=> Fixed race condition calling Replicator::httpResponse() [CBL-7419]

C/tests/c4DocumentTest.cc, LiteCore/RevTrees/Version.cc, LiteCore/RevTrees/VersionVector.cc, LiteCore/tests/VersionVectorTest.cc
If the `anyone` is false (as it is by default), the method is supposed to skip the call to `clock.see()` if this Version is by the local author.
Unfortunately I got the logic wrong and it ends up skipping `clock.see()` if this Version is by _anyone but_ the local author.
That's bad because we always want to check timestamps from other authors, because their clocks might be skewed.
(I just discovered this by code inspection, while porting this code to TypeScript.)
=> Fixed bug in Version::updateClock()

C/Cpp_include/c4Document.hh, C/c4CAPI.cc, C/c4Document.cc, C/include/c4Document.h, LiteCore/Database/TreeDocument.cc, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/RawRevTree.cc, LiteCore/RevTrees/RevID.cc, LiteCore/RevTrees/RevID.hh, LiteCore/RevTrees/SourceID.hh, LiteCore/RevTrees/VectorRecord.cc, LiteCore/RevTrees/VectorRecord.hh, LiteCore/RevTrees/Version.cc, LiteCore/RevTrees/Version.hh, LiteCore/RevTrees/VersionVector.cc, LiteCore/RevTrees/VersionVectorWithLegacy.hh, LiteCore/tests/VectorRecordTest.cc, LiteCore/tests/VersionVectorTest.cc, Replicator/IncomingRev.cc, Replicator/Pusher.cc, Replicator/RevFinder.cc, Replicator/tests/ReplicatorLoopbackTest.hh, Replicator/tests/ReplicatorVVUpgradeTest.cc
The key changes:
- Implemented [the scheme I'd come up with but forgotten about](https://docs.google.com/document/d/1hqeuQ7dlCD1XWsjnxRW6L5E15diLXkfo0Xn5F9vs13c) to represent a legacy revID as a version.
- Improved VectorRecord to be able to save a new revision with a legacy revid, which can happen when pulling from a peer that made further changes to the same doc before upgrading the db.
=> Fixed problems syncing partially VV-upgraded database [CBL-6666, CBL-6593]

LiteCore/Database/VectorDocument.cc, Replicator/tests/ReplicatorLoopbackTest.cc
Return error in VectorDocument::putExistingRevision when allowConflict is false and the new revision will cause conflict flag. This also matches the behavior of TreeDocument.
=> CBL-5315: Reinstate flaky test "Continuous Push From Both Sides" for VV

C/include/c4Document.h, C/tests/c4DocumentTest.cc, LiteCore/Database/VectorDocument.cc, LiteCore/RevTrees/SourceID.hh, LiteCore/RevTrees/VersionVector.cc, LiteCore/RevTrees/VersionVector.hh, LiteCore/tests/VersionVectorTest.cc, Replicator/tests/ReplicatorCollectionTest.cc, Replicator/tests/ReplicatorLoopbackTest.cc, Replicator/tests/ReplicatorLoopbackTest.hh
Per @torcolvin's new design.
When resolving a conflict, if the merged revision has the same body as the winning rev, generate a "trivial merge" version vector. This doesn't have the form of a merge VV; instead it just adds the versions from the losing VV but keeps the same current version as the winner.
In terms of the API, a trivial merge results when calling `c4doc_resolveConflict` and the `mergedBody` is either nullslice or is an equivalent FLDict to the winning rev's body.
Reference : CBL-7455
=> Updated VV conflict resolution when keeping winning rev's body

Networking/WebSockets/WebSocketImpl.cc
We have a crash in Timer::Manager::setFireTime. It is called while WebSocketImpl::~WebSocketImpl() is active on the stacks. We add a guard in sendPing to guard against scheduling the next ping. This is a callback that can fire at anytime.
=> CBL-7490 : Crash in WebSocketImpl::sendPing() while WebSocket is being closed
